name: "Build Fusion Telemetry Core App"
description: "Build Fusion Telemetry Core App"
inputs:
  flutter_apps_sonar_token:
    description: 'SonarQube server token'
    required: true
  nexus_password:
    description: 'Nexus repository password'
    required: true
  jenkins_user_name:
    description: 'Jenkins username for authentication'
    required: true
  jenkins_user_token:
    description: 'Jenkins token for authentication'
    required: true
  jenkins_url:
    description: 'Nexus repository URL'
    required: true
  nexus_url:
    description: 'Nexus repository URL'
    required: true
        
runs:
  using: "composite"
  steps:
    - name: Build with WAF
      shell: bash
      working-directory: apps/firmware-apps/fusion-telemetry-core
      run: |
        moon run fusion-telemetry-core:build
        VERSION="$(./Jenkins/SetVersionProperty.sh)-${GITHUB_RUN_NUMBER}+$(git rev-parse --short HEAD)"
        curl -k --ssl-no-revoke -f -u github-actions-uploader:${{ inputs.nexus_password }} -T ./build/telemetry_core ${{ inputs.nexus_url }}/Fusion-Telemetry-Core/Continuous/${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}/fusion-telemetry-core/$VERSION/fusion-telemetry-core-$VERSION
        echo "Fusion Telemetry Core build uploaded to Nexus successfully!"
        echo "fusion-telemetry-core: ${{ inputs.nexus_url }}/Fusion-Telemetry-Core/Continuous/${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}/fusion-telemetry-core/$VERSION/fusion-telemetry-core-$VERSION"