name: "Build Fusion System Monitor App"
description: "Build Fusion System Monitor App"
inputs:
  flutter_apps_sonar_token:
    description: 'SonarQube server token'
    required: true
  nexus_password:
    description: 'Nexus repository password'
    required: true
  jenkins_user_name:
    description: 'Jenkins username for authentication'
    required: true
  jenkins_user_token:
    description: 'Jenkins token for authentication'
    required: true
  jenkins_url:
    description: 'Nexus repository URL'
    required: true
  nexus_url:
    description: 'Nexus repository URL'
    required: true
        
runs:
  using: "composite"
  steps:
    - name: Build with Waf
      shell: bash
      working-directory: apps/firmware-apps/fusion-system-monitor
      run: |
        moon run fusion-system-monitor:build
        VERSION="$(./Jenkins/SetVersionProperty.sh)-${GITHUB_RUN_NUMBER}+$(git rev-parse --short HEAD)"
        curl -k --ssl-no-revoke -f -u github-actions-uploader:${{ inputs.nexus_password }} -T ./build/fusion_system_monitor ${{ inputs.nexus_url }}/Fusion-System-Monitor/Continuous/${GITHUB_REF_NAME}/fusion-system-monitor/$VERSION/fusion-system-monitor-$VERSION
        echo "Fusion System Monitor build uploaded to Nexus successfully!"
        echo "fusion-dsp: ${{ inputs.nexus_url }}/Fusion-System-Monitor/Continuous/${GITHUB_REF_NAME}/fusion-system-monitor/$VERSION/fusion-system-monitor-$VERSION"