// GENERATED CODE - DO NOT MODIFY BY HAND
// This file was generated by assets_generator.py

class AssetImages {
  static const String _path = 'assets/images';
  // Images Files
  static const String amplifierImg = '$_path/amplifier_img.webp';
  static const String amplifiersBanner = '$_path/amplifiers_banner.png';
  static const String boseDsp = '$_path/bose_dsp.png';
  static const String boseProDark = '$_path/bose_pro_dark.webp';
  static const String boseProDsp = '$_path/bose_pro_dsp.webp';
  static const String boseProLogoB = '$_path/bose_pro_logo_b.webp';
  static const String boseProLogoNew = '$_path/bose_pro_logo_new.png';
  static const String boseSpeaker = '$_path/bose_speaker.webp';
  static const String checkMark = '$_path/check_mark.webp';
  static const String color = '$_path/color.png';
  static const String coverage = '$_path/coverage.png';
  static const String defaultImage = '$_path/default_image.png';
  static const String dspBanner = '$_path/dsp_banner.png';
  static const String filter = '$_path/filter.png';
  static const String fusionDefaultIcon = '$_path/fusion_default_icon.png';
  static const String highToLow = '$_path/high_to_low.png';
  static const String impedance = '$_path/impedance.png';
  static const String infocommBanner = '$_path/infocomm_banner.png';
  static const String launcherBgPattern = '$_path/launcher_bg_pattern.png';
  static const String launcherHero = '$_path/launcher_hero.png';
  static const String loudSpeaker = '$_path/loud_speaker.webp';
  static const String lowToHigh = '$_path/low_to_high.png';
  static const String mountType = '$_path/mount_type.png';
  static const String processorImg = '$_path/processor_img.webp';
  static const String rackImg = '$_path/rack_img.webp';
  static const String returnIcon = '$_path/return_icon.png';
  static const String shareIcon = '$_path/share_icon.png';
  static const String sortAToZ = '$_path/sort_a_to_z.png';
  static const String sortDescending = '$_path/sort_descending.png';
  static const String sourceIcon = '$_path/source_icon.png';
  static const String sourceSetIcon = '$_path/source_set_icon.png';
  static const String speakerBanner = '$_path/speaker_banner.png';
  static const String uploadFloorPlan = '$_path/upload_floor_plan.png';
  static const String venueType = '$_path/venue_type.png';
  static const String zoneIcon = '$_path/zone_icon.png';
}
