name: "Build Cloud Services UI"
description: "Build Cloud Services UI"

runs:
  using: "composite"
  steps:
    - name: Cloud Services UI build
      shell: bash
      working-directory: apps/frontend/react-apps
      run: |
        moon run react-apps:build-all
