#!/bin/bash
set -euo pipefail

# Build the fusion-gateway binary and optionally a release package.
#
# Usage:
#   ./build-fusion-gateway [--target <target>] [--package]
#     --target        Specify the target operating system (default: linux)
#     --package   Build a release package with required config files, etc.

# Default values
BINARY_NAME="fusion-gateway"
ARCH="${ARCH:-arm64}"
TARGET="linux"
PACKAGE=false

# Process command-line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --target)
            TARGET="$2"
            shift 2
            ;;
        --package|-p)
            PACKAGE=true
            shift
            ;;
        *)
            echo "Unknown parameter: $1"
            exit 1
            ;;
    esac
done

EXPECTED_BINARY="${BINARY_NAME}_${TARGET}_${ARCH}"

# Clean up old binary if it exists
if [ -f "$BINARY_NAME" ]; then
    echo "Removing old binary..."
    rm "$BINARY_NAME"
fi

# Build the binary
echo "Building ${BINARY_NAME} for ${TARGET}_${ARCH}..."
make "build-${TARGET}-${ARCH}"

# Check if the build produced the expected binary
if [ ! -f "build/$EXPECTED_BINARY" ]; then
    echo "Error: Build failed to produce ${EXPECTED_BINARY}"
    exit 1
fi

# Rename the binary
echo "Creating binary symlink to $BINARY_NAME"
pushd ./build > /dev/null
ln -sf "$EXPECTED_BINARY" "$BINARY_NAME"
popd > /dev/null

if [ "$PACKAGE" = true ]; then
    # Make a "release package" with the binary, config files and version info.
    VERSION=${VERSION:-LOCAL}
    commit_id=$(git rev-parse HEAD)
    full_version=$VERSION

    # Jenkins will set a 'branchName' environment variable, but for local builds we need to get it.
    BRANCH=${branchName:-}
    if [ -z "$BRANCH" ]; then
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
    fi

    cat << EOF_VERSION > build/fusion-gateway.info
APP="fusion-gateway"
VERSION="$VERSION"
BRANCH="$BRANCH"
COMMIT_ID="$commit_id"
COMMIT_DATE="$(TZ=UTC0 git --no-pager log -1 --pretty='format:%cd' --date='format-local:%Y-%m-%dT%H:%M:%S+00:00')"
BUILD_DATE="$(date -u -Iseconds)"
EOF_VERSION
    
    tar -czhf "build/fusion-gateway_${full_version}.tar.gz" scripts/*.service scripts/generate_cloud_config.sh \
              build/$BINARY_NAME build/fusion-gateway.info scripts/fusion-gateway-start.sh
    rm build/fusion-gateway.info
fi

echo "Build process completed successfully."
