CREATE TABLE user_profile (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    job_title VARCHAR(100),
    phone VARCHAR(30),
    profile_photo_url VARCHAR(2048),
    address_line_1 VARCHAR(255),
    city VARCHAR(100),
    state_province VARCHAR(100),
    country VARCHAR(100),
    zip_postal_code VARCHAR(20),
    gdpr_opt_out BOOLEAN DEFAULT false,
    privacy_policy_accepted BOOLEAN DEFAULT false,
    linked_profiles JSONB,
    timezone VARCHAR(64),
    unit_system VARCHAR(20),
    customer_type VARCHAR(50),
    client_type VARCHAR(50),
    company_name VARCHAR(255),
    company_website VARCHAR(2048),
    currency VARCHAR(10),
    netsuite_customer_id VARCHAR(255),
    price_list JSONB,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp,
    
    FOREIGN KEY (user_id) REFERENCES app_user(id)
);  