name: "Build Cloud Services Backend"
description: "Build Cloud Services Backend"
inputs:
  cloud_backend_sonar_token:
    description: 'SonarQube server token'
    required: true
  nexus_password:
    description: 'Nexus repository password'
    required: true
  nexus_url:
    description: 'Nexus repository URL'
    required: true

runs:
  using: "composite"
  steps:
    - name: Read version from version.txt
      id: read_version
      working-directory: apps/cloud-backend/fusion-cloud
      shell: bash
      run: |
        VERSION=$(cat version.txt)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    # - name: SonarQube Scan
    #   uses: SonarSource/sonarqube-scan-action@v5
    #   env:
    #     SONAR_TOKEN: ${{ inputs.cloud_backend_sonar_token }}
    #   with:
    #     projectBaseDir: 'apps/cloud-backend/fusion-cloud'

    - name: Cloud Services Backend
      shell: bash
      working-directory: apps/cloud-backend/fusion-cloud
      run: |
        moon run fusion-cloud:build
        VERSION="${{ steps.read_version.outputs.version }}-${GITHUB_RUN_NUMBER}+$(git rev-parse --short HEAD)"
        curl -k --ssl-no-revoke -f -u github-actions-uploader:${{ inputs.nexus_password }} -T ./fusion-web-services ${{ inputs.nexus_url }}/Fusion-Cloud-Backend/Continuous/$VERSION/fusion-web-services-$VERSION

