name: "Build Cloud Services Backend"
description: "Build Cloud Services Backend"
inputs:
  cloud_backend_sonar_token:
    description: 'SonarQube server token'
    required: true
  nexus_password:
    description: 'Nexus repository password'
    required: true
  nexus_url:
    description: 'Nexus repository URL'
    required: true
  DOCKER_REGISTRY_DEV:
    description: 'Docker registry for development'
    required: true
  AWS_ACCESS_KEY_ID_DEV:
    description: 'AWS Access Key ID for development'
    required: true
  AWS_SECRET_ACCESS_KEY_DEV:
    description: 'AWS Secret Access Key for development'
    required: true
  AWS_ECS_CLUSTER:
    description: 'AWS ECS Cluster for development'
    required: true
  AWS_ECS_SERVICE:
    description: 'AWS ECS Service for development'
    required: true
  AWS_ECS_TASK_DEFINITION:
    description: 'AWS ECS Task Definition for development'
    required: true
  AWS_DEFAULT_REGION:
    description: 'AWS Default Region for development'
    required: true

runs:
  using: "composite"
  steps:
    - name: Read version from version.txt
      id: read_version
      working-directory: apps/cloud-backend/fusion-core
      shell: bash
      run: |
        VERSION=$(cat version.txt)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    # - name: SonarQube Scan
    #   uses: SonarSource/sonarqube-scan-action@v5
    #   env:
    #     SONAR_TOKEN: ${{ inputs.cloud_backend_sonar_token }}
    #   with:
    #     projectBaseDir: 'apps/cloud-backend/fusion-cloud'

    - name: Cloud Services Backend Tests
      shell: bash
      working-directory: apps/cloud-backend/fusion-core
      run: |
        moon run fusion-core:test
        moon run fusion-core:integration-tests
        VERSION="${{ steps.read_version.outputs.version }}-${GITHUB_RUN_NUMBER}+$(git rev-parse --short HEAD)"
        docker build -t ${{ inputs.DOCKER_REGISTRY_DEV }}/go-image:$(git rev-parse --short HEAD) .
        docker image ls ${{ inputs.DOCKER_REGISTRY_DEV }}/go-image:$(git rev-parse --short HEAD)
     #    curl -k --ssl-no-revoke -f -u github-actions-uploader:${{ inputs.nexus_password }} -T ./fusion-web-services ${{ inputs.nexus_url }}/Fusion-Cloud-Backend/Continuous/${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}/$VERSION/fusion-web-services-$VERSION

    - name: Login to ECR
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.DOCKER_REGISTRY_DEV }}
        username: ${{ inputs.AWS_ACCESS_KEY_ID_DEV }}
        password: ${{ inputs.AWS_SECRET_ACCESS_KEY_DEV }}
    
    - name: Push docker image
      shell: bash
      working-directory: apps/cloud-backend/fusion-core
      run: |
        docker image ls ${{ inputs.DOCKER_REGISTRY_DEV }}/go-image:$(git rev-parse --short HEAD)
        docker push ${{ inputs.DOCKER_REGISTRY_DEV }}/go-image:$(git rev-parse --short HEAD)

    - name: Trigger new ECS deployment
      shell: bash
      working-directory: apps/cloud-backend/fusion-core
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID_DEV }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY_DEV }}
      run: aws ecs update-service --cluster ${{ inputs.AWS_ECS_CLUSTER }} --service ${{ inputs.AWS_ECS_SERVICE }} --task-definition ${{ inputs.AWS_ECS_TASK_DEFINITION }} --force-new-deployment