package model

type Product struct {
	ID int64 `json:"id"`
	// Type string      `json:"type"`
	SKU  interface{} `json:"sku"`
	Name string      `json:"name"`
	// Published                                 interface{} `json:"published"`
	// IsFeatured                                int         `json:"is_featured"`
	// VisibilityInCatalog                       string      `json:"visibility_in_catalog"`
	// ShortDescription                          string      `json:"short_description"`
	// Description                               string      `json:"description"`
	// Weight                                    string      `json:"weight"`
	// Length                                    string      `json:"length"`
	// Width                                     string      `json:"width"`
	// Height                                    string      `json:"height"`
	// Categories                                string      `json:"categories"`
	// Tags                                      string      `json:"tags"`
	Images []string `json:"images"`
	// Position                                  int         `json:"position"`
	// ChannelSeparationAmplification            string      `json:"channel_separation_amplification"`
	// DynamicRangeAmplification                 string      `json:"dynamic_range_amplification"`
	// FrequencyResponseAmplification            string      `json:"frequency_response_amplification"`
	// GainHighImpedanceAmplification            string      `json:"gain_highimpedance_amplification"`
	// GainLowImpedanceAmplification             string      `json:"gain_lowimpedance_amplification"`
	// MaximumPeakPowerAsymmetricalAmplification string      `json:"maximum_peak_power_asymmetrical_amplification"`
	MaximumPeakPowerSymmetricalAmplification []string    `json:"maximum_peak_power_symmetrical_amplification"`
	NumberOfChannelsAmplification            interface{} `json:"number_of_channels_amplification,omitempty"`
	// PowerClassAmplification                   string      `json:"power_class_amplification"`
	// RatedPowerAsymmetricalAmplification       string      `json:"rated_power_asymmetrical_amplification"`
	// RatedPowerSymmetricalAmplification        string      `json:"rated_power_symmetrical_amplification"`
	// SnrAmplification                          string      `json:"snr_amplification"`
	// ThdnAmplification2                        string      `json:"thdn_amplification2"`
	// AECEnabledAcousticEchoCancelation         string      `json:"aecenabled_acoustic_echo_cancelation"`
	// ChannelsAcousticEchoCancelation           interface{} `json:"channels_acoustic_echo_cancelation"`
	// LatencyAcousticEchoCancelation            string      `json:"latency_acoustic_echo_cancelation"`
	// NoiseReductionAcousticEchoCancelation     string      `json:"noise_reduction_acoustic_echo_cancelation"`
	// ReferencesAcousticEchoCancelation         interface{} `json:"references_acoustic_echo_cancelation"`
	// TailLengthAcousticEchoCancelation         string      `json:"tail_length_acoustic_echo_cancelation"`
	// AdjustmentRangeAudioInputsAnalog          string      `json:"adjustment_range_audio_inputs_analog"`
	// ChannelsAudioInputsAnalog                 interface{} `json:"channels_audio_inputs_analog"`
	// ConnectorsAudioInputsAnalog               string      `json:"connectors_audio_inputs_analog"`
	// EquivalentInputNoiseAudioInputsAnalog     string      `json:"equivalent_input_noise_audio_inputs_analog"`
	// GainSettingsAudioInputsAnalog             string      `json:"gain_settings_audio_inputs_analog"`
	// InputImpedanceAudioInputsAnalog           string      `json:"input_impedance_audio_inputs_analog"`
	// InputRangeAudioInputsAnalog               string      `json:"input_range_audio_inputs_analog"`
	// MaximumInputLevelAudioInputsAnalog        string      `json:"maximum_input_level_audio_inputs_analog"`
	// NominalInputLevelAudioInputsAnalog        string      `json:"nominal_input_level_audio_inputs_analog"`
	// PhantomPowerAudioInputsAnalog             string      `json:"phantom_power_audio_inputs_analog"`
	// SensitivityAudioInputsAnalog              string      `json:"sensitivity_audio_inputs_analog"`
	// ChannelsAudioInputsOutputsDigital         string      `json:"channels_audio_inputsoutputs_digital"`
	// ConnectorsAudioInputsOutputsDigital       string      `json:"connectors_audio_inputsoutputs_digital"`
	// TypeAudioInputsOutputsDigital             string      `json:"type_audio_inputsoutputs_digital"`
	// AdjustmentRangeAudioOutputsAnalog         string      `json:"adjustment_range_audio_outputs_analog"`
	// ChannelsAudioOutputsAnalog                interface{} `json:"channels_audio_outputs_analog"`
	// ConnectorsAudioOutputsAnalog              string      `json:"connectors_audio_outputs_analog"`
	// MaximumOutputLevelAudioOutputsAnalog      string      `json:"maximum_output_level_audio_outputs_analog"`
	// NominalOutputLevelAudioOutputsAnalog      string      `json:"nominal_output_level_audio_outputs_analog"`
	// OutputImpedanceAudioOutputsAnalog         string      `json:"output_impedance_audio_outputs_analog"`
	// EnvironmentalCompliance                   string      `json:"environmental_compliance"`
	// EMCCompliance                             string      `json:"emc_compliance"`
	// EN5424CertifiedCompliance                 string      `json:"en_5424_certified_compliance"`
	// SafetyCompliance                          string      `json:"safety_compliance"`
	// SafetyAgencyRatingsCompliance             string      `json:"safety_agency_ratings_compliance"`
	// TelecommunicationCompliance               string      `json:"telecommunication_compliance"`
	// FocusDistanceCameraAndVideo               string      `json:"focus_distance_camera_and_video"`
	// FieldOfViewCameraAndVideo                 string      `json:"field_of_view_camera_and_video"`
	// ImageSensorCameraAndVideo                 string      `json:"image_sensor_camera_and_video"`
	// LensCameraAndVideo                        string      `json:"lens_camera_and_video"`
	// PositioningCameraAndVideo                 string      `json:"positioning_camera_and_video"`
	// ProcessingCameraAndVideo                  string      `json:"processing_camera_and_video"`
	// SupportedVideoResolutionsCameraAndVideo   string      `json:"supported_video_resolutions_camera_and_video"`
	// USBDeviceVideoClassCameraAndVideo         string      `json:"usb_device_video_class_camera_and_video"`
	// VideoEncodingCameraAndVideo               string      `json:"video_encoding_camera_and_video"`
	// ControlInputsControlInputs                string      `json:"control_inputs_control_inputs"`
	// VoltageRangeAnalogControlInputs           string      `json:"voltage_range_analog_control_inputs"`
	// VoltageRangeDigitalControlInputs          string      `json:"voltage_range_digital_control_inputs"`
	// ControlOutputsControlOutputs              interface{} `json:"control_outputs_control_outputs"`
	// OutputCurrentControlOutputs               string      `json:"output_current_control_outputs"`
	// OutputVoltageControlOutputs               string      `json:"output_voltage_control_outputs"`
	// Colour                                    string      `json:"colour"`
	// BluetoothCommunicationPorts               string      `json:"bluetooth_communication_ports"`
	// NetworkCommunicationPorts                 string      `json:"network_communication_ports"`
	// PSTNCommunicationPorts                    string      `json:"pstn_communication_ports"`
	// USBCommunicationPorts                     string      `json:"usb_communication_ports"`
	// VOIPCommunicationPorts                    string      `json:"voip_communication_ports"`
	// ACPowerConnectorElectrical                string      `json:"ac_power_connector_electrical"`
	// ACPowerInputElectrical                    string      `json:"ac_power_input_electrical"`
	// CurrentDrawContinuousElectrical           string      `json:"current_draw_continuous_electrical"`
	// ConnectorsElectrical                      string      `json:"connectors_electrical"`
	// CableRequirementsElectrical               string      `json:"cable_requirements_electrical"`
	// CurrentDrawIdleElectrical                 string      `json:"current_draw_idle_electrical"`
	// CurrentDrawInrushElectrical               string      `json:"current_draw_inrush_electrical"`
	// LEDPowerUsageElectrical                   string      `json:"led_power_usage_electrical"`
	// MainsConnectorElectrical                  string      `json:"mains_connector_electrical"`
	// MaximumCableLengthElectrical              string      `json:"maximum_cable_length_electrical"`
	// MaximumControllerQuantityElectrical       string      `json:"maximum_controller_quantity_electrical"`
	// MainsVoltageElectrical                    string      `json:"mains_voltage_electrical"`
	// ProtectionsElectrical                     string      `json:"protections_electrical"`
	// PoEClassElectrical                        string      `json:"poe_class_electrical"`
	// PowerConsumptionElectrical                string      `json:"power_consumption_electrical"`
	// PowerDissipationElectrical                string      `json:"power_dissipation_electrical"`
	// PowerRangeElectrical                      string      `json:"power_range_electrical"`
	// ComputerInterfaceConnectionGeneral        string      `json:"computer_interface_connection_general"`
	// CompatibleWithGeneral                     string      `json:"compatible_with_general"`
	// NotificationOutputsGeneral                string      `json:"notification_outputs_general"`
	// SoftwareApplicationsGeneral               string      `json:"software_applications_general"`
	// SystemRequirementsGeneral                 string      `json:"system_requirements_general"`
	// WorkingLoadLimitGeneral                   string      `json:"working_load_limit_general"`
	// ControlsFrontPanelIndicatorsAndControls   string      `json:"controls_front_panel_indicators_and_controls"`
	// ControlsRearPanelIndicatorsAndControls    string      `json:"controls_rear_panel_indicators_and_controls"`
	// DisplayIndicatorsAndControls              string      `json:"display_indicators_and_controls"`
	// LEDStatusIndicatorsIndicatorsAndControls  string      `json:"led_status_indicators_indicators_and_controls"`
	// ADAndDAConversionIntegratedDSP            string      `json:"ad_and_da_conversion_integrated_dsp"`
	// AudioLatencyIntegratedDSP                 string      `json:"audio_latency_integrated_dsp"`
	// CrossoverTypesIntegratedDSP               string      `json:"crossover_types_integrated_dsp"`
	// DelayIntegratedDSP                        string      `json:"delay_integrated_dsp"`
	// DSPEnabledIntegratedDSP                   string      `json:"dspenabled_integrated_dsp"`
	// EqualizationIntegratedDSP                 string      `json:"equalization_integrated_dsp"`
	// InternalPrecisionIntegratedDSP            string      `json:"internal_precision_integrated_dsp"`
	// LimitersIntegratedDSP                     string      `json:"limiters_integrated_dsp"`
	// MaximumCalculationIntegratedDSP           string      `json:"maximum_calculation_integrated_dsp"`
	// PresetsIntegratedDSP                      string      `json:"presets_integrated_dsp"`
	// ProcessingFunctionsIntegratedDSP          string      `json:"processing_functions_integrated_dsp"`
	// SignalProcessorCPUIntegratedDSP           string      `json:"signal_processorcpu_integrated_dsp"`
	// SampleRateBitDepthIntegratedDSP           string      `json:"sample_rate_bit_depth_integrated_dsp"`
	// PackageContentsIncludedInPackaging        string      `json:"package_contents_included_in_packaging"`
	// PickupRangeMicrophone                     string      `json:"pickup_range_microphone"`
	// TechnologyMicrophone                      string      `json:"technology_microphone"`
	ColorsPhysical []string `json:"colors_physical"`
	// CutoutDiameterPhysical                    string      `json:"cutout_diameter_physical"`
	// CoolingSystemPhysical                     string      `json:"cooling_system_physical"`
	// EnclosureMaterialPhysical                 string      `json:"enclosure_material_physical"`
	// EnvironmentalTestingPhysical              string      `json:"environmental_testing_physical"`
	// FrequencyRangePerformance                 string      `json:"frequency_range_performance"`
	// FrequencyResponsePerformance              string      `json:"frequency_response_performance"`
	// GrilleMaterialPhysical                    string      `json:"grille_material_physical"`
	// CoverageHorizontalPerformance             string      `json:"coverage_horizontal_performance"`
	// IngressProtectionPhysical                 string      `json:"ingress_protection_physical"`
	// LogoPhysical                              string      `json:"logo_physical"`
	// MountingRiggingProvisionsPhysical         string      `json:"mountingrigging_provisions_physical"`
	// MaximumSPLAt1MPerformance                 string      `json:"maximum_spl_at_1_m_performance"`
	// NominalImpedancePerformance               string      `json:"nominal_impedance_performance"`
	// NetWeightPhysical                         string      `json:"net_weight_physical"`
	// OperationModePerformance                  string      `json:"operation_mode_performance"`
	// OperatingRangePerformance                 string      `json:"operating_range_performance"`
	// OperatingTemperaturePhysical              string      `json:"operating_temperature_physical"`
	// ProductDimensionsPhysical                 string      `json:"product_dimensions_physical"`
	// PowerHandlingContinuousPerformance        string      `json:"power_handling_continuous_performance"`
	// PowerHandlingPeakPerformance              string      `json:"power_handling_peak_performance"`
	// RecommendedPowerAmplificationPerformance  string      `json:"recommended_power_amplification_performance"`
	// RackSpacesPhysical                        interface{} `json:"rack_spaces_physical"`
	// RecommendedSignalProcessingPerformance    string      `json:"recommended_signal_processing_performance"`
	// SensitivityPerformance                    string      `json:"sensitivity_performance"`
	// ShippingDimensionsPhysical                string      `json:"shipping_dimensions_physical"`
	// SafetyFeaturesPhysical                    string      `json:"safety_features_physical"`
	// StorageTemperaturePhysical                string      `json:"storage_temperature_physical"`
	// ShippingWeightPhysical                    string      `json:"shipping_weight_physical"`
	// TransformerTaps100VPerformance            string      `json:"transformer_taps_100v_performance"`
	// TransformerTaps70VPerformance             string      `json:"transformer_taps_70v_performance"`
	// CoverageVerticalPerformance               string      `json:"coverage_vertical_performance"`
	// ZPerformance                              string      `json:"z_performance"`
	// OptionalAccessoriesRequiredAndOptional    string      `json:"optional_accessories_required_and_optional_accessories"`
	// RequiredAccessoriesRequiredAndOptional    string      `json:"required_accessories_required_and_optional_accessories"`
	// CrossoverFrequencyTransducers             string      `json:"crossover_frequency_transducers"`
	// DriverProtectionTransducers               string      `json:"driver_protection_transducers"`
	// HighFrequencyTransducerQuantityAndSize    string      `json:"highfrequency_transducer_quantity_and_size_transducers"`
	// LowFrequencyTransducerQuantityAndSize     string      `json:"lowfrequency_transducer_quantity_and_size_transducers"`
	// MidFrequencyTransducerQuantityAndSize     string      `json:"midfrequency_transducer_quantity_and_size_transducers"`
	// WarrantyPeriodWarranty                    string      `json:"warranty_period_warranty"`

	// Add this dynamic key manually in code, not in JSON tags
	CustomName string `json:"custom_name,omitempty"`
}
