info:
  name: Clear TouchUI Zone Config
  type: http
  seq: 9

http:
  method: DELETE
  url: "{{api_url}}/settings/touchui_zone_config"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
