info:
  name: Get TouchUI Zone Config
  type: http
  seq: 7

http:
  method: GET
  url: "{{api_url}}/settings/touchui_zone_config"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
