info:
  name: Patch Wall Controller Config
  type: http
  seq: 11

http:
  method: PATCH
  url: "{{api_url}}/settings/wall_controller_config"
  body:
    type: json
    data: |-
      {
        "value": {
          "zones": [
            {
              "id": "FUNC546470292/selector",
              "gain": {
                "default_gain_value": "0",
                "default_mute_value": "0",
                "gainID": "GAIN528578446",
                "max_value": "12",
                "min_value": "-60"
              }
            }
          ]
        }
      }

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
