name: "Build Flutter Web App"
description: "Build Flutter Web App"
inputs:
  flutter_apps_sonar_token:
    description: 'SonarQube server token'
    required: true
  nexus_password:
    description: 'Nexus repository password'
    required: true
  keychain_password:
    description: 'Keychain password for iOS build'
    required: true
  nexus_url:
    description: 'Nexus repository URL'
    required: true
        
runs:
  using: "composite"
  steps:
    - name: Read package version
      id: get_version
      shell: bash
      run: |
        VERSION=$(grep '^version:' apps/frontend/flutter-apps/fusion-launcher/pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
        echo "Found version: $VERSION"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"


    # - name: SonarQube Scan
    #   uses: SonarSource/sonarqube-scan-action@v5
    #   env:
    #     SONAR_TOKEN: ${{ inputs.flutter_apps_sonar_token }}
    #   with:
    #     projectBaseDir: 'apps/frontend/flutter-apps'
    #     args: >
    #       -Dsonar.c.file.suffixes=-
    #       -Dsonar.cpp.file.suffixes=-
    #       -Dsonar.objc.file.suffixes=-
    #       -Dsonar.exclusions=build/**
    #       -Dsonar.inclusions=lib/**,android/**,ios/**

    # - name: Flutter Web App build
    #   shell: bash
    #   working-directory: apps/frontend/flutter-apps/fusion-launcher
    #   run: |
    #     echo "$HOME/.proto/shims" >> $GITHUB_PATH
    #     flutter pub get
    #     moon run flutter-apps:build-web
    #     cd build/web
    #     zip -r fusion_launcher_web_build.zip .
    #     VERSION="${{ steps.get_version.outputs.version }}-${GITHUB_RUN_NUMBER}+$(git rev-parse --short=8 HEAD)"
    #     curl -k --ssl-no-revoke -f -u github-actions-uploader:${{ inputs.nexus_password }} -T fusion_launcher_web_build.zip ${{ inputs.nexus_url }}/Fusion-Frontend/Continuous/${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}/$VERSION/flutter-web/Fusion-Launcher-$VERSION.zip
    #     echo "Web Build uploaded to Nexus successfully!"
    #     echo "flutter-web: ${{ inputs.nexus_url }}/Fusion-Frontend/Continuous/${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}/$VERSION/flutter-web/Fusion-Launcher-$VERSION.zip"
