class SampleData {
  static Map<String, dynamic> get sampleData => <String, dynamic>{
    "width": 100,
    "height": 100,
    "children": <Map<String, Object>>[
      <String, Object>{
        "id": "368708",
        "x": 205.39,
        "y": 0.64,
        "width": 19.65,
        "height": 5.04,
        "field": "",
        "type": "text",
        "param": <String, String>{"label": "OUTPUT"},
      },
      <String, Object>{
        "id": "489516",
        "x": 164.41,
        "y": 0.0,
        "width": 20,
        "height": 5,
        "field": "",
        "type": "indicator",
        "param": <String, String>{"label": "Open"},
      },
      <String, Object>{
        "id": "784848",
        "x": 0.0,
        "y": 54.0,
        "width": 25.0,
        "height": 45.0,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "ATTACK", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "490063",
        "x": 25.0,
        "y": 55.47,
        "width": 25.0,
        "height": 45.0,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "HOLD", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "766574",
        "x": 50.0,
        "y": 54.95,
        "width": 25.0,
        "height": 45.0,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "DECAY", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "860530",
        "x": 0.0,
        "y": 10.0,
        "width": 25.0,
        "height": 40.0,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "THRESHOLD", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "122421",
        "x": 25.0,
        "y": 10.0,
        "width": 25.0,
        "height": 40.0,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "RANGE", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "388726",
        "x": 2.74,
        "y": 0.4,
        "width": 30.42,
        "height": 8.37,
        "field": "",
        "type": "switch",
        "param": <String, String>{"label": "Detector", "enable_value_label": "Yes", "disabled_value_label": "No"},
      },
      <String, Object>{
        "id": "305678",
        "x": 76.99,
        "y": 9.39,
        "width": 107.42,
        "height": 89.72,
        "field": "",
        "type": "graph",
        "param": <String, String>{"label": "Graph goes here"},
      },
      <String, Object>{
        "id": "676584",
        "x": 201.48,
        "y": -0.85,
        "width": 15.34,
        "height": 100.45,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "390872",
        "x": 208.29,
        "y": 10.81,
        "width": 19.12,
        "height": 78.97,
        "field": "",
        "type": "meter",
        "param": <String, Object>{"label": "", "min": 0, "max": 100},
      },
    ],
  };
}
