class SampleData {
  static Map<String, dynamic> get sampleData => <String, dynamic>{
    "width": 100,
    "height": 100,
    "children": <Map<String, Object>>[
      <String, Object>{
        "id": "751552",
        "x": 2.0,
        "y": 1.0,
        "width": 20,
        "height": 5,
        "field": "",
        "type": "switch",
        "param": <String, String>{"label": "DETECTOR", "enable_value_label": "TRUE", "disabled_value_label": "FALSE"},
      },
      <String, Object>{
        "id": "353449",
        "x": 2.0,
        "y": 7.0,
        "width": 10,
        "height": 25,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "Slider", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "497462",
        "x": 2.0,
        "y": 35.0,
        "width": 10,
        "height": 25,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "Slider", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "453989",
        "x": 12.0,
        "y": 35.0,
        "width": 10,
        "height": 25,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "Slider", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "672836",
        "x": 99.67447916666666,
        "y": 22.86820023148148,
        "width": 20,
        "height": 5,
        "field": "",
        "type": "indicator",
        "param": <String, String>{"label": "Indicator"},
      },
      <String, Object>{
        "id": "361293",
        "x": 83.01,
        "y": 7.21,
        "width": 7.03,
        "height": 52.04,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "Slider", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "406940",
        "x": 89.88,
        "y": 7.16,
        "width": 9.12,
        "height": 51.53,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "Slider", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "44406",
        "x": 30.45,
        "y": 6.74,
        "width": 51.83,
        "height": 52.55,
        "field": "",
        "type": "graph",
        "param": <String, String>{"label": "Graph goes here"},
      },
      <String, Object>{
        "id": "632654",
        "x": 70.0,
        "y": 2.0,
        "width": 9.83,
        "height": 4.21,
        "field": "",
        "type": "indicator",
        "param": <String, String>{"label": "Indicator"},
      },
      <String, Object>{
        "id": "400964",
        "x": 12.0,
        "y": 7.0,
        "width": 6.98,
        "height": 24.03,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "Slider", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "125356",
        "x": 20.39,
        "y": 7.07,
        "width": 10,
        "height": 25,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "Slider", "min": 0, "max": 100},
      },
      <String, Object>{
        "id": "244718",
        "x": 20.31,
        "y": 35.02,
        "width": 10,
        "height": 25,
        "field": "",
        "type": "slider",
        "param": <String, Object>{"label": "Slider", "min": 0, "max": 100},
      },
    ],
  };
}
