name: "Setup Toolchain"
description: "Setup the Monorepo build toolchain"

runs:
  using: "composite"
  steps:
    # Set up Proto Tool
    - name: Set up Moon & Proto tools
      uses: moonrepo/setup-toolchain@v0
      with:
        version: '0.51.4'
        moon-version: '1.41.8'

    # # Install Moon via Proto
    # - name: Install moon
    #   shell: bash
    #   run: proto install moon

    # Install Toolchain
    - name: Run proto install
      shell: bash
      run: proto install

    - name: Add custom tool to path
      shell: bash
      run: |
        echo "$HOME/.proto/shims" >> $GITHUB_PATH
        echo "$HOME/.proto/bin" >> $GITHUB_PATH
        echo "$HOME/.moon/bin" >> $GITHUB_PATH

    # Flutter pub cache
    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-      
