#!/usr/bin/env python3

import os
import re
import subprocess
from pathlib import Path

# Define the output directory
OUTPUT_DIR = "lib/core/assets"

def to_camel_case(input_str):
    """Convert snake_case, kebab-case, or space-separated to camelCase (first word lowercase)"""
    # Remove file extension if present
    input_str = Path(input_str).stem
    
    # Replace hyphens and spaces with underscores for uniform processing
    input_str = input_str.replace('-', '_').replace(' ', '_')
    
    # Split by underscore
    parts = input_str.split('_')
    if not parts:
        return input_str
    
    # Filter out empty parts
    parts = [part for part in parts if part]
    
    if not parts:
        return input_str
    
    # First word stays lowercase, capitalize rest
    result = parts[0].lower()
    for part in parts[1:]:
        if part:
            result += part.capitalize()
    
    return result

def to_pascal_case(input_str):
    """Convert snake_case, kebab-case, or space-separated to PascalCase (for class names)"""
    # Replace hyphens and spaces with underscores for uniform processing
    input_str = input_str.replace('-', '_').replace(' ', '_')
    
    parts = input_str.split('_')
    result = ''.join(part.capitalize() for part in parts if part)
    return result

def sanitize_variable_name(name):
    """Sanitize variable name to be a valid Dart identifier"""
    # Remove any characters that aren't alphanumeric or underscore
    name = re.sub(r'[^\w]', '', name)
    
    # Ensure it doesn't start with a number
    if name and name[0].isdigit():
        name = '_' + name
    
    return name

def has_files(folder_path):
    """Check if folder has files"""
    try:
        files = list(Path(folder_path).glob('*'))
        return any(f.is_file() for f in files)
    except Exception:
        return False

def generate_asset_file(folder_name):
    """Generate asset file for a specific folder"""
    folder_path = Path(f"assets/{folder_name}")
    output_file = Path(OUTPUT_DIR) / f"asset_{folder_name}.dart"
    capitalized_name = to_pascal_case(folder_name)
    
    # Check if folder exists
    if not folder_path.exists():
        print(f"Warning: Folder '{folder_path}' does not exist. Skipping...")
        return
    
    # Check if folder has files
    if not has_files(folder_path):
        print(f"Warning: No files found in '{folder_path}'. Creating empty class...")
    
    # Start writing to the output file
    lines = [
        "// GENERATED CODE - DO NOT MODIFY BY HAND",
        "// This file was generated by assets_generator.py",
        "",
        f"class Asset{capitalized_name} {{",
        f"  static const String _path = 'assets/{folder_name}';",
    ]
    
    # Process files if they exist
    try:
        files = sorted([f for f in folder_path.iterdir() if f.is_file()])
        
        if files:
            lines.append(f"  // {capitalized_name} Files")
            for file in files:
                filename_with_ext = file.name
                var_name = to_camel_case(file.stem)
                var_name = sanitize_variable_name(var_name)
                
                # Skip if variable name is empty after sanitization
                if not var_name:
                    print(f"Warning: Could not generate valid variable name for '{filename_with_ext}'. Skipping...")
                    continue
                
                lines.append(f"  static const String {var_name} = '$_path/{filename_with_ext}';")
        else:
            lines.append(f"  // No {capitalized_name} files found")
    except Exception as e:
        print(f"Error processing files in {folder_path}: {e}")
        lines.append(f"  // No {capitalized_name} files found")
    
    # Add closing brace
    lines.append("}")
    
    # Write to file
    output_file.write_text('\n'.join(lines) + '\n')
    
    # Format the generated file
    # try:
    #     result = subprocess.run(['dart', 'format', str(output_file)], 
    #                   capture_output=True, 
    #                   check=False,
    #                   text=True)
    #     if result.returncode != 0 and result.stderr:
    #         print(f"Warning: dart format had issues with {output_file}: {result.stderr}")
    # except FileNotFoundError:
    #     print(f"Warning: 'dart' command not found. Skipping formatting for {output_file}")
    # except Exception as e:
    #     print(f"Warning: Could not format {output_file}: {e}")
    
    print(f"Generated {output_file}")

def main():
    """Main script"""
    print("Starting asset generation...")
    
    assets_dir = Path("assets")
    
    if not assets_dir.exists():
        print("Error: 'assets' directory not found!")
        return 1
    
    # Create output directory if it doesn't exist
    Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
    
    # Process each folder in assets
    for folder in assets_dir.iterdir():
        if folder.is_dir():
            folder_name = folder.name
            generate_asset_file(folder_name)
    
    print("Asset generation completed successfully!")
    return 0

if __name__ == "__main__":
    exit(main())