#!/usr/bin/env python3

import os
import re
from pathlib import Path

OUTPUT_DIR = "lib/core/assets"


def to_camel_case(input_str):
    input_str = Path(input_str).stem
    input_str = input_str.replace('-', '_').replace(' ', '_')

    parts = [p for p in input_str.split('_') if p]

    if not parts:
        return input_str

    result = parts[0].lower()
    for part in parts[1:]:
        result += part.capitalize()

    return result


def to_pascal_case(input_str):
    input_str = input_str.replace('-', '_').replace(' ', '_')
    parts = input_str.split('_')
    return ''.join(part.capitalize() for part in parts if part)


def sanitize_variable_name(name):
    name = re.sub(r'[^\w]', '', name)

    if name and name[0].isdigit():
        name = '_' + name

    return name


def has_files(folder_path):
    return any(f.is_file() for f in folder_path.rglob("*"))


def generate_asset_file(folder_name):
    folder_path = Path(f"assets/{folder_name}")
    output_file = Path(OUTPUT_DIR) / f"asset_{folder_name}.dart"
    capitalized_name = to_pascal_case(folder_name)

    if not folder_path.exists():
        print(f"Warning: Folder '{folder_path}' does not exist. Skipping...")
        return

    if not has_files(folder_path):
        print(f"Warning: No files found in '{folder_path}'. Creating empty class...")

    lines = [
        "// GENERATED CODE - DO NOT MODIFY BY HAND",
        "// This file was generated by assets_generator.py",
        "",
        f"class Asset{capitalized_name} {{",
        f"  static const String _path = 'assets/{folder_name}';",
    ]

    try:
        # recursively collect files
        files = sorted([f for f in folder_path.rglob("*") if f.is_file()])

        if files:
            lines.append(f"  // {capitalized_name} Files")

            for file in files:

                # relative path inside main folder
                relative_path = file.relative_to(folder_path)

                filename = relative_path.name
                folder_prefix = relative_path.parent

                var_name = to_camel_case(file.stem)
                var_name = sanitize_variable_name(var_name)

                if not var_name:
                    continue

                if str(folder_prefix) == ".":
                    asset_path = f"$_path/{filename}"
                else:
                    asset_path = f"$_path/{folder_prefix}/{filename}"

                lines.append(
                    f"  static const String {var_name} = '{asset_path}';"
                )

        else:
            lines.append(f"  // No {capitalized_name} files found")

    except Exception as e:
        print(f"Error processing files in {folder_path}: {e}")
        lines.append(f"  // No {capitalized_name} files found")

    lines.append("}")

    output_file.write_text('\n'.join(lines) + '\n')

    print(f"Generated {output_file}")


def main():
    print("Starting asset generation...")

    assets_dir = Path("assets")

    if not assets_dir.exists():
        print("Error: 'assets' directory not found!")
        return 1

    Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

    for folder in assets_dir.iterdir():
        if folder.is_dir():
            generate_asset_file(folder.name)

    print("Asset generation completed successfully!")
    return 0


if __name__ == "__main__":
    exit(main())