import 'package:fusion_lib/constants/fusion_constants.dart';

extension ControllerKeys on FusionTestKeys {
  String get controlPanel => "control_panel";

  // ------------- Sidebar --------------
  String get controlPanelSidebar => "control_panel_sidebar";
  String get controlPanelSidebarHeader => "control_panel_sidebar_header";
  String get controlPanelSidebarHeaderText => "control_panel_sidebar_header_text";
  String get controlPanelSidebarHeaderIcon => "control_panel_sidebar_header_add_controller_icon";
  String get controlPanelSidebarEmptyList => "control_panel_sidebar_empty_list";
  String get controlPanelSidebarEmptyListText => "control_panel_sidebar_empty_list_text";
  String get controlPanelSidebarList => "control_panel_sidebar_list";
  String get controlPanelSidebarListItem => "control_panel_sidebar_list_item";
  String get controlPanelSidebarListItemControllerName => "control_panel_sidebar_list_item_controller_name";
  String get controlPanelSidebarListItemControllerSku => "control_panel_sidebar_list_item_controller_sku";
  String get controlPanelSidebarListItemControllerLocation => "control_panel_sidebar_list_item_controller_location";
  String get controlPanelSidebarListItemControllerLocationBox => "control_panel_sidebar_list_item_controller_location_box";
  String get controlPanelSidebarListItemControllerLocationText => "control_panel_sidebar_list_item_controller_location_text";
  String get controlPanelSidebarListItemControllerLocationIcon => "control_panel_sidebar_list_item_controller_location_icon";
  String get controlPanelSidebarListItemControllerKebakPopup => "control_panel_sidebar_list_item_controller_kebab_popup";

  // ------------- Content Panel --------------
  String get controlPanelContentTabBar => "control_panel_content_tab_bar";
  String get controlPanelContentTabBarItem => "control_panel_content_tab_bar_item";
  String get controlPanelContentTabItemText => "control_panel_content_tab_item_text";

  // ------------ Zone Control Tab --------------
  String get zoneControlTab => "zone_control_tab";
  String get zoneControlTabZoneSection => "zone_control_tab_zone_section";
  String get zoneControlTabZoneSectionHeader => "zone_control_tab_zone_section_header";
  String get zoneControlTabZoneSectionList => "zone_control_tab_zone_section_list";
  String get zoneControlTabZoneSectionListEmpty => "zone_control_tab_zone_list_empty";
  String get zoneControlTabZoneSectionListEmptyText => "zone_control_tab_zone_list_empty_text";
  String get zoneControlTabZoneSectionListItem => "zone_control_tab_zone_section_item";
  String get zoneControlTabZoneSectionListItemZone => "zone_control_tab_zone_section_item_zone";
  String get zoneControlTabZoneSectionListItemZoneBox => "zone_control_tab_zone_section_item_zone_box";
  String get zoneControlTabZoneSectionListItemZoneName => "zone_control_tab_zone_section_item_zone_name";
  String get zoneControlTabZoneSectionListItemZoneCheckBox => "zone_control_tab_zone_section_item_zone_checkbox";
  String get zoneControlTabZoneSectionListItemZoneSetting => "zone_control_tab_zone_section_item_zone_settings";
  String get zoneControlTabZoneSectionListItemSubZone => "zone_control_tab_zone_section_item_sub_zone";
  String get zoneControlTabZoneSectionListItemSubZoneArrow => "zone_control_tab_zone_section_item_sub_zone_arrow";
  String get zoneControlTabZoneSectionListItemSubZoneName => "zone_control_tab_zone_section_item_sub_zone_name";
  String get zoneControlTabZoneSectionListItemSubZoneCheckbox => "zone_control_tab_zone_section_item_sub_zone_checkbox";
  String get zoneControlTabZoneSectionListItemSubZoneSetting => "zone_control_tab_zone_section_item_sub_zone_setting";

  String get zoneControlTabVirtualController => "zone_control_tab_virtual_controller";
  String get zoneControlTabVirtualControllerHeader => "zone_control_tab_virtual_controller_header";
  String get zoneControlTabVirtualControllerContent => "zone_control_tab_virtual_controller_content";
  String get zoneControlTabVirtualControllerEmptyContent => "zone_control_tab_virtual_controller_empty_content";
  String get zoneControlTabVirtualControllerEmptyContentText => "zone_control_tab_virtual_controller_empty_content_text";
  String get zoneControlTabVirtualControllerContentHeader => "zone_control_tab_virtual_controller_content_header";
  String get zoneControlTabVirtualControllerContentDropdown => "zone_control_tab_virtual_controller_content_dropdown";
  String get zoneControlTabVirtualControllerContentVolumeDial => "zone_control_tab_virtual_controller_content_volume_dial";
  String get zoneControlTabVirtualControllerContentVolumeSlider => "zone_control_tab_virtual_controller_content_volume_slider";
  String get zoneControlTabVirtualControllerContentMuteButton => "zone_control_tab_virtual_controller_content_mute_button";

  // ------------ Snapshot/Scenes Tab --------------
  String get snapshotAndScenesTab => "snapshots_and_scenes_tab";
  String get snapshotAndScenesSection => "snapshots_and_scenes_section";
  String get scenesSection => "scenes_section";
  String get scenesSectionHeader => "scenes_section_header";
  String get scenesSectionEmptyList => "scenes_section_empty_content";
  String get scenesSectionEmptyListText => "scenes_section_empty_content_text";
  String get scenesSectionList => "scenes_section_list";
  String get scenesSectionListItem => "scenes_section_list_item";
  String get scenesSectionListItemCheckbox => "scenes_section_list_item_checkbox";
  String get scenesSectionListItemName => "scenes_section_list_item_name";
  String get snapshotSection => "snapshot_section";
  String get snapshotSectionHeader => "snapshot_section_header";
  String get snapshotSectionHeaderIcon => "snapshot_section_header_add_snapshot_icon";
  String get snapshotSectionEmptyList => "snapshot_section_empty_content";
  String get snapshotSectionEmptyListText => "snapshot_section_empty_content_text";
  String get snapshotSectionList => "snapshot_section_list";
  String get snapshotSectionListItem => "snapshot_section_list_item";
  String get snapshotSectionListItemText => "snapshot_section_list_item_text";
  String get snapshotSectionListItemKebabPopup => "snapshot_section_list_item_kebab_popup";

  String get snapshotAndScenesPagesSection => "snapshots_and_scenes_pages_section";
  String get snapshotAndScenesPagesSectionHeader => "snapshots_and_scenes_pages_section_header";
  String get snapshotAndScenesPagesSectionEmptyList => "snapshots_and_scenes_pages_section_empty_list";
  String get snapshotAndScenesPagesSectionEmptyListText => "snapshots_and_scenes_pages_section_empty_list_text";
  String get snapshotAndScenesPagesSectionList => "snapshots_and_scenes_pages_section_list";
  String get snapshotAndScenesPagesSectionListScenesItem => "snapshots_and_scenes_pages_section_list_scenes_item";
  String get snapshotAndScenesPagesSectionListSnapshotItem => "snapshots_and_scenes_pages_section_list_snapshot_item";
  String get snapshotAndScenesPagesSectionListItemIcon => "snapshots_and_scenes_pages_section_list_item_icon";
  String get snapshotAndScenesPagesSectionListItemName => "snapshots_and_scenes_pages_section_list_item_name";

  String get snapshotAndScenesTabVirtualController => "zone_control_tab_virtual_controller";
  String get snapshotAndScenesTabVirtualControllerHeader => "zone_control_tab_virtual_controller_header";
  String get snapshotAndScenesTabVirtualControllerContent => "zone_control_tab_virtual_controller_content";
  String get snapshotAndScenesTabVirtualControllerEmptyContent => "zone_control_tab_virtual_controller_empty_content";
  String get snapshotAndScenesTabVirtualControllerEmptyContentHeader => "zone_control_tab_virtual_controller_empty_content_header";
  String get snapshotAndScenesTabVirtualControllerEmptyContentText => "zone_control_tab_virtual_controller_empty_content_text";
  String get snapshotAndScenesTabVirtualControllerContentHeader => "zone_control_tab_virtual_controller_content_header";
  String get snapshotAndScenesTabVirtualControllerContentList => "zone_control_tab_virtual_controller_content_list";
  String get snapshotAndScenesTabVirtualControllerContentListItem => "zone_control_tab_virtual_controller_content_list_item";
  String get snapshotAndScenesTabVirtualControllerContentListItemText => "zone_control_tab_virtual_controller_content_list_item_text";
  String get snapshotAndScenesTabVirtualControllerContentListItemLabel => "zone_control_tab_virtual_controller_content_list_item_text_label";
  String get snapshotAndScenesTabVirtualControllerContentListItemCheckBox => "zone_control_tab_virtual_controller_content_list_item_text_checkbox";

  // ------------ Schedule Tab --------------
  String get scheduleTab => "schedule_tab";
  String get scheduleTabScheduledItems => "schedule_tab_scheduled_items";
  String get scheduleTabScheduledItemsHeader => "schedule_tab_scheduled_items_header";
  String get scheduleTabScheduledItemsContent => "schedule_tab_scheduled_items_content";
  String get scheduleTabScheduledItemsContentUpcomingSection => "schedule_tab_scheduled_items_upcoming_section";
  String get scheduleTabScheduledItemsContentUpcomingSectionCheckbox => "schedule_tab_scheduled_items_upcoming_section_checkbox";
  String get scheduleTabScheduledItemsContentUpcomingSectionText => "schedule_tab_scheduled_items_upcoming_section_text";
  String get scheduleTabScheduledItemsContentShowNoneSection => "schedule_tab_scheduled_items_content_show_none_section";
  String get scheduleTabScheduledItemsContentShowNoneSectionCheckbox => "schedule_tab_scheduled_items_content_show_none_section_checkbox";
  String get scheduleTabScheduledItemsContentShowNoneSectionText => "schedule_tab_scheduled_items_content_show_none_section_text";
  String get scheduleTabScheduledItemsContentShowAllSection => "schedule_tab_scheduled_items_content_show_all_section";
  String get scheduleTabScheduledItemsContentShowAllSectionCheckbox => "schedule_tab_scheduled_items_content_show_all_section_checkbox";
  String get scheduleTabScheduledItemsContentShowAllSectionText => "schedule_tab_scheduled_items_content_show_all_section";
  String get scheduleTabScheduledItemsContentShowSelectedSection => "schedule_tab_scheduled_items_content_show_selected_section";
  String get scheduleTabScheduledItemsContentShowSelectedSectionCheckbox => "schedule_tab_scheduled_items_content_show_selected_section_checkbox";
  String get scheduleTabScheduledItemsContentShowSelectedSectionText => "schedule_tab_scheduled_items_content_show_selected_section_text";

  String get scheduleTabScheduleVc => "schedule_tab_schedule_vc";
  String get scheduleTabScheduleVcHeader => "schedule_tab_schedule_vc";
  String get scheduleTabScheduleVcTab => "schedule_tab_schedule_vc_tab";
  String get scheduleTabScheduleVcTabScheduled => "schedule_tab_schedule_vc_tab_scheduled";
  String get scheduleTabScheduleVcTabUpcomming => "schedule_tab_schedule_vc_tab_upcoming";
  String get scheduleTabScheduleVcTabList => "schedule_tab_schedule_vc_tab_list";
  String get scheduleTabScheduleVcTabEmptyList => "schedule_tab_schedule_vc_tab_empty_list";
  String get scheduleTabScheduleVcTabEmptyListText => "schedule_tab_schedule_vc_tab_empty_list_text";
  String get scheduleTabScheduleVcItem => "schedule_tab_schedule_vc_item";
  String get scheduleTabScheduleVcItemLeftStrip => "schedule_tab_schedule_vc_item_left_strip";
  String get scheduleTabScheduleVcItemTime => "schedule_tab_schedule_vc_item_time";
  String get scheduleTabScheduleVcItemTimeIcon => "schedule_tab_schedule_vc_item_time_icon";
  String get scheduleTabScheduleVcItemTimeAmPmText => "schedule_tab_schedule_vc_item_time_am_pm_text";
  String get scheduleTabScheduleVcItemTitle => "schedule_tab_schedule_vc_item_title";
  String get scheduleTabScheduleVcItemSubTitle => "schedule_tab_schedule_vc_item_sub_title";
  String get scheduleTabScheduleVcItemToggle => "schedule_tab_schedule_vc_item_toggle";

  // ------------ Message Tab --------------
  String get messageTab => "message_tab";
  String get messageTabMessagePanel => "message_tab_message_panel";
  String get messageTabMessagePanelMessagePlayers => "message_tab_message_panel_message_players";
  String get messageTabMessagePanelMessagePlayersHeader => "message_tab_message_panel_message_players_header";
  String get messageTabMessagePanelMessagePlayersList => "message_tab_message_panel_message_players_list";
  String get messageTabMessagePanelMessagePlayersListItem => "message_tab_message_panel_message_players_list_item";
  String get messageTabMessagePanelMessagePlayersListItemCheckbox => "message_tab_message_panel_message_players_list_item_checkbox";
  String get messageTabMessagePanelMessagePlayersListItemText => "message_tab_message_panel_message_players_list_item_text";
  String get messageTabMessagePanelMessageList => "message_tab_message_panel_message_list";
  String get messageTabMessagePanelMessageListHeader => "message_tab_message_panel_message_list_header";
  String get messageTabMessagePanelMessageListEmpty => "message_tab_message_panel_message_list_empty";
  String get messageTabMessagePanelMessageListEmptyText => "message_tab_message_panel_message_list_empty_text";
  String get messageTabMessagePanelMessageListContent => "message_tab_message_panel_message_content_list";
  String get messageTabMessagePanelMessageListContentHeader => "message_tab_message_panel_message_list_content_header";
  String get messageTabMessagePanelMessageListContentHeaderText => "message_tab_message_panel_message_list_content_header_text";
  String get messageTabMessagePanelMessageListEmptyContent => "message_tab_message_panel_message_list_empty_content";
  String get messageTabMessagePanelMessageListEmptyContentText => "message_tab_message_panel_message_list_empty_content_text";
  String get messageTabMessagePanelMessageListContentItem => "message_tab_message_panel_message_list_content_item";
  String get messageTabMessagePanelMessageListContentItemCheckBox => "message_tab_message_panel_message_list_content_item_checkbox";
  String get messageTabMessagePanelMessageListContentItemText => "message_tab_message_panel_message_list_content_item_text";
  String get messageTabPages => "message_tab_pages";
  String get messageTabPagesHeader => "message_tab_pages_header";
  String get messageTabPagesEmptyList => "message_tab_pages_empty_list";
  String get messageTabPagesEmptyListText => "message_tab_pages_empty_list_text";
  String get messageTabPagesList => "message_tab_pages_list";
  String get messageTabPagesListItem => "message_tab_pages_list_item";
  String get messageTabPagesListItemIcon => "message_tab_pages_list_item_icon";
  String get messageTabPagesListItemName => "message_tab_pages_list_item_name";
  String get messageTabVirtualController => "message_tab_virtual_controller";
  String get messageTabVirtualControllerHeader => "message_tab_virtual_controller_header";
  String get messageTabVirtualControllerContent => "message_tab_virtual_controller_content";
  String get messageTabVirtualControllerContentHeader => "message_tab_virtual_controller_content_header";
  String get messageTabVirtualControllerContentHeaderText => "message_tab_virtual_controller_content_header_text";
  String get messageTabVirtualControllerContentList => "message_tab_virtual_controller_content_list";

  // ------------ Settings Tab --------------
  String get settingsTab => "controller_settings_tab";
  String get settingsTabvirtualControlsection => "controller_settings_tab_virtual_controller_section";
  String get settingsTabvirtualControlsectionHeader => "controller_settings_tab_virtual_controller_section_header";
  String get settingsTabvirtualControlsectionQrPanel => "controller_settings_tab_virtual_controller_section_qr_panel";
  String get settingsTabvirtualControlsectiondesc => "controller_settings_tab_virtual_controller_section_description";
  String get settingsTabvirtualControlsectiondesclabel => "controller_settings_tab_virtual_controller_section_description_label";
  String get settingsTabvirtualControlsectiondesctext => "controller_settings_tab_virtual_controller_section_description_text";
  String get settingsTabvirtualControlsectiondescprintbutton => "controller_settings_tab_virtual_controller_section_description_print_button";
  String get settingsTabvirtualControlsectiondescdownloadbutton => "controller_settings_tab_virtual_controller_section_description_download_button";
  String get settingsTabvirtualControlsectionprintdialog => "controller_settings_tab_virtual_controller_section_print_dialog";
  String get settingsTabvirtualControlsectionprintdialogheader => "controller_settings_tab_virtual_controller_section_print_dialog_header";
  String get settingsTabControlsection => "controller_settings_tab_virtual_controller_section";
  String get settingsTabControlsectionHeader => "controller_settings_tab_virtual_controller_section_header";
  String get settingsTabControlsectionscreenmode => "controller_settings_tab_virtual_controller_section_screen_mode_section_items";
  String get settingsTabControlsectionscreenmodecontent => "controller_settings_tab_virtual_controller_section_screen_mode_section";
  String get settingsTabControlsectionscreenmodelight => "controller_settings_tab_virtual_controller_section_screen_mode_light_section";
  String get settingsTabControlsectionscreenmodedark => "controller_settings_tab_virtual_controller_section_screen_mode_dark_section";
  String get settingsTabControlsectionscreenmodelabel => "controller_settings_tab_virtual_controller_section_screen_mode_section_label";
  String get settingsTabControlsectionscreensavermode => "controller_settings_tab_virtual_controller_section_screen_saver_section";
  String get settingsTabControlsectionscreensavermodeitems => "controller_settings_tab_virtual_controller_section_screen_saver_items";
  String get settingsTabControlsectionscreensavermodelabel => "controller_settings_tab_virtual_controller_section_screen_saver_label";
  String get settingsTabControlsectionsleeptimer => "controller_settings_tab_virtual_controller_section_sleep_timer_section";
  String get settingsTabControlsectionsleeptimerlabel => "controller_settings_tab_virtual_controller_section_sleep_timer_label";
  String get settingsTabControlsectionsleeptimertext => "controller_settings_tab_virtual_controller_section_sleep_timer_text";
  String get settingsTabControlsectionsleeptimerdropdown => "controller_settings_tab_virtual_controller_section_sleep_timer_dropdown";
  String get settingsTabControlsectionWakeFunction => "controller_settings_tab_virtual_controller_section_wake_function_section";
  String get settingsTabControlsectionWakeFunctionitems => "controller_settings_tab_virtual_controller_section_wake_function_section_items";
  String get settingsTabControlsectionWakeFunctionLabel => "controller_settings_tab_virtual_controller_section_wake_function_label";
  String get settingsTabControlsectionWakeFunctionZoneDropdown => "controller_settings_tab_virtual_controller_section_wake_function_zone_dropdown";
}
