platform: fusion-mini-DSP
firmwareBundleVersion: 1.0.0
manufacturer: Fusion Audio
model: Fusion-Mini DSP
deviceType: DSP

compatibility:
  fusionServicesApiLevel: 1.1.0
  minDesktopAppVersion: 1.0.0
  cloudServicesApiLevel: 1.0.0
