// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/products": {
            "get": {
                "description": "Get all available products including speakers, amplifiers and digital signal processors",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get all products",
                "responses": {
                    "200": {
                        "description": "Successful response with all products",
                        "schema": {
                            "$ref": "#/definitions/types.ProductResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "description": "Get a specific product by its unique identifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get product by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with product details",
                        "schema": {
                            "$ref": "#/definitions/types.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - Product ID is required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "description": "Get all projects in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get all projects",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Filter projects by archived status",
                        "name": "is_archived",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to sort projects by (e.g., created_at, updated_at)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Sort order (ascending or descending)",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved all projects",
                        "schema": {
                            "$ref": "#/definitions/types.GetAllProjectsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid query parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized do perform this action",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.InternalServerError"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new project in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Create a new project",
                "parameters": [
                    {
                        "description": "Project details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ProjectCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created project",
                        "schema": {
                            "$ref": "#/definitions/types.ProjectCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized to perform this action",
                        "schema": {
                            "$ref": "#/definitions/types.BadRequestError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.InternalServerError"
                        }
                    }
                }
            }
        },
        "/projects/{id}": {
            "delete": {
                "description": "Delete a project by its unique identifier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Delete project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted project"
                    },
                    "401": {
                        "description": "Unauthorized to perform this action",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "$ref": "#/definitions/types.BadRequestError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User not assigned to project, project archived, or locked by another user",
                        "schema": {
                            "$ref": "#/definitions/types.ForbiddenError"
                        }
                    },
                    "404": {
                        "description": "Project or user not found",
                        "schema": {
                            "$ref": "#/definitions/types.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.InternalServerError"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update an existing project by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Update project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated project details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ProjectUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully created project",
                        "schema": {
                            "$ref": "#/definitions/types.ProjectUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/types.BadRequestError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User not assigned to project, project archived, or locked by another user",
                        "schema": {
                            "$ref": "#/definitions/types.ForbiddenError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized to perform this action",
                        "schema": {
                            "$ref": "#/definitions/types.BadRequestError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User not assigned to project or project locked by another user",
                        "schema": {
                            "$ref": "#/definitions/types.ForbiddenError"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "$ref": "#/definitions/types.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.InternalServerError"
                        }
                    }
                }
            }
        },
        "/projects/{projectId}/lock": {
            "post": {
                "description": "Lock or unlock a project for a specific user based on request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Update project lock status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Lock/unlock request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ProjectLockRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully updated project lock status"
                    },
                    "400": {
                        "description": "Bad request - Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/types.BadRequestError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User not assigned to project or project already locked by another user",
                        "schema": {
                            "$ref": "#/definitions/types.ForbiddenError"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "$ref": "#/definitions/types.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.InternalServerError"
                        }
                    }
                }
            }
        },
        "/projects/{projectId}/star/{userId}": {
            "post": {
                "description": "Star or unstar a project for a specific user based on request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Update project star status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Star/unstar request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ProjectStarRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully updated project star status"
                    },
                    "400": {
                        "description": "Bad request - Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/types.BadRequestError"
                        }
                    },
                    "403": {
                        "description": "Forbidden - User not assigned to project, project archived, or locked by another user",
                        "schema": {
                            "$ref": "#/definitions/types.ForbiddenError"
                        }
                    },
                    "404": {
                        "description": "Project or User not found",
                        "schema": {
                            "$ref": "#/definitions/types.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.InternalServerError"
                        }
                    }
                }
            }
        },
        "/projects/{projectId}/users/{userEmail}": {
            "put": {
                "description": "Assign a user to a project by project ID and user email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Assign a user to a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Email",
                        "name": "userEmail",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "User successfully assigned to the project"
                    },
                    "404": {
                        "description": "Project or User not found",
                        "schema": {
                            "$ref": "#/definitions/types.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.InternalServerError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a user from a project by project ID and user email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Remove a user from a project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User Email",
                        "name": "userEmail",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "User successfully removed from the project"
                    },
                    "404": {
                        "description": "Project or User not found, or user not assigned to the project",
                        "schema": {
                            "$ref": "#/definitions/types.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.InternalServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.Amplifier": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "meta_info": {
                    "$ref": "#/definitions/types.Amplifier_meta_response"
                }
            }
        },
        "types.Amplifier_meta_response": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "power_output": {
                    "$ref": "#/definitions/types.powerOutput"
                },
                "total_capacity": {
                    "type": "number"
                }
            }
        },
        "types.Budget": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Bad Request"
                }
            }
        },
        "types.DSP_meta": {
            "type": "object",
            "properties": {
                "acoustic_echo_cancellation": {
                    "type": "object",
                    "properties": {
                        "channels": {
                            "type": "integer"
                        }
                    }
                },
                "configuration_software": {
                    "type": "string"
                },
                "dimensions": {
                    "type": "object",
                    "properties": {
                        "rack_space": {
                            "type": "string"
                        },
                        "size": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "depth": {
                                        "type": "integer"
                                    },
                                    "height": {
                                        "type": "integer"
                                    },
                                    "unit": {
                                        "type": "string"
                                    },
                                    "width": {
                                        "type": "integer"
                                    }
                                }
                            }
                        }
                    }
                },
                "dsp_architecture": {
                    "type": "string"
                },
                "firmware": {
                    "type": "object",
                    "properties": {
                        "current_published_version": {
                            "type": "string"
                        },
                        "current_running_version": {
                            "type": "string"
                        }
                    }
                },
                "gpio_logic_ports": {
                    "type": "object",
                    "properties": {
                        "inputs": {
                            "type": "integer"
                        },
                        "outputs": {
                            "type": "integer"
                        }
                    }
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "max_number_of_analog_control": {
                    "type": "integer"
                },
                "max_number_of_digital_control": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "net_weight": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "unit": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            }
                        }
                    }
                },
                "number_of_inputs_and_outputs": {
                    "type": "object",
                    "properties": {
                        "aes67": {
                            "type": "object",
                            "properties": {
                                "max_inputs": {
                                    "type": "integer"
                                },
                                "max_outputs": {
                                    "type": "integer"
                                }
                            }
                        },
                        "dante": {
                            "type": "object",
                            "properties": {
                                "max_inputs": {
                                    "type": "integer"
                                },
                                "max_outputs": {
                                    "type": "integer"
                                }
                            }
                        },
                        "fusion_connect": {
                            "type": "object",
                            "properties": {
                                "max_inputs": {
                                    "type": "integer"
                                },
                                "max_outputs": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                },
                "product_codes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "safe_operating_temperature": {
                    "type": "object",
                    "properties": {
                        "max": {
                            "type": "integer"
                        },
                        "min": {
                            "type": "integer"
                        },
                        "unit": {
                            "type": "string"
                        }
                    }
                },
                "skus": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "supported_bose_professional_dante_endpoints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "types.DigitalSignalProcessor": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "meta_info": {
                    "$ref": "#/definitions/types.DSP_meta"
                }
            }
        },
        "types.EnvironmentType": {
            "type": "string",
            "enum": [
                "indoor",
                "outdoor",
                "hybrid"
            ],
            "x-enum-varnames": [
                "EnvironmentTypeIndoor",
                "EnvironmentTypeOutdoor",
                "EnvironmentTypeHybrid"
            ]
        },
        "types.GetAllProjectsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Project"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "types.ProductResponse": {
            "type": "object",
            "properties": {
                "amplifier": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Amplifier"
                    }
                },
                "digital_signal_processors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.DigitalSignalProcessor"
                    }
                },
                "speaker": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Speaker"
                    }
                }
            }
        },
        "types.Project": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "application": {
                    "type": "string",
                    "example": "Audio System Design"
                },
                "budget": {
                    "$ref": "#/definitions/types.Budget"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "example": "Professional audio system for corporate conference room"
                },
                "environment_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.EnvironmentType"
                        }
                    ],
                    "example": "indoor"
                },
                "environment_type": {
                    "$ref": "#/definitions/types.EnvironmentType"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "is_archived": {
                    "type": "boolean"
                },
                "is_starred": {
                    "type": "boolean"
                },
                "locked_by_user": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "project_file_url": {
                    "type": "string",
                    "example": "https://storage.example.com/projects/123e4567/project.json"
                },
                "project_phase": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.ProjectPhase"
                        }
                    ],
                    "example": "Development"
                },
                "thumbnail_url": {
                    "type": "string",
                    "example": "https://storage.example.com/projects/123e4567/thumbnail.jpg"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-10-20T16:45:00Z"
                },
                "project_phase": {
                    "$ref": "#/definitions/types.ProjectPhase"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "venue": {
                    "type": "string"
                }
            }
        },
        "types.ProjectCreateRequest": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "application": {
                    "type": "string"
                },
                "budget": {
                    "$ref": "#/definitions/types.Budget"
                },
                "description": {
                    "type": "string"
                },
                "environment_type": {
                    "$ref": "#/definitions/types.EnvironmentType"
                },
                "id": {
                    "type": "string"
                },
                "is_project_file_created": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "project_phase": {
                    "$ref": "#/definitions/types.ProjectPhase"
                },
                "venue": {
                    "type": "string"
                }
            }
        },
        "types.ProjectCreateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "project_upload_url": {
                    "type": "string"
                }
            }
        },
        "types.ProjectPhase": {
            "type": "string",
            "enum": [
                "Proposal",
                "Development",
                "Commissioned"
            ],
            "x-enum-varnames": [
                "ProjectPhaseProposal",
                "ProjectPhaseDevelopment",
                "ProjectPhaseCommissioned"
            ]
        },
        "types.ProjectUpdateRequest": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "application": {
                    "type": "string"
                },
                "budget": {
                    "$ref": "#/definitions/types.Budget"
                },
                "description": {
                    "type": "string"
                },
                "environment_type": {
                    "$ref": "#/definitions/types.EnvironmentType"
                },
                "id": {
                    "type": "string"
                },
                "is_archived": {
                    "type": "boolean"
                },
                "is_project_file_dirty": {
                    "type": "boolean"
                },
                "is_starred": {
                    "type": "boolean"
                },
                "lock_project": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "project_phase": {
                    "$ref": "#/definitions/types.ProjectPhase"
                },
                "venue": {
                    "type": "string"
                }
            }
        },
        "types.ProjectUpdateResponse": {
            "type": "object",
            "properties": {
                "project_upload_url": {
                    "type": "string"
                }
            }
        },
        "types.Speaker": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "meta_info": {
                    "$ref": "#/definitions/types.Speaker_meta_response"
                }
            }
        },
        "types.Speaker_meta_response": {
            "type": "object",
            "properties": {
                "available_taps": {
                    "type": "object",
                    "properties": {
                        "100v": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            }
                        },
                        "70v": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            }
                        }
                    }
                },
                "environment": {
                    "type": "string"
                },
                "image_url": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "is_subwoofer": {
                    "type": "boolean"
                },
                "max_spl": {
                    "type": "number"
                },
                "model": {
                    "type": "string"
                },
                "mount_type": {
                    "type": "string"
                },
                "nominal_impedance": {
                    "$ref": "#/definitions/types.nominal_impedence"
                },
                "power_handling": {
                    "type": "object",
                    "properties": {
                        "long_term_continuous": {
                            "type": "string"
                        },
                        "peak": {
                            "type": "string"
                        },
                        "unit": {
                            "type": "string"
                        }
                    }
                },
                "sensitivity": {
                    "type": "object",
                    "properties": {
                        "at": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "key": {
                                        "type": "string"
                                    },
                                    "value": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "unit": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "types.nominal_impedence": {
            "type": "object",
            "properties": {
                "unit": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "types.powerOutput": {
            "type": "object",
            "properties": {
                "asymmetrical": {
                    "type": "object",
                    "properties": {
                        "peak_per_channel": {
                            "type": "object",
                            "properties": {
                                "at": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "key": {
                                                "type": "string"
                                            },
                                            "value": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                },
                                "unit": {
                                    "type": "string"
                                }
                            }
                        },
                        "peak_per_channel_high_voltage": {
                            "type": "object",
                            "properties": {
                                "at": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "key": {
                                                "type": "string"
                                            },
                                            "value": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                },
                                "unit": {
                                    "type": "string"
                                }
                            }
                        },
                        "rated_per_channel": {
                            "type": "object",
                            "properties": {
                                "at": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "key": {
                                                "type": "string"
                                            },
                                            "value": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                },
                                "unit": {
                                    "type": "string"
                                }
                            }
                        },
                        "rated_per_channel_high_voltage": {
                            "type": "object",
                            "properties": {
                                "at": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "key": {
                                                "type": "string"
                                            },
                                            "value": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                },
                                "unit": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "symmetrical": {
                    "type": "object",
                    "properties": {
                        "peak_per_channel": {
                            "type": "object",
                            "properties": {
                                "at": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "key": {
                                                "type": "string"
                                            },
                                            "value": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                },
                                "unit": {
                                    "type": "string"
                                }
                            }
                        },
                        "peak_per_channel_high_voltage": {
                            "type": "object",
                            "properties": {
                                "at": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "key": {
                                                "type": "string"
                                            },
                                            "value": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                },
                                "unit": {
                                    "type": "string"
                                }
                            }
                        },
                        "rated_per_channel": {
                            "type": "object",
                            "properties": {
                                "at": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "impedance": {
                                                "type": "object",
                                                "properties": {
                                                    "unit": {
                                                        "type": "string"
                                                    },
                                                    "value": {
                                                        "type": "integer"
                                                    }
                                                }
                                            },
                                            "power": {
                                                "type": "object",
                                                "properties": {
                                                    "unit": {
                                                        "type": "string"
                                                    },
                                                    "value": {
                                                        "type": "integer"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "rated_per_channel_high_voltage": {
                            "type": "object",
                            "properties": {
                                "at": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "key": {
                                                "type": "string"
                                            },
                                            "value": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                },
                                "unit": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8020",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Fusion Cloud Backend API",
	Description:      "This is the Fusion Cloud Backend API server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
