basePath: /api/v1
definitions:
  types.Amplifier:
    properties:
      category:
        type: string
      id:
        type: integer
      meta_info:
        $ref: '#/definitions/types.Amplifier_meta_response'
    type: object
  types.Amplifier_meta_response:
    properties:
      channels:
        type: integer
      image_url:
        items:
          type: string
        type: array
      name:
        type: string
      power_output:
        $ref: '#/definitions/types.powerOutput'
      total_capacity:
        type: number
    type: object
  types.Budget:
    properties:
      message:
        example: Bad Request
        type: string
    type: object
  types.DSP_meta:
    properties:
      acoustic_echo_cancellation:
        properties:
          channels:
            type: integer
        type: object
      configuration_software:
        type: string
      dimensions:
        properties:
          rack_space:
            type: string
          size:
            items:
              properties:
                depth:
                  type: integer
                height:
                  type: integer
                unit:
                  type: string
                width:
                  type: integer
              type: object
            type: array
        type: object
      dsp_architecture:
        type: string
      firmware:
        properties:
          current_published_version:
            type: string
          current_running_version:
            type: string
        type: object
      gpio_logic_ports:
        properties:
          inputs:
            type: integer
          outputs:
            type: integer
        type: object
      id:
        type: integer
      images:
        items:
          type: string
        type: array
      max_number_of_analog_control:
        type: integer
      max_number_of_digital_control:
        type: integer
      model:
        type: string
      name:
        type: string
      net_weight:
        items:
          properties:
            unit:
              type: string
            value:
              type: string
          type: object
        type: array
      number_of_inputs_and_outputs:
        properties:
          aes67:
            properties:
              max_inputs:
                type: integer
              max_outputs:
                type: integer
            type: object
          dante:
            properties:
              max_inputs:
                type: integer
              max_outputs:
                type: integer
            type: object
          fusion_connect:
            properties:
              max_inputs:
                type: integer
              max_outputs:
                type: integer
            type: object
        type: object
      product_codes:
        items:
          type: string
        type: array
      safe_operating_temperature:
        properties:
          max:
            type: integer
          min:
            type: integer
          unit:
            type: string
        type: object
      skus:
        items:
          type: integer
        type: array
      supported_bose_professional_dante_endpoints:
        items:
          type: string
        type: array
    type: object
  types.DigitalSignalProcessor:
    properties:
      category:
        type: string
      id:
        type: integer
      meta_info:
        $ref: '#/definitions/types.DSP_meta'
    type: object
  types.EnvironmentType:
    enum:
    - indoor
    - outdoor
    - hybrid
    type: string
    x-enum-varnames:
    - EnvironmentTypeIndoor
    - EnvironmentTypeOutdoor
    - EnvironmentTypeHybrid
  types.GetAllProjectsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/types.Project'
        type: array
      page:
        type: integer
      total_count:
        type: integer
      total_pages:
        type: integer
    type: object
  types.ProductResponse:
    properties:
      amplifier:
        items:
          $ref: '#/definitions/types.Amplifier'
        type: array
      digital_signal_processors:
        items:
          $ref: '#/definitions/types.DigitalSignalProcessor'
        type: array
      speaker:
        items:
          $ref: '#/definitions/types.Speaker'
        type: array
    type: object
  types.Project:
    properties:
      account_id:
        type: string
      application:
        example: Audio System Design
        type: string
      budget:
        $ref: '#/definitions/types.Budget'
      created_at:
        type: string
      description:
        example: Professional audio system for corporate conference room
        type: string
      environment_type:
        $ref: '#/definitions/types.EnvironmentType'
      id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      is_archived:
        example: false
        type: boolean
      is_starred:
        example: true
        type: boolean
      locked_by_user:
        example: user456
        type: string
      is_archived:
        type: boolean
      is_starred:
        type: boolean
      locked_by_user:
        type: string
      name:
        type: string
      project_file_url:
        example: https://storage.example.com/projects/123e4567/project.json
        type: string
      project_phase:
        allOf:
        - $ref: '#/definitions/types.ProjectPhase'
        example: Development
      thumbnail_url:
        example: https://storage.example.com/projects/123e4567/thumbnail.jpg
        type: string
      updated_at:
        example: "2023-10-20T16:45:00Z"
        type: string
      project_phase:
        $ref: '#/definitions/types.ProjectPhase'
      thumbnail_url:
        type: string
      updated_at:
        type: string
      venue:
        type: string
    type: object
  types.ProjectCreateRequest:
    properties:
      account_id:
        type: string
      application:
        type: string
      budget:
        $ref: '#/definitions/types.Budget'
      description:
        type: string
      environment_type:
        $ref: '#/definitions/types.EnvironmentType'
      id:
        type: string
      is_project_file_created:
        type: boolean
      name:
        type: string
      project_phase:
        $ref: '#/definitions/types.ProjectPhase'
      venue:
        type: string
    type: object
  types.ProjectCreateResponse:
    properties:
      id:
        type: string
      project_upload_url:
        type: string
    type: object
  types.ProjectPhase:
    enum:
    - Proposal
    - Development
    - Commissioned
    type: string
    x-enum-varnames:
    - ProjectPhaseProposal
    - ProjectPhaseDevelopment
    - ProjectPhaseCommissioned
  types.ProjectUpdateRequest:
    properties:
      account_id:
        type: string
      application:
        type: string
      budget:
        $ref: '#/definitions/types.Budget'
      description:
        type: string
      environment_type:
        $ref: '#/definitions/types.EnvironmentType'
      id:
        type: string
      is_archived:
        type: boolean
      is_project_file_dirty:
        type: boolean
      is_starred:
        type: boolean
      lock_project:
        type: boolean
      name:
        type: string
      project_phase:
        $ref: '#/definitions/types.ProjectPhase'
      venue:
        type: string
    type: object
  types.ProjectUpdateResponse:
    properties:
      project_upload_url:
        type: string
    type: object
  types.Speaker:
    properties:
      category:
        type: string
      id:
        type: integer
      meta_info:
        $ref: '#/definitions/types.Speaker_meta_response'
    type: object
  types.Speaker_meta_response:
    properties:
      available_taps:
        properties:
          70v:
            items:
              type: number
            type: array
          100v:
            items:
              type: number
            type: array
        type: object
      environment:
        type: string
      image_url:
        items:
          type: string
        type: array
      is_subwoofer:
        type: boolean
      max_spl:
        type: number
      model:
        type: string
      mount_type:
        type: string
      nominal_impedance:
        $ref: '#/definitions/types.nominal_impedence'
      power_handling:
        properties:
          long_term_continuous:
            type: string
          peak:
            type: string
          unit:
            type: string
        type: object
      sensitivity:
        properties:
          at:
            items:
              properties:
                key:
                  type: string
                value:
                  type: string
              type: object
            type: array
          unit:
            type: string
        type: object
    type: object
  types.nominal_impedence:
    properties:
      unit:
        type: string
      value:
        type: string
    type: object
  types.powerOutput:
    properties:
      asymmetrical:
        properties:
          peak_per_channel:
            properties:
              at:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: integer
                  type: object
                type: array
              unit:
                type: string
            type: object
          peak_per_channel_high_voltage:
            properties:
              at:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: integer
                  type: object
                type: array
              unit:
                type: string
            type: object
          rated_per_channel:
            properties:
              at:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: integer
                  type: object
                type: array
              unit:
                type: string
            type: object
          rated_per_channel_high_voltage:
            properties:
              at:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: integer
                  type: object
                type: array
              unit:
                type: string
            type: object
        type: object
      symmetrical:
        properties:
          peak_per_channel:
            properties:
              at:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: integer
                  type: object
                type: array
              unit:
                type: string
            type: object
          peak_per_channel_high_voltage:
            properties:
              at:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: integer
                  type: object
                type: array
              unit:
                type: string
            type: object
          rated_per_channel:
            properties:
              at:
                items:
                  properties:
                    impedance:
                      properties:
                        unit:
                          type: string
                        value:
                          type: integer
                      type: object
                    power:
                      properties:
                        unit:
                          type: string
                        value:
                          type: integer
                      type: object
                  type: object
                type: array
            type: object
          rated_per_channel_high_voltage:
            properties:
              at:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: integer
                  type: object
                type: array
              unit:
                type: string
            type: object
        type: object
    type: object
host: localhost:8020
info:
  contact: {}
  description: This is the Fusion Cloud Backend API server.
  title: Fusion Cloud Backend API
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Get all available products including speakers, amplifiers and digital
        signal processors
      produces:
      - application/json
      responses:
        "200":
          description: Successful response with all products
          schema:
            $ref: '#/definitions/types.ProductResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all products
      tags:
      - products
  /products/{id}:
    get:
      consumes:
      - application/json
      description: Get a specific product by its unique identifier
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response with product details
          schema:
            $ref: '#/definitions/types.ProductResponse'
        "400":
          description: Bad request - Product ID is required
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Product not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get product by ID
      tags:
      - products
  /projects:
    get:
      consumes:
      - application/json
      description: Get all projects in the system
      parameters:
      - description: Filter projects by archived status
        in: query
        name: is_archived
        type: boolean
      - description: Field to sort projects by (e.g., created_at, updated_at)
        in: query
        name: sort_by
        type: string
      - description: Sort order (ascending or descending)
        enum:
        - asc
        - desc
        in: query
        name: sort_order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved all projects
          schema:
            $ref: '#/definitions/types.GetAllProjectsResponse'
        "400":
          description: Bad request - Invalid query parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized do perform this action
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/types.InternalServerError'
      summary: Get all projects
      tags:
      - projects
    post:
      consumes:
      - application/json
      description: Create a new project in the system
      parameters:
      - description: Project details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.ProjectCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created project
          schema:
            $ref: '#/definitions/types.ProjectCreateResponse'
        "400":
          description: Bad request - Invalid payload
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized to perform this action
          schema:
            $ref: '#/definitions/types.BadRequestError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/types.InternalServerError'
      summary: Create a new project
      tags:
      - projects
  /projects/{projectId}:
    delete:
      consumes:
      - application/json
      description: Delete a project by its unique identifier
      parameters:
      - description: Project ID
        in: path
        name: projectId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Successfully deleted project
        "401":
          description: Unauthorized to perform this action
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/types.BadRequestError'
        "403":
          description: Forbidden - User not assigned to project, project archived,
            or locked by another user
          schema:
            $ref: '#/definitions/types.ForbiddenError'
        "404":
          description: Project or user not found
          schema:
            $ref: '#/definitions/types.NotFoundError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/types.InternalServerError'
      summary: Delete project
      tags:
      - projects
    patch:
      consumes:
      - application/json
      description: Update an existing project by its ID
      parameters:
      - description: Project ID
        in: path
        name: projectId
        required: true
        type: string
      - description: Updated project details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.ProjectUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created project
          schema:
            $ref: '#/definitions/types.ProjectUpdateResponse'
        "400":
          description: Bad request - Invalid payload
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized to perform this action
          schema:
            $ref: '#/definitions/types.BadRequestError'
        "403":
          description: Forbidden - User not assigned to project, project archived,
            or locked by another user
          schema:
            $ref: '#/definitions/types.ForbiddenError'
        "404":
          description: Project or user not found
          schema:
            $ref: '#/definitions/types.NotFoundError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/types.InternalServerError'
      summary: Update project
      tags:
      - projects
schemes:
- http
- https
swagger: "2.0"
