# NOTE: Using Python 3.5 features only for now, so Raphael Yocto SDK provided Python works.
import sys

from waflib import Options

top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_cxx')

    opt.add_option('--platform', type=str, default=sys.platform,
                   help='Target platform for cross-compiling')


def compiler_has_flag(conf, flag):
    conf.start_msg(f'  {flag}')
    try:
        conf.check_cxx(cxxflags=[flag], mandatory=True)
        conf.end_msg('yes')
        return True
    except conf.errors.ConfigurationError:
        conf.end_msg('no')
        return False


def detect_platform(conf):
    platforms = [
        # FLAG          name       strings                is-cross-compile
        ('IS_VARMINI', 'varmini', ['varmini'],            True),
        ('IS_RAPHAEL', 'raphael', ['raphael', 'Raphael'], True),
        ('IS_LINUX',   'Linux',   ['linux'],              False),
        ('IS_MACOS',   'macOS',   ['darwin'],             False)
    ]

    conf.env['is_cross_compile'] = False
    for key, name, strings, cross in platforms:
        conf.env[key] = False

    conf.start_msg('Detecting platform')
    platform = Options.options.platform
    for key, name, strings, is_cross in platforms:
        for s in strings:
            if platform.startswith(s):
                conf.env[key] = True
                conf.env['platform'] = name
                conf.env['is_cross_compile'] = is_cross
                conf.end_msg(name, color='CYAN')
                return

def configure(conf):
    conf.load('compiler_cxx')

    detect_platform(conf)

    if conf.env.is_cross_compile:
        conf.load(conf.env.platform, tooldir='wafconf')

    print('Checking compiler flags...')
    if compiler_has_flag(conf, '-Wtemplate-id-cdtor'):
        # GCC 14 gives a warning for templated ctor/dtor that are not valid in
        # C++20. We have -std=c++17. So disable the warning. With -Werror
        # compilation would fail.
        if not conf.env['IS_MACOS']:
            conf.env.append_value('CXXFLAGS', ['-Wno-template-id-cdtor'])

    if compiler_has_flag(conf, '-Wcalloc-transposed-args'):
        if not conf.env['IS_MACOS']:
            conf.env.append_value('CXXFLAGS', '-Wno-calloc-transposed-args')

    conf.env.append_value('CXXFLAGS', ['-std=c++17'])
    conf.env.append_value('CXXFLAGS', ['-Wall', '-Wextra', '-Werror'])
    conf.env.append_value('CXXFLAGS', ['-O3', '-ffast-math', '-fno-finite-math-only'])

    # spdlog from the Yocto SDK is configured for an external 'fmt' lib.
    conf.env.append_value('CXXFLAGS', ['-DSPDLOG_FMT_EXTERNAL'])
    # by default we compile out all TRACE logs as they may affect performance
    conf.env.append_value('CXXFLAGS',
                          ['-DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_DEBUG'])

    # This greatly reduces binary size.  Comment out to include symbols for gdb.
    conf.env.append_value('LDFLAGS', ['-Wl,-s'])

    # #to define USE_WEIGHTS_FILE
    # conf.env.append_value('CXXFLAGS', ['-DUSE_WEIGHTS_FILE'])

    if conf.env['IS_MACOS']:
        conf.env.append_value('INCLUDES', ['/opt/homebrew/include'])
        conf.env.append_value('LIBPATH', ['/opt/homebrew/lib'])
        conf.env.append_value('CXXFLAGS', '-DUSE_MAC_THREADS')

        # This is needed because of warnings in Boost property trees.
        conf.env.append_value('CXXFLAGS',
                           ['-Wno-deprecated-copy-with-user-provided-copy'])

    else:
        if conf.env['IS_LINUX']:
            # NOTE: Doing the old way of boost::bind for now.
            # /usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the 
            # global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, 
            # or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
            conf.env.append_value('CXXFLAGS', '-DBOOST_BIND_GLOBAL_PLACEHOLDERS')


def build(bld):
    bld(export_includes=['./include'], name='common-include')

    libs = ['fmt']

    bld.shlib(target='fusion_embedded_interface',
              source=bld.path.ant_glob(['src/*.cpp', 'src/*.c']),
              use=['common-include', 'fmt'],
              lib=libs,
              export_includes=['./include'])


