// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AccessLevel is an object representing the database table.
type AccessLevel struct {
	ID    int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Key   string `boil:"key" json:"key" toml:"key" yaml:"key"`
	Label string `boil:"label" json:"label" toml:"label" yaml:"label"`

	R *accessLevelR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accessLevelL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccessLevelColumns = struct {
	ID    string
	Key   string
	Label string
}{
	ID:    "id",
	Key:   "key",
	Label: "label",
}

var AccessLevelTableColumns = struct {
	ID    string
	Key   string
	Label string
}{
	ID:    "access_level.id",
	Key:   "access_level.key",
	Label: "access_level.label",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var AccessLevelWhere = struct {
	ID    whereHelperint
	Key   whereHelperstring
	Label whereHelperstring
}{
	ID:    whereHelperint{field: "\"access_level\".\"id\""},
	Key:   whereHelperstring{field: "\"access_level\".\"key\""},
	Label: whereHelperstring{field: "\"access_level\".\"label\""},
}

// AccessLevelRels is where relationship names are stored.
var AccessLevelRels = struct {
	FeaturePermissions string
}{
	FeaturePermissions: "FeaturePermissions",
}

// accessLevelR is where relationships are stored.
type accessLevelR struct {
	FeaturePermissions FeaturePermissionSlice `boil:"FeaturePermissions" json:"FeaturePermissions" toml:"FeaturePermissions" yaml:"FeaturePermissions"`
}

// NewStruct creates a new relationship struct
func (*accessLevelR) NewStruct() *accessLevelR {
	return &accessLevelR{}
}

func (o *AccessLevel) GetFeaturePermissions() FeaturePermissionSlice {
	if o == nil {
		return nil
	}

	return o.R.GetFeaturePermissions()
}

func (r *accessLevelR) GetFeaturePermissions() FeaturePermissionSlice {
	if r == nil {
		return nil
	}

	return r.FeaturePermissions
}

// accessLevelL is where Load methods for each relationship are stored.
type accessLevelL struct{}

var (
	accessLevelAllColumns            = []string{"id", "key", "label"}
	accessLevelColumnsWithoutDefault = []string{"key", "label"}
	accessLevelColumnsWithDefault    = []string{"id"}
	accessLevelPrimaryKeyColumns     = []string{"id"}
	accessLevelGeneratedColumns      = []string{}
)

type (
	// AccessLevelSlice is an alias for a slice of pointers to AccessLevel.
	// This should almost always be used instead of []AccessLevel.
	AccessLevelSlice []*AccessLevel
	// AccessLevelHook is the signature for custom AccessLevel hook methods
	AccessLevelHook func(context.Context, boil.ContextExecutor, *AccessLevel) error

	accessLevelQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accessLevelType                 = reflect.TypeOf(&AccessLevel{})
	accessLevelMapping              = queries.MakeStructMapping(accessLevelType)
	accessLevelPrimaryKeyMapping, _ = queries.BindMapping(accessLevelType, accessLevelMapping, accessLevelPrimaryKeyColumns)
	accessLevelInsertCacheMut       sync.RWMutex
	accessLevelInsertCache          = make(map[string]insertCache)
	accessLevelUpdateCacheMut       sync.RWMutex
	accessLevelUpdateCache          = make(map[string]updateCache)
	accessLevelUpsertCacheMut       sync.RWMutex
	accessLevelUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var accessLevelAfterSelectMu sync.Mutex
var accessLevelAfterSelectHooks []AccessLevelHook

var accessLevelBeforeInsertMu sync.Mutex
var accessLevelBeforeInsertHooks []AccessLevelHook
var accessLevelAfterInsertMu sync.Mutex
var accessLevelAfterInsertHooks []AccessLevelHook

var accessLevelBeforeUpdateMu sync.Mutex
var accessLevelBeforeUpdateHooks []AccessLevelHook
var accessLevelAfterUpdateMu sync.Mutex
var accessLevelAfterUpdateHooks []AccessLevelHook

var accessLevelBeforeDeleteMu sync.Mutex
var accessLevelBeforeDeleteHooks []AccessLevelHook
var accessLevelAfterDeleteMu sync.Mutex
var accessLevelAfterDeleteHooks []AccessLevelHook

var accessLevelBeforeUpsertMu sync.Mutex
var accessLevelBeforeUpsertHooks []AccessLevelHook
var accessLevelAfterUpsertMu sync.Mutex
var accessLevelAfterUpsertHooks []AccessLevelHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AccessLevel) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessLevelAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AccessLevel) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessLevelBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AccessLevel) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessLevelAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AccessLevel) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessLevelBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AccessLevel) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessLevelAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AccessLevel) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessLevelBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AccessLevel) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessLevelAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AccessLevel) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessLevelBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AccessLevel) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessLevelAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAccessLevelHook registers your hook function for all future operations.
func AddAccessLevelHook(hookPoint boil.HookPoint, accessLevelHook AccessLevelHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		accessLevelAfterSelectMu.Lock()
		accessLevelAfterSelectHooks = append(accessLevelAfterSelectHooks, accessLevelHook)
		accessLevelAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		accessLevelBeforeInsertMu.Lock()
		accessLevelBeforeInsertHooks = append(accessLevelBeforeInsertHooks, accessLevelHook)
		accessLevelBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		accessLevelAfterInsertMu.Lock()
		accessLevelAfterInsertHooks = append(accessLevelAfterInsertHooks, accessLevelHook)
		accessLevelAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		accessLevelBeforeUpdateMu.Lock()
		accessLevelBeforeUpdateHooks = append(accessLevelBeforeUpdateHooks, accessLevelHook)
		accessLevelBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		accessLevelAfterUpdateMu.Lock()
		accessLevelAfterUpdateHooks = append(accessLevelAfterUpdateHooks, accessLevelHook)
		accessLevelAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		accessLevelBeforeDeleteMu.Lock()
		accessLevelBeforeDeleteHooks = append(accessLevelBeforeDeleteHooks, accessLevelHook)
		accessLevelBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		accessLevelAfterDeleteMu.Lock()
		accessLevelAfterDeleteHooks = append(accessLevelAfterDeleteHooks, accessLevelHook)
		accessLevelAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		accessLevelBeforeUpsertMu.Lock()
		accessLevelBeforeUpsertHooks = append(accessLevelBeforeUpsertHooks, accessLevelHook)
		accessLevelBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		accessLevelAfterUpsertMu.Lock()
		accessLevelAfterUpsertHooks = append(accessLevelAfterUpsertHooks, accessLevelHook)
		accessLevelAfterUpsertMu.Unlock()
	}
}

// One returns a single accessLevel record from the query.
func (q accessLevelQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccessLevel, error) {
	o := &AccessLevel{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for access_level")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AccessLevel records from the query.
func (q accessLevelQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccessLevelSlice, error) {
	var o []*AccessLevel

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AccessLevel slice")
	}

	if len(accessLevelAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AccessLevel records in the query.
func (q accessLevelQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count access_level rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accessLevelQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if access_level exists")
	}

	return count > 0, nil
}

// FeaturePermissions retrieves all the feature_permission's FeaturePermissions with an executor.
func (o *AccessLevel) FeaturePermissions(mods ...qm.QueryMod) featurePermissionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"feature_permission\".\"access_level_id\"=?", o.ID),
	)

	return FeaturePermissions(queryMods...)
}

// LoadFeaturePermissions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (accessLevelL) LoadFeaturePermissions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccessLevel interface{}, mods queries.Applicator) error {
	var slice []*AccessLevel
	var object *AccessLevel

	if singular {
		var ok bool
		object, ok = maybeAccessLevel.(*AccessLevel)
		if !ok {
			object = new(AccessLevel)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccessLevel)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccessLevel))
			}
		}
	} else {
		s, ok := maybeAccessLevel.(*[]*AccessLevel)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccessLevel)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccessLevel))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &accessLevelR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accessLevelR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`feature_permission`),
		qm.WhereIn(`feature_permission.access_level_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load feature_permission")
	}

	var resultSlice []*FeaturePermission
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice feature_permission")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on feature_permission")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for feature_permission")
	}

	if len(featurePermissionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.FeaturePermissions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &featurePermissionR{}
			}
			foreign.R.AccessLevel = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.AccessLevelID {
				local.R.FeaturePermissions = append(local.R.FeaturePermissions, foreign)
				if foreign.R == nil {
					foreign.R = &featurePermissionR{}
				}
				foreign.R.AccessLevel = local
				break
			}
		}
	}

	return nil
}

// AddFeaturePermissions adds the given related objects to the existing relationships
// of the access_level, optionally inserting them as new records.
// Appends related to o.R.FeaturePermissions.
// Sets related.R.AccessLevel appropriately.
func (o *AccessLevel) AddFeaturePermissions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*FeaturePermission) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.AccessLevelID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"feature_permission\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"access_level_id"}),
				strmangle.WhereClause("\"", "\"", 2, featurePermissionPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.AccessLevelID = o.ID
		}
	}

	if o.R == nil {
		o.R = &accessLevelR{
			FeaturePermissions: related,
		}
	} else {
		o.R.FeaturePermissions = append(o.R.FeaturePermissions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &featurePermissionR{
				AccessLevel: o,
			}
		} else {
			rel.R.AccessLevel = o
		}
	}
	return nil
}

// AccessLevels retrieves all the records using an executor.
func AccessLevels(mods ...qm.QueryMod) accessLevelQuery {
	mods = append(mods, qm.From("\"access_level\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"access_level\".*"})
	}

	return accessLevelQuery{q}
}

// FindAccessLevel retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccessLevel(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*AccessLevel, error) {
	accessLevelObj := &AccessLevel{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"access_level\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, accessLevelObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from access_level")
	}

	if err = accessLevelObj.doAfterSelectHooks(ctx, exec); err != nil {
		return accessLevelObj, err
	}

	return accessLevelObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccessLevel) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no access_level provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accessLevelColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accessLevelInsertCacheMut.RLock()
	cache, cached := accessLevelInsertCache[key]
	accessLevelInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accessLevelAllColumns,
			accessLevelColumnsWithDefault,
			accessLevelColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accessLevelType, accessLevelMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accessLevelType, accessLevelMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"access_level\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"access_level\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into access_level")
	}

	if !cached {
		accessLevelInsertCacheMut.Lock()
		accessLevelInsertCache[key] = cache
		accessLevelInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AccessLevel.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccessLevel) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	accessLevelUpdateCacheMut.RLock()
	cache, cached := accessLevelUpdateCache[key]
	accessLevelUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accessLevelAllColumns,
			accessLevelPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update access_level, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"access_level\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, accessLevelPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accessLevelType, accessLevelMapping, append(wl, accessLevelPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update access_level row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for access_level")
	}

	if !cached {
		accessLevelUpdateCacheMut.Lock()
		accessLevelUpdateCache[key] = cache
		accessLevelUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q accessLevelQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for access_level")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for access_level")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccessLevelSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accessLevelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"access_level\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accessLevelPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in accessLevel slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all accessLevel")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AccessLevel) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no access_level provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accessLevelColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accessLevelUpsertCacheMut.RLock()
	cache, cached := accessLevelUpsertCache[key]
	accessLevelUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			accessLevelAllColumns,
			accessLevelColumnsWithDefault,
			accessLevelColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			accessLevelAllColumns,
			accessLevelPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert access_level, could not build update column list")
		}

		ret := strmangle.SetComplement(accessLevelAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(accessLevelPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert access_level, could not build conflict column list")
			}

			conflict = make([]string, len(accessLevelPrimaryKeyColumns))
			copy(conflict, accessLevelPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"access_level\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(accessLevelType, accessLevelMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accessLevelType, accessLevelMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert access_level")
	}

	if !cached {
		accessLevelUpsertCacheMut.Lock()
		accessLevelUpsertCache[key] = cache
		accessLevelUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AccessLevel record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccessLevel) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AccessLevel provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accessLevelPrimaryKeyMapping)
	sql := "DELETE FROM \"access_level\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from access_level")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for access_level")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accessLevelQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no accessLevelQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from access_level")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for access_level")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccessLevelSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(accessLevelBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accessLevelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"access_level\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accessLevelPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from accessLevel slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for access_level")
	}

	if len(accessLevelAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccessLevel) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccessLevel(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccessLevelSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccessLevelSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accessLevelPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"access_level\".* FROM \"access_level\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accessLevelPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AccessLevelSlice")
	}

	*o = slice

	return nil
}

// AccessLevelExists checks if the AccessLevel row exists.
func AccessLevelExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"access_level\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if access_level exists")
	}

	return exists, nil
}

// Exists checks if the AccessLevel row exists.
func (o *AccessLevel) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccessLevelExists(ctx, exec, o.ID)
}
