// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AccountTypeRole is an object representing the database table.
type AccountTypeRole struct {
	ID        int `boil:"id" json:"id" toml:"id" yaml:"id"`
	AccountID int `boil:"account_id" json:"account_id" toml:"account_id" yaml:"account_id"`
	RoleID    int `boil:"role_id" json:"role_id" toml:"role_id" yaml:"role_id"`

	R *accountTypeRoleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountTypeRoleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountTypeRoleColumns = struct {
	ID        string
	AccountID string
	RoleID    string
}{
	ID:        "id",
	AccountID: "account_id",
	RoleID:    "role_id",
}

var AccountTypeRoleTableColumns = struct {
	ID        string
	AccountID string
	RoleID    string
}{
	ID:        "account_type_role.id",
	AccountID: "account_type_role.account_id",
	RoleID:    "account_type_role.role_id",
}

// Generated where

var AccountTypeRoleWhere = struct {
	ID        whereHelperint
	AccountID whereHelperint
	RoleID    whereHelperint
}{
	ID:        whereHelperint{field: "\"account_type_role\".\"id\""},
	AccountID: whereHelperint{field: "\"account_type_role\".\"account_id\""},
	RoleID:    whereHelperint{field: "\"account_type_role\".\"role_id\""},
}

// AccountTypeRoleRels is where relationship names are stored.
var AccountTypeRoleRels = struct {
	Account   string
	Role      string
	RoleUsers string
}{
	Account:   "Account",
	Role:      "Role",
	RoleUsers: "RoleUsers",
}

// accountTypeRoleR is where relationships are stored.
type accountTypeRoleR struct {
	Account   *Account  `boil:"Account" json:"Account" toml:"Account" yaml:"Account"`
	Role      *Role     `boil:"Role" json:"Role" toml:"Role" yaml:"Role"`
	RoleUsers UserSlice `boil:"RoleUsers" json:"RoleUsers" toml:"RoleUsers" yaml:"RoleUsers"`
}

// NewStruct creates a new relationship struct
func (*accountTypeRoleR) NewStruct() *accountTypeRoleR {
	return &accountTypeRoleR{}
}

func (o *AccountTypeRole) GetAccount() *Account {
	if o == nil {
		return nil
	}

	return o.R.GetAccount()
}

func (r *accountTypeRoleR) GetAccount() *Account {
	if r == nil {
		return nil
	}

	return r.Account
}

func (o *AccountTypeRole) GetRole() *Role {
	if o == nil {
		return nil
	}

	return o.R.GetRole()
}

func (r *accountTypeRoleR) GetRole() *Role {
	if r == nil {
		return nil
	}

	return r.Role
}

func (o *AccountTypeRole) GetRoleUsers() UserSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRoleUsers()
}

func (r *accountTypeRoleR) GetRoleUsers() UserSlice {
	if r == nil {
		return nil
	}

	return r.RoleUsers
}

// accountTypeRoleL is where Load methods for each relationship are stored.
type accountTypeRoleL struct{}

var (
	accountTypeRoleAllColumns            = []string{"id", "account_id", "role_id"}
	accountTypeRoleColumnsWithoutDefault = []string{"account_id", "role_id"}
	accountTypeRoleColumnsWithDefault    = []string{"id"}
	accountTypeRolePrimaryKeyColumns     = []string{"id"}
	accountTypeRoleGeneratedColumns      = []string{}
)

type (
	// AccountTypeRoleSlice is an alias for a slice of pointers to AccountTypeRole.
	// This should almost always be used instead of []AccountTypeRole.
	AccountTypeRoleSlice []*AccountTypeRole
	// AccountTypeRoleHook is the signature for custom AccountTypeRole hook methods
	AccountTypeRoleHook func(context.Context, boil.ContextExecutor, *AccountTypeRole) error

	accountTypeRoleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountTypeRoleType                 = reflect.TypeOf(&AccountTypeRole{})
	accountTypeRoleMapping              = queries.MakeStructMapping(accountTypeRoleType)
	accountTypeRolePrimaryKeyMapping, _ = queries.BindMapping(accountTypeRoleType, accountTypeRoleMapping, accountTypeRolePrimaryKeyColumns)
	accountTypeRoleInsertCacheMut       sync.RWMutex
	accountTypeRoleInsertCache          = make(map[string]insertCache)
	accountTypeRoleUpdateCacheMut       sync.RWMutex
	accountTypeRoleUpdateCache          = make(map[string]updateCache)
	accountTypeRoleUpsertCacheMut       sync.RWMutex
	accountTypeRoleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var accountTypeRoleAfterSelectMu sync.Mutex
var accountTypeRoleAfterSelectHooks []AccountTypeRoleHook

var accountTypeRoleBeforeInsertMu sync.Mutex
var accountTypeRoleBeforeInsertHooks []AccountTypeRoleHook
var accountTypeRoleAfterInsertMu sync.Mutex
var accountTypeRoleAfterInsertHooks []AccountTypeRoleHook

var accountTypeRoleBeforeUpdateMu sync.Mutex
var accountTypeRoleBeforeUpdateHooks []AccountTypeRoleHook
var accountTypeRoleAfterUpdateMu sync.Mutex
var accountTypeRoleAfterUpdateHooks []AccountTypeRoleHook

var accountTypeRoleBeforeDeleteMu sync.Mutex
var accountTypeRoleBeforeDeleteHooks []AccountTypeRoleHook
var accountTypeRoleAfterDeleteMu sync.Mutex
var accountTypeRoleAfterDeleteHooks []AccountTypeRoleHook

var accountTypeRoleBeforeUpsertMu sync.Mutex
var accountTypeRoleBeforeUpsertHooks []AccountTypeRoleHook
var accountTypeRoleAfterUpsertMu sync.Mutex
var accountTypeRoleAfterUpsertHooks []AccountTypeRoleHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AccountTypeRole) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeRoleAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AccountTypeRole) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeRoleBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AccountTypeRole) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeRoleAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AccountTypeRole) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeRoleBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AccountTypeRole) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeRoleAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AccountTypeRole) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeRoleBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AccountTypeRole) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeRoleAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AccountTypeRole) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeRoleBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AccountTypeRole) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeRoleAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAccountTypeRoleHook registers your hook function for all future operations.
func AddAccountTypeRoleHook(hookPoint boil.HookPoint, accountTypeRoleHook AccountTypeRoleHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		accountTypeRoleAfterSelectMu.Lock()
		accountTypeRoleAfterSelectHooks = append(accountTypeRoleAfterSelectHooks, accountTypeRoleHook)
		accountTypeRoleAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		accountTypeRoleBeforeInsertMu.Lock()
		accountTypeRoleBeforeInsertHooks = append(accountTypeRoleBeforeInsertHooks, accountTypeRoleHook)
		accountTypeRoleBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		accountTypeRoleAfterInsertMu.Lock()
		accountTypeRoleAfterInsertHooks = append(accountTypeRoleAfterInsertHooks, accountTypeRoleHook)
		accountTypeRoleAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		accountTypeRoleBeforeUpdateMu.Lock()
		accountTypeRoleBeforeUpdateHooks = append(accountTypeRoleBeforeUpdateHooks, accountTypeRoleHook)
		accountTypeRoleBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		accountTypeRoleAfterUpdateMu.Lock()
		accountTypeRoleAfterUpdateHooks = append(accountTypeRoleAfterUpdateHooks, accountTypeRoleHook)
		accountTypeRoleAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		accountTypeRoleBeforeDeleteMu.Lock()
		accountTypeRoleBeforeDeleteHooks = append(accountTypeRoleBeforeDeleteHooks, accountTypeRoleHook)
		accountTypeRoleBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		accountTypeRoleAfterDeleteMu.Lock()
		accountTypeRoleAfterDeleteHooks = append(accountTypeRoleAfterDeleteHooks, accountTypeRoleHook)
		accountTypeRoleAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		accountTypeRoleBeforeUpsertMu.Lock()
		accountTypeRoleBeforeUpsertHooks = append(accountTypeRoleBeforeUpsertHooks, accountTypeRoleHook)
		accountTypeRoleBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		accountTypeRoleAfterUpsertMu.Lock()
		accountTypeRoleAfterUpsertHooks = append(accountTypeRoleAfterUpsertHooks, accountTypeRoleHook)
		accountTypeRoleAfterUpsertMu.Unlock()
	}
}

// One returns a single accountTypeRole record from the query.
func (q accountTypeRoleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccountTypeRole, error) {
	o := &AccountTypeRole{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for account_type_role")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AccountTypeRole records from the query.
func (q accountTypeRoleQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccountTypeRoleSlice, error) {
	var o []*AccountTypeRole

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AccountTypeRole slice")
	}

	if len(accountTypeRoleAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AccountTypeRole records in the query.
func (q accountTypeRoleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count account_type_role rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accountTypeRoleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if account_type_role exists")
	}

	return count > 0, nil
}

// Account pointed to by the foreign key.
func (o *AccountTypeRole) Account(mods ...qm.QueryMod) accountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AccountID),
	}

	queryMods = append(queryMods, mods...)

	return Accounts(queryMods...)
}

// Role pointed to by the foreign key.
func (o *AccountTypeRole) Role(mods ...qm.QueryMod) roleQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.RoleID),
	}

	queryMods = append(queryMods, mods...)

	return Roles(queryMods...)
}

// RoleUsers retrieves all the user's Users with an executor via role_id column.
func (o *AccountTypeRole) RoleUsers(mods ...qm.QueryMod) userQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"user\".\"role_id\"=?", o.ID),
	)

	return Users(queryMods...)
}

// LoadAccount allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (accountTypeRoleL) LoadAccount(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccountTypeRole interface{}, mods queries.Applicator) error {
	var slice []*AccountTypeRole
	var object *AccountTypeRole

	if singular {
		var ok bool
		object, ok = maybeAccountTypeRole.(*AccountTypeRole)
		if !ok {
			object = new(AccountTypeRole)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccountTypeRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccountTypeRole))
			}
		}
	} else {
		s, ok := maybeAccountTypeRole.(*[]*AccountTypeRole)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccountTypeRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccountTypeRole))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &accountTypeRoleR{}
		}
		args[object.AccountID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accountTypeRoleR{}
			}

			args[obj.AccountID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`account`),
		qm.WhereIn(`account.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Account")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for account")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for account")
	}

	if len(accountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Account = foreign
		if foreign.R == nil {
			foreign.R = &accountR{}
		}
		foreign.R.AccountTypeRoles = append(foreign.R.AccountTypeRoles, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AccountID == foreign.ID {
				local.R.Account = foreign
				if foreign.R == nil {
					foreign.R = &accountR{}
				}
				foreign.R.AccountTypeRoles = append(foreign.R.AccountTypeRoles, local)
				break
			}
		}
	}

	return nil
}

// LoadRole allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (accountTypeRoleL) LoadRole(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccountTypeRole interface{}, mods queries.Applicator) error {
	var slice []*AccountTypeRole
	var object *AccountTypeRole

	if singular {
		var ok bool
		object, ok = maybeAccountTypeRole.(*AccountTypeRole)
		if !ok {
			object = new(AccountTypeRole)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccountTypeRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccountTypeRole))
			}
		}
	} else {
		s, ok := maybeAccountTypeRole.(*[]*AccountTypeRole)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccountTypeRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccountTypeRole))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &accountTypeRoleR{}
		}
		args[object.RoleID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accountTypeRoleR{}
			}

			args[obj.RoleID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`roles`),
		qm.WhereIn(`roles.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Role")
	}

	var resultSlice []*Role
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Role")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for roles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for roles")
	}

	if len(roleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Role = foreign
		if foreign.R == nil {
			foreign.R = &roleR{}
		}
		foreign.R.AccountTypeRoles = append(foreign.R.AccountTypeRoles, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.RoleID == foreign.ID {
				local.R.Role = foreign
				if foreign.R == nil {
					foreign.R = &roleR{}
				}
				foreign.R.AccountTypeRoles = append(foreign.R.AccountTypeRoles, local)
				break
			}
		}
	}

	return nil
}

// LoadRoleUsers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (accountTypeRoleL) LoadRoleUsers(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccountTypeRole interface{}, mods queries.Applicator) error {
	var slice []*AccountTypeRole
	var object *AccountTypeRole

	if singular {
		var ok bool
		object, ok = maybeAccountTypeRole.(*AccountTypeRole)
		if !ok {
			object = new(AccountTypeRole)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccountTypeRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccountTypeRole))
			}
		}
	} else {
		s, ok := maybeAccountTypeRole.(*[]*AccountTypeRole)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccountTypeRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccountTypeRole))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &accountTypeRoleR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accountTypeRoleR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`user`),
		qm.WhereIn(`user.role_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load user")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice user")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RoleUsers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &userR{}
			}
			foreign.R.Role = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.RoleID {
				local.R.RoleUsers = append(local.R.RoleUsers, foreign)
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Role = local
				break
			}
		}
	}

	return nil
}

// SetAccount of the accountTypeRole to the related item.
// Sets o.R.Account to related.
// Adds o to related.R.AccountTypeRoles.
func (o *AccountTypeRole) SetAccount(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Account) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"account_type_role\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"account_id"}),
		strmangle.WhereClause("\"", "\"", 2, accountTypeRolePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AccountID = related.ID
	if o.R == nil {
		o.R = &accountTypeRoleR{
			Account: related,
		}
	} else {
		o.R.Account = related
	}

	if related.R == nil {
		related.R = &accountR{
			AccountTypeRoles: AccountTypeRoleSlice{o},
		}
	} else {
		related.R.AccountTypeRoles = append(related.R.AccountTypeRoles, o)
	}

	return nil
}

// SetRole of the accountTypeRole to the related item.
// Sets o.R.Role to related.
// Adds o to related.R.AccountTypeRoles.
func (o *AccountTypeRole) SetRole(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Role) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"account_type_role\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"role_id"}),
		strmangle.WhereClause("\"", "\"", 2, accountTypeRolePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.RoleID = related.ID
	if o.R == nil {
		o.R = &accountTypeRoleR{
			Role: related,
		}
	} else {
		o.R.Role = related
	}

	if related.R == nil {
		related.R = &roleR{
			AccountTypeRoles: AccountTypeRoleSlice{o},
		}
	} else {
		related.R.AccountTypeRoles = append(related.R.AccountTypeRoles, o)
	}

	return nil
}

// AddRoleUsers adds the given related objects to the existing relationships
// of the account_type_role, optionally inserting them as new records.
// Appends related to o.R.RoleUsers.
// Sets related.R.Role appropriately.
func (o *AccountTypeRole) AddRoleUsers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*User) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.RoleID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"user\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"role_id"}),
				strmangle.WhereClause("\"", "\"", 2, userPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.RoleID = o.ID
		}
	}

	if o.R == nil {
		o.R = &accountTypeRoleR{
			RoleUsers: related,
		}
	} else {
		o.R.RoleUsers = append(o.R.RoleUsers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &userR{
				Role: o,
			}
		} else {
			rel.R.Role = o
		}
	}
	return nil
}

// AccountTypeRoles retrieves all the records using an executor.
func AccountTypeRoles(mods ...qm.QueryMod) accountTypeRoleQuery {
	mods = append(mods, qm.From("\"account_type_role\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"account_type_role\".*"})
	}

	return accountTypeRoleQuery{q}
}

// FindAccountTypeRole retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountTypeRole(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*AccountTypeRole, error) {
	accountTypeRoleObj := &AccountTypeRole{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"account_type_role\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, accountTypeRoleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from account_type_role")
	}

	if err = accountTypeRoleObj.doAfterSelectHooks(ctx, exec); err != nil {
		return accountTypeRoleObj, err
	}

	return accountTypeRoleObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccountTypeRole) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no account_type_role provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountTypeRoleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accountTypeRoleInsertCacheMut.RLock()
	cache, cached := accountTypeRoleInsertCache[key]
	accountTypeRoleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accountTypeRoleAllColumns,
			accountTypeRoleColumnsWithDefault,
			accountTypeRoleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accountTypeRoleType, accountTypeRoleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountTypeRoleType, accountTypeRoleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"account_type_role\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"account_type_role\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into account_type_role")
	}

	if !cached {
		accountTypeRoleInsertCacheMut.Lock()
		accountTypeRoleInsertCache[key] = cache
		accountTypeRoleInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AccountTypeRole.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccountTypeRole) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	accountTypeRoleUpdateCacheMut.RLock()
	cache, cached := accountTypeRoleUpdateCache[key]
	accountTypeRoleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accountTypeRoleAllColumns,
			accountTypeRolePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update account_type_role, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"account_type_role\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, accountTypeRolePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountTypeRoleType, accountTypeRoleMapping, append(wl, accountTypeRolePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update account_type_role row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for account_type_role")
	}

	if !cached {
		accountTypeRoleUpdateCacheMut.Lock()
		accountTypeRoleUpdateCache[key] = cache
		accountTypeRoleUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q accountTypeRoleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for account_type_role")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for account_type_role")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountTypeRoleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountTypeRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"account_type_role\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accountTypeRolePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in accountTypeRole slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all accountTypeRole")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AccountTypeRole) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no account_type_role provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountTypeRoleColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountTypeRoleUpsertCacheMut.RLock()
	cache, cached := accountTypeRoleUpsertCache[key]
	accountTypeRoleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			accountTypeRoleAllColumns,
			accountTypeRoleColumnsWithDefault,
			accountTypeRoleColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			accountTypeRoleAllColumns,
			accountTypeRolePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert account_type_role, could not build update column list")
		}

		ret := strmangle.SetComplement(accountTypeRoleAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(accountTypeRolePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert account_type_role, could not build conflict column list")
			}

			conflict = make([]string, len(accountTypeRolePrimaryKeyColumns))
			copy(conflict, accountTypeRolePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"account_type_role\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(accountTypeRoleType, accountTypeRoleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountTypeRoleType, accountTypeRoleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert account_type_role")
	}

	if !cached {
		accountTypeRoleUpsertCacheMut.Lock()
		accountTypeRoleUpsertCache[key] = cache
		accountTypeRoleUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AccountTypeRole record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountTypeRole) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AccountTypeRole provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountTypeRolePrimaryKeyMapping)
	sql := "DELETE FROM \"account_type_role\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from account_type_role")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for account_type_role")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accountTypeRoleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no accountTypeRoleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from account_type_role")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for account_type_role")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountTypeRoleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(accountTypeRoleBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountTypeRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"account_type_role\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountTypeRolePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from accountTypeRole slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for account_type_role")
	}

	if len(accountTypeRoleAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountTypeRole) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccountTypeRole(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountTypeRoleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccountTypeRoleSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountTypeRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"account_type_role\".* FROM \"account_type_role\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountTypeRolePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AccountTypeRoleSlice")
	}

	*o = slice

	return nil
}

// AccountTypeRoleExists checks if the AccountTypeRole row exists.
func AccountTypeRoleExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"account_type_role\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if account_type_role exists")
	}

	return exists, nil
}

// Exists checks if the AccountTypeRole row exists.
func (o *AccountTypeRole) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccountTypeRoleExists(ctx, exec, o.ID)
}
