// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AccountType is an object representing the database table.
type AccountType struct {
	ID          string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name        string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`

	R *accountTypeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accountTypeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccountTypeColumns = struct {
	ID          string
	Name        string
	Description string
}{
	ID:          "id",
	Name:        "name",
	Description: "description",
}

var AccountTypeTableColumns = struct {
	ID          string
	Name        string
	Description string
}{
	ID:          "account_type.id",
	Name:        "account_type.name",
	Description: "account_type.description",
}

// Generated where

var AccountTypeWhere = struct {
	ID          whereHelperstring
	Name        whereHelperstring
	Description whereHelpernull_String
}{
	ID:          whereHelperstring{field: "\"account_type\".\"id\""},
	Name:        whereHelperstring{field: "\"account_type\".\"name\""},
	Description: whereHelpernull_String{field: "\"account_type\".\"description\""},
}

// AccountTypeRels is where relationship names are stored.
var AccountTypeRels = struct {
	Accounts         string
	AccountTypeRoles string
}{
	Accounts:         "Accounts",
	AccountTypeRoles: "AccountTypeRoles",
}

// accountTypeR is where relationships are stored.
type accountTypeR struct {
	Accounts         AccountSlice         `boil:"Accounts" json:"Accounts" toml:"Accounts" yaml:"Accounts"`
	AccountTypeRoles AccountTypeRoleSlice `boil:"AccountTypeRoles" json:"AccountTypeRoles" toml:"AccountTypeRoles" yaml:"AccountTypeRoles"`
}

// NewStruct creates a new relationship struct
func (*accountTypeR) NewStruct() *accountTypeR {
	return &accountTypeR{}
}

func (o *AccountType) GetAccounts() AccountSlice {
	if o == nil {
		return nil
	}

	return o.R.GetAccounts()
}

func (r *accountTypeR) GetAccounts() AccountSlice {
	if r == nil {
		return nil
	}

	return r.Accounts
}

func (o *AccountType) GetAccountTypeRoles() AccountTypeRoleSlice {
	if o == nil {
		return nil
	}

	return o.R.GetAccountTypeRoles()
}

func (r *accountTypeR) GetAccountTypeRoles() AccountTypeRoleSlice {
	if r == nil {
		return nil
	}

	return r.AccountTypeRoles
}

// accountTypeL is where Load methods for each relationship are stored.
type accountTypeL struct{}

var (
	accountTypeAllColumns            = []string{"id", "name", "description"}
	accountTypeColumnsWithoutDefault = []string{"name"}
	accountTypeColumnsWithDefault    = []string{"id", "description"}
	accountTypePrimaryKeyColumns     = []string{"id"}
	accountTypeGeneratedColumns      = []string{}
)

type (
	// AccountTypeSlice is an alias for a slice of pointers to AccountType.
	// This should almost always be used instead of []AccountType.
	AccountTypeSlice []*AccountType
	// AccountTypeHook is the signature for custom AccountType hook methods
	AccountTypeHook func(context.Context, boil.ContextExecutor, *AccountType) error

	accountTypeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accountTypeType                 = reflect.TypeOf(&AccountType{})
	accountTypeMapping              = queries.MakeStructMapping(accountTypeType)
	accountTypePrimaryKeyMapping, _ = queries.BindMapping(accountTypeType, accountTypeMapping, accountTypePrimaryKeyColumns)
	accountTypeInsertCacheMut       sync.RWMutex
	accountTypeInsertCache          = make(map[string]insertCache)
	accountTypeUpdateCacheMut       sync.RWMutex
	accountTypeUpdateCache          = make(map[string]updateCache)
	accountTypeUpsertCacheMut       sync.RWMutex
	accountTypeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var accountTypeAfterSelectMu sync.Mutex
var accountTypeAfterSelectHooks []AccountTypeHook

var accountTypeBeforeInsertMu sync.Mutex
var accountTypeBeforeInsertHooks []AccountTypeHook
var accountTypeAfterInsertMu sync.Mutex
var accountTypeAfterInsertHooks []AccountTypeHook

var accountTypeBeforeUpdateMu sync.Mutex
var accountTypeBeforeUpdateHooks []AccountTypeHook
var accountTypeAfterUpdateMu sync.Mutex
var accountTypeAfterUpdateHooks []AccountTypeHook

var accountTypeBeforeDeleteMu sync.Mutex
var accountTypeBeforeDeleteHooks []AccountTypeHook
var accountTypeAfterDeleteMu sync.Mutex
var accountTypeAfterDeleteHooks []AccountTypeHook

var accountTypeBeforeUpsertMu sync.Mutex
var accountTypeBeforeUpsertHooks []AccountTypeHook
var accountTypeAfterUpsertMu sync.Mutex
var accountTypeAfterUpsertHooks []AccountTypeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AccountType) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AccountType) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AccountType) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AccountType) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AccountType) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AccountType) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AccountType) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AccountType) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AccountType) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accountTypeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAccountTypeHook registers your hook function for all future operations.
func AddAccountTypeHook(hookPoint boil.HookPoint, accountTypeHook AccountTypeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		accountTypeAfterSelectMu.Lock()
		accountTypeAfterSelectHooks = append(accountTypeAfterSelectHooks, accountTypeHook)
		accountTypeAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		accountTypeBeforeInsertMu.Lock()
		accountTypeBeforeInsertHooks = append(accountTypeBeforeInsertHooks, accountTypeHook)
		accountTypeBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		accountTypeAfterInsertMu.Lock()
		accountTypeAfterInsertHooks = append(accountTypeAfterInsertHooks, accountTypeHook)
		accountTypeAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		accountTypeBeforeUpdateMu.Lock()
		accountTypeBeforeUpdateHooks = append(accountTypeBeforeUpdateHooks, accountTypeHook)
		accountTypeBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		accountTypeAfterUpdateMu.Lock()
		accountTypeAfterUpdateHooks = append(accountTypeAfterUpdateHooks, accountTypeHook)
		accountTypeAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		accountTypeBeforeDeleteMu.Lock()
		accountTypeBeforeDeleteHooks = append(accountTypeBeforeDeleteHooks, accountTypeHook)
		accountTypeBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		accountTypeAfterDeleteMu.Lock()
		accountTypeAfterDeleteHooks = append(accountTypeAfterDeleteHooks, accountTypeHook)
		accountTypeAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		accountTypeBeforeUpsertMu.Lock()
		accountTypeBeforeUpsertHooks = append(accountTypeBeforeUpsertHooks, accountTypeHook)
		accountTypeBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		accountTypeAfterUpsertMu.Lock()
		accountTypeAfterUpsertHooks = append(accountTypeAfterUpsertHooks, accountTypeHook)
		accountTypeAfterUpsertMu.Unlock()
	}
}

// One returns a single accountType record from the query.
func (q accountTypeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccountType, error) {
	o := &AccountType{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for account_type")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AccountType records from the query.
func (q accountTypeQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccountTypeSlice, error) {
	var o []*AccountType

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AccountType slice")
	}

	if len(accountTypeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AccountType records in the query.
func (q accountTypeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count account_type rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accountTypeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if account_type exists")
	}

	return count > 0, nil
}

// Accounts retrieves all the account's Accounts with an executor.
func (o *AccountType) Accounts(mods ...qm.QueryMod) accountQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"account\".\"account_type_id\"=?", o.ID),
	)

	return Accounts(queryMods...)
}

// AccountTypeRoles retrieves all the account_type_role's AccountTypeRoles with an executor.
func (o *AccountType) AccountTypeRoles(mods ...qm.QueryMod) accountTypeRoleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"account_type_role\".\"account_type_id\"=?", o.ID),
	)

	return AccountTypeRoles(queryMods...)
}

// LoadAccounts allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (accountTypeL) LoadAccounts(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccountType interface{}, mods queries.Applicator) error {
	var slice []*AccountType
	var object *AccountType

	if singular {
		var ok bool
		object, ok = maybeAccountType.(*AccountType)
		if !ok {
			object = new(AccountType)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccountType)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccountType))
			}
		}
	} else {
		s, ok := maybeAccountType.(*[]*AccountType)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccountType)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccountType))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &accountTypeR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accountTypeR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`account`),
		qm.WhereIn(`account.account_type_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load account")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on account")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for account")
	}

	if len(accountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Accounts = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &accountR{}
			}
			foreign.R.AccountType = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.AccountTypeID {
				local.R.Accounts = append(local.R.Accounts, foreign)
				if foreign.R == nil {
					foreign.R = &accountR{}
				}
				foreign.R.AccountType = local
				break
			}
		}
	}

	return nil
}

// LoadAccountTypeRoles allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (accountTypeL) LoadAccountTypeRoles(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccountType interface{}, mods queries.Applicator) error {
	var slice []*AccountType
	var object *AccountType

	if singular {
		var ok bool
		object, ok = maybeAccountType.(*AccountType)
		if !ok {
			object = new(AccountType)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccountType)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccountType))
			}
		}
	} else {
		s, ok := maybeAccountType.(*[]*AccountType)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccountType)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccountType))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &accountTypeR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accountTypeR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`account_type_role`),
		qm.WhereIn(`account_type_role.account_type_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load account_type_role")
	}

	var resultSlice []*AccountTypeRole
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice account_type_role")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on account_type_role")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for account_type_role")
	}

	if len(accountTypeRoleAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.AccountTypeRoles = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &accountTypeRoleR{}
			}
			foreign.R.AccountType = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.AccountTypeID) {
				local.R.AccountTypeRoles = append(local.R.AccountTypeRoles, foreign)
				if foreign.R == nil {
					foreign.R = &accountTypeRoleR{}
				}
				foreign.R.AccountType = local
				break
			}
		}
	}

	return nil
}

// AddAccounts adds the given related objects to the existing relationships
// of the account_type, optionally inserting them as new records.
// Appends related to o.R.Accounts.
// Sets related.R.AccountType appropriately.
func (o *AccountType) AddAccounts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Account) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.AccountTypeID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"account\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"account_type_id"}),
				strmangle.WhereClause("\"", "\"", 2, accountPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.AccountTypeID = o.ID
		}
	}

	if o.R == nil {
		o.R = &accountTypeR{
			Accounts: related,
		}
	} else {
		o.R.Accounts = append(o.R.Accounts, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &accountR{
				AccountType: o,
			}
		} else {
			rel.R.AccountType = o
		}
	}
	return nil
}

// AddAccountTypeRoles adds the given related objects to the existing relationships
// of the account_type, optionally inserting them as new records.
// Appends related to o.R.AccountTypeRoles.
// Sets related.R.AccountType appropriately.
func (o *AccountType) AddAccountTypeRoles(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*AccountTypeRole) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.AccountTypeID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"account_type_role\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"account_type_id"}),
				strmangle.WhereClause("\"", "\"", 2, accountTypeRolePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.AccountTypeID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &accountTypeR{
			AccountTypeRoles: related,
		}
	} else {
		o.R.AccountTypeRoles = append(o.R.AccountTypeRoles, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &accountTypeRoleR{
				AccountType: o,
			}
		} else {
			rel.R.AccountType = o
		}
	}
	return nil
}

// SetAccountTypeRoles removes all previously related items of the
// account_type replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.AccountType's AccountTypeRoles accordingly.
// Replaces o.R.AccountTypeRoles with related.
// Sets related.R.AccountType's AccountTypeRoles accordingly.
func (o *AccountType) SetAccountTypeRoles(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*AccountTypeRole) error {
	query := "update \"account_type_role\" set \"account_type_id\" = null where \"account_type_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.AccountTypeRoles {
			queries.SetScanner(&rel.AccountTypeID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.AccountType = nil
		}
		o.R.AccountTypeRoles = nil
	}

	return o.AddAccountTypeRoles(ctx, exec, insert, related...)
}

// RemoveAccountTypeRoles relationships from objects passed in.
// Removes related items from R.AccountTypeRoles (uses pointer comparison, removal does not keep order)
// Sets related.R.AccountType.
func (o *AccountType) RemoveAccountTypeRoles(ctx context.Context, exec boil.ContextExecutor, related ...*AccountTypeRole) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.AccountTypeID, nil)
		if rel.R != nil {
			rel.R.AccountType = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("account_type_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.AccountTypeRoles {
			if rel != ri {
				continue
			}

			ln := len(o.R.AccountTypeRoles)
			if ln > 1 && i < ln-1 {
				o.R.AccountTypeRoles[i] = o.R.AccountTypeRoles[ln-1]
			}
			o.R.AccountTypeRoles = o.R.AccountTypeRoles[:ln-1]
			break
		}
	}

	return nil
}

// AccountTypes retrieves all the records using an executor.
func AccountTypes(mods ...qm.QueryMod) accountTypeQuery {
	mods = append(mods, qm.From("\"account_type\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"account_type\".*"})
	}

	return accountTypeQuery{q}
}

// FindAccountType retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccountType(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*AccountType, error) {
	accountTypeObj := &AccountType{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"account_type\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, accountTypeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from account_type")
	}

	if err = accountTypeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return accountTypeObj, err
	}

	return accountTypeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccountType) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no account_type provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountTypeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accountTypeInsertCacheMut.RLock()
	cache, cached := accountTypeInsertCache[key]
	accountTypeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accountTypeAllColumns,
			accountTypeColumnsWithDefault,
			accountTypeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accountTypeType, accountTypeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accountTypeType, accountTypeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"account_type\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"account_type\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into account_type")
	}

	if !cached {
		accountTypeInsertCacheMut.Lock()
		accountTypeInsertCache[key] = cache
		accountTypeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AccountType.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccountType) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	accountTypeUpdateCacheMut.RLock()
	cache, cached := accountTypeUpdateCache[key]
	accountTypeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accountTypeAllColumns,
			accountTypePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update account_type, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"account_type\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, accountTypePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accountTypeType, accountTypeMapping, append(wl, accountTypePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update account_type row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for account_type")
	}

	if !cached {
		accountTypeUpdateCacheMut.Lock()
		accountTypeUpdateCache[key] = cache
		accountTypeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q accountTypeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for account_type")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for account_type")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccountTypeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"account_type\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accountTypePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in accountType slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all accountType")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AccountType) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no account_type provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accountTypeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accountTypeUpsertCacheMut.RLock()
	cache, cached := accountTypeUpsertCache[key]
	accountTypeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			accountTypeAllColumns,
			accountTypeColumnsWithDefault,
			accountTypeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			accountTypeAllColumns,
			accountTypePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert account_type, could not build update column list")
		}

		ret := strmangle.SetComplement(accountTypeAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(accountTypePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert account_type, could not build conflict column list")
			}

			conflict = make([]string, len(accountTypePrimaryKeyColumns))
			copy(conflict, accountTypePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"account_type\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(accountTypeType, accountTypeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accountTypeType, accountTypeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert account_type")
	}

	if !cached {
		accountTypeUpsertCacheMut.Lock()
		accountTypeUpsertCache[key] = cache
		accountTypeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AccountType record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccountType) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no AccountType provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accountTypePrimaryKeyMapping)
	sql := "DELETE FROM \"account_type\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from account_type")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for account_type")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accountTypeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no accountTypeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from account_type")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for account_type")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccountTypeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(accountTypeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"account_type\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountTypePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from accountType slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for account_type")
	}

	if len(accountTypeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccountType) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccountType(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccountTypeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccountTypeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accountTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"account_type\".* FROM \"account_type\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accountTypePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AccountTypeSlice")
	}

	*o = slice

	return nil
}

// AccountTypeExists checks if the AccountType row exists.
func AccountTypeExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"account_type\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if account_type exists")
	}

	return exists, nil
}

// Exists checks if the AccountType row exists.
func (o *AccountType) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccountTypeExists(ctx, exec, o.ID)
}
