// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Products", testProducts)
	t.Run("Projects", testProjects)
}

func TestDelete(t *testing.T) {
	t.Run("Products", testProductsDelete)
	t.Run("Projects", testProjectsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Products", testProductsQueryDeleteAll)
	t.Run("Projects", testProjectsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Products", testProductsSliceDeleteAll)
	t.Run("Projects", testProjectsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Products", testProductsExists)
	t.Run("Projects", testProjectsExists)
}

func TestFind(t *testing.T) {
	t.Run("Products", testProductsFind)
	t.Run("Projects", testProjectsFind)
}

func TestBind(t *testing.T) {
	t.Run("Products", testProductsBind)
	t.Run("Projects", testProjectsBind)
}

func TestOne(t *testing.T) {
	t.Run("Products", testProductsOne)
	t.Run("Projects", testProjectsOne)
}

func TestAll(t *testing.T) {
	t.Run("Products", testProductsAll)
	t.Run("Projects", testProjectsAll)
}

func TestCount(t *testing.T) {
	t.Run("Products", testProductsCount)
	t.Run("Projects", testProjectsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Products", testProductsHooks)
	t.Run("Projects", testProjectsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Products", testProductsInsert)
	t.Run("Products", testProductsInsertWhitelist)
	t.Run("Projects", testProjectsInsert)
	t.Run("Projects", testProjectsInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("Products", testProductsReload)
	t.Run("Projects", testProjectsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Products", testProductsReloadAll)
	t.Run("Projects", testProjectsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Products", testProductsSelect)
	t.Run("Projects", testProjectsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Products", testProductsUpdate)
	t.Run("Projects", testProjectsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Products", testProductsSliceUpdateAll)
	t.Run("Projects", testProjectsSliceUpdateAll)
}
