// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Bundle is an object representing the database table.
type Bundle struct {
	ID                        string           `boil:"id" json:"id" toml:"id" yaml:"id"`
	Version                   string           `boil:"version" json:"version" toml:"version" yaml:"version"`
	VersionArray              types.Int64Array `boil:"version_array" json:"version_array,omitempty" toml:"version_array" yaml:"version_array,omitempty"`
	Prerelease                null.String      `boil:"prerelease" json:"prerelease,omitempty" toml:"prerelease" yaml:"prerelease,omitempty"`
	PrereleaseTag             null.String      `boil:"prerelease_tag" json:"prerelease_tag,omitempty" toml:"prerelease_tag" yaml:"prerelease_tag,omitempty"`
	PrereleaseNum             null.Int         `boil:"prerelease_num" json:"prerelease_num,omitempty" toml:"prerelease_num" yaml:"prerelease_num,omitempty"`
	ReleaseNotes              null.String      `boil:"release_notes" json:"release_notes,omitempty" toml:"release_notes" yaml:"release_notes,omitempty"`
	MinPrevVersion            string           `boil:"min_prev_version" json:"min_prev_version" toml:"min_prev_version" yaml:"min_prev_version"`
	MinPrevVersionArray       types.Int64Array `boil:"min_prev_version_array" json:"min_prev_version_array,omitempty" toml:"min_prev_version_array" yaml:"min_prev_version_array,omitempty"`
	MinDesktopAppVersion      string           `boil:"min_desktop_app_version" json:"min_desktop_app_version" toml:"min_desktop_app_version" yaml:"min_desktop_app_version"`
	MinDesktopAppVersionArray types.Int64Array `boil:"min_desktop_app_version_array" json:"min_desktop_app_version_array,omitempty" toml:"min_desktop_app_version_array" yaml:"min_desktop_app_version_array,omitempty"`
	ManifestData              null.JSON        `boil:"manifest_data" json:"manifest_data,omitempty" toml:"manifest_data" yaml:"manifest_data,omitempty"`
	Checksum                  string           `boil:"checksum" json:"checksum" toml:"checksum" yaml:"checksum"`
	S3Path                    string           `boil:"s3_path" json:"s3_path" toml:"s3_path" yaml:"s3_path"`
	ApprovalStatus            string           `boil:"approval_status" json:"approval_status" toml:"approval_status" yaml:"approval_status"`
	ApprovalStatusChangedBy   null.String      `boil:"approval_status_changed_by" json:"approval_status_changed_by,omitempty" toml:"approval_status_changed_by" yaml:"approval_status_changed_by,omitempty"`
	ApprovalStatusChangedAt   null.Time        `boil:"approval_status_changed_at" json:"approval_status_changed_at,omitempty" toml:"approval_status_changed_at" yaml:"approval_status_changed_at,omitempty"`
	CreatedAt                 time.Time        `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt                 time.Time        `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *bundleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L bundleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BundleColumns = struct {
	ID                        string
	Version                   string
	VersionArray              string
	Prerelease                string
	PrereleaseTag             string
	PrereleaseNum             string
	ReleaseNotes              string
	MinPrevVersion            string
	MinPrevVersionArray       string
	MinDesktopAppVersion      string
	MinDesktopAppVersionArray string
	ManifestData              string
	Checksum                  string
	S3Path                    string
	ApprovalStatus            string
	ApprovalStatusChangedBy   string
	ApprovalStatusChangedAt   string
	CreatedAt                 string
	UpdatedAt                 string
}{
	ID:                        "id",
	Version:                   "version",
	VersionArray:              "version_array",
	Prerelease:                "prerelease",
	PrereleaseTag:             "prerelease_tag",
	PrereleaseNum:             "prerelease_num",
	ReleaseNotes:              "release_notes",
	MinPrevVersion:            "min_prev_version",
	MinPrevVersionArray:       "min_prev_version_array",
	MinDesktopAppVersion:      "min_desktop_app_version",
	MinDesktopAppVersionArray: "min_desktop_app_version_array",
	ManifestData:              "manifest_data",
	Checksum:                  "checksum",
	S3Path:                    "s3_path",
	ApprovalStatus:            "approval_status",
	ApprovalStatusChangedBy:   "approval_status_changed_by",
	ApprovalStatusChangedAt:   "approval_status_changed_at",
	CreatedAt:                 "created_at",
	UpdatedAt:                 "updated_at",
}

var BundleTableColumns = struct {
	ID                        string
	Version                   string
	VersionArray              string
	Prerelease                string
	PrereleaseTag             string
	PrereleaseNum             string
	ReleaseNotes              string
	MinPrevVersion            string
	MinPrevVersionArray       string
	MinDesktopAppVersion      string
	MinDesktopAppVersionArray string
	ManifestData              string
	Checksum                  string
	S3Path                    string
	ApprovalStatus            string
	ApprovalStatusChangedBy   string
	ApprovalStatusChangedAt   string
	CreatedAt                 string
	UpdatedAt                 string
}{
	ID:                        "bundle.id",
	Version:                   "bundle.version",
	VersionArray:              "bundle.version_array",
	Prerelease:                "bundle.prerelease",
	PrereleaseTag:             "bundle.prerelease_tag",
	PrereleaseNum:             "bundle.prerelease_num",
	ReleaseNotes:              "bundle.release_notes",
	MinPrevVersion:            "bundle.min_prev_version",
	MinPrevVersionArray:       "bundle.min_prev_version_array",
	MinDesktopAppVersion:      "bundle.min_desktop_app_version",
	MinDesktopAppVersionArray: "bundle.min_desktop_app_version_array",
	ManifestData:              "bundle.manifest_data",
	Checksum:                  "bundle.checksum",
	S3Path:                    "bundle.s3_path",
	ApprovalStatus:            "bundle.approval_status",
	ApprovalStatusChangedBy:   "bundle.approval_status_changed_by",
	ApprovalStatusChangedAt:   "bundle.approval_status_changed_at",
	CreatedAt:                 "bundle.created_at",
	UpdatedAt:                 "bundle.updated_at",
}

// Generated where

type whereHelpertypes_Int64Array struct{ field string }

func (w whereHelpertypes_Int64Array) EQ(x types.Int64Array) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpertypes_Int64Array) NEQ(x types.Int64Array) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpertypes_Int64Array) LT(x types.Int64Array) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_Int64Array) LTE(x types.Int64Array) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_Int64Array) GT(x types.Int64Array) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_Int64Array) GTE(x types.Int64Array) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpertypes_Int64Array) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpertypes_Int64Array) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_JSON struct{ field string }

func (w whereHelpernull_JSON) EQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_JSON) NEQ(x null.JSON) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_JSON) LT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_JSON) LTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_JSON) GT(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_JSON) GTE(x null.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_JSON) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_JSON) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var BundleWhere = struct {
	ID                        whereHelperstring
	Version                   whereHelperstring
	VersionArray              whereHelpertypes_Int64Array
	Prerelease                whereHelpernull_String
	PrereleaseTag             whereHelpernull_String
	PrereleaseNum             whereHelpernull_Int
	ReleaseNotes              whereHelpernull_String
	MinPrevVersion            whereHelperstring
	MinPrevVersionArray       whereHelpertypes_Int64Array
	MinDesktopAppVersion      whereHelperstring
	MinDesktopAppVersionArray whereHelpertypes_Int64Array
	ManifestData              whereHelpernull_JSON
	Checksum                  whereHelperstring
	S3Path                    whereHelperstring
	ApprovalStatus            whereHelperstring
	ApprovalStatusChangedBy   whereHelpernull_String
	ApprovalStatusChangedAt   whereHelpernull_Time
	CreatedAt                 whereHelpertime_Time
	UpdatedAt                 whereHelpertime_Time
}{
	ID:                        whereHelperstring{field: "\"bundle\".\"id\""},
	Version:                   whereHelperstring{field: "\"bundle\".\"version\""},
	VersionArray:              whereHelpertypes_Int64Array{field: "\"bundle\".\"version_array\""},
	Prerelease:                whereHelpernull_String{field: "\"bundle\".\"prerelease\""},
	PrereleaseTag:             whereHelpernull_String{field: "\"bundle\".\"prerelease_tag\""},
	PrereleaseNum:             whereHelpernull_Int{field: "\"bundle\".\"prerelease_num\""},
	ReleaseNotes:              whereHelpernull_String{field: "\"bundle\".\"release_notes\""},
	MinPrevVersion:            whereHelperstring{field: "\"bundle\".\"min_prev_version\""},
	MinPrevVersionArray:       whereHelpertypes_Int64Array{field: "\"bundle\".\"min_prev_version_array\""},
	MinDesktopAppVersion:      whereHelperstring{field: "\"bundle\".\"min_desktop_app_version\""},
	MinDesktopAppVersionArray: whereHelpertypes_Int64Array{field: "\"bundle\".\"min_desktop_app_version_array\""},
	ManifestData:              whereHelpernull_JSON{field: "\"bundle\".\"manifest_data\""},
	Checksum:                  whereHelperstring{field: "\"bundle\".\"checksum\""},
	S3Path:                    whereHelperstring{field: "\"bundle\".\"s3_path\""},
	ApprovalStatus:            whereHelperstring{field: "\"bundle\".\"approval_status\""},
	ApprovalStatusChangedBy:   whereHelpernull_String{field: "\"bundle\".\"approval_status_changed_by\""},
	ApprovalStatusChangedAt:   whereHelpernull_Time{field: "\"bundle\".\"approval_status_changed_at\""},
	CreatedAt:                 whereHelpertime_Time{field: "\"bundle\".\"created_at\""},
	UpdatedAt:                 whereHelpertime_Time{field: "\"bundle\".\"updated_at\""},
}

// BundleRels is where relationship names are stored.
var BundleRels = struct {
	ApprovalStatusChangedByAppUser string
}{
	ApprovalStatusChangedByAppUser: "ApprovalStatusChangedByAppUser",
}

// bundleR is where relationships are stored.
type bundleR struct {
	ApprovalStatusChangedByAppUser *AppUser `boil:"ApprovalStatusChangedByAppUser" json:"ApprovalStatusChangedByAppUser" toml:"ApprovalStatusChangedByAppUser" yaml:"ApprovalStatusChangedByAppUser"`
}

// NewStruct creates a new relationship struct
func (*bundleR) NewStruct() *bundleR {
	return &bundleR{}
}

func (o *Bundle) GetApprovalStatusChangedByAppUser() *AppUser {
	if o == nil {
		return nil
	}

	return o.R.GetApprovalStatusChangedByAppUser()
}

func (r *bundleR) GetApprovalStatusChangedByAppUser() *AppUser {
	if r == nil {
		return nil
	}

	return r.ApprovalStatusChangedByAppUser
}

// bundleL is where Load methods for each relationship are stored.
type bundleL struct{}

var (
	bundleAllColumns            = []string{"id", "version", "version_array", "prerelease", "prerelease_tag", "prerelease_num", "release_notes", "min_prev_version", "min_prev_version_array", "min_desktop_app_version", "min_desktop_app_version_array", "manifest_data", "checksum", "s3_path", "approval_status", "approval_status_changed_by", "approval_status_changed_at", "created_at", "updated_at"}
	bundleColumnsWithoutDefault = []string{"version", "min_prev_version", "min_desktop_app_version", "checksum", "s3_path"}
	bundleColumnsWithDefault    = []string{"id", "version_array", "prerelease", "prerelease_tag", "prerelease_num", "release_notes", "min_prev_version_array", "min_desktop_app_version_array", "manifest_data", "approval_status", "approval_status_changed_by", "approval_status_changed_at", "created_at", "updated_at"}
	bundlePrimaryKeyColumns     = []string{"id"}
	bundleGeneratedColumns      = []string{"version_array", "min_prev_version_array", "min_desktop_app_version_array"}
)

type (
	// BundleSlice is an alias for a slice of pointers to Bundle.
	// This should almost always be used instead of []Bundle.
	BundleSlice []*Bundle
	// BundleHook is the signature for custom Bundle hook methods
	BundleHook func(context.Context, boil.ContextExecutor, *Bundle) error

	bundleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	bundleType                 = reflect.TypeOf(&Bundle{})
	bundleMapping              = queries.MakeStructMapping(bundleType)
	bundlePrimaryKeyMapping, _ = queries.BindMapping(bundleType, bundleMapping, bundlePrimaryKeyColumns)
	bundleInsertCacheMut       sync.RWMutex
	bundleInsertCache          = make(map[string]insertCache)
	bundleUpdateCacheMut       sync.RWMutex
	bundleUpdateCache          = make(map[string]updateCache)
	bundleUpsertCacheMut       sync.RWMutex
	bundleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var bundleAfterSelectMu sync.Mutex
var bundleAfterSelectHooks []BundleHook

var bundleBeforeInsertMu sync.Mutex
var bundleBeforeInsertHooks []BundleHook
var bundleAfterInsertMu sync.Mutex
var bundleAfterInsertHooks []BundleHook

var bundleBeforeUpdateMu sync.Mutex
var bundleBeforeUpdateHooks []BundleHook
var bundleAfterUpdateMu sync.Mutex
var bundleAfterUpdateHooks []BundleHook

var bundleBeforeDeleteMu sync.Mutex
var bundleBeforeDeleteHooks []BundleHook
var bundleAfterDeleteMu sync.Mutex
var bundleAfterDeleteHooks []BundleHook

var bundleBeforeUpsertMu sync.Mutex
var bundleBeforeUpsertHooks []BundleHook
var bundleAfterUpsertMu sync.Mutex
var bundleAfterUpsertHooks []BundleHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Bundle) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bundleAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Bundle) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bundleBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Bundle) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bundleAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Bundle) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bundleBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Bundle) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bundleAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Bundle) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bundleBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Bundle) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bundleAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Bundle) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bundleBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Bundle) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bundleAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBundleHook registers your hook function for all future operations.
func AddBundleHook(hookPoint boil.HookPoint, bundleHook BundleHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		bundleAfterSelectMu.Lock()
		bundleAfterSelectHooks = append(bundleAfterSelectHooks, bundleHook)
		bundleAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		bundleBeforeInsertMu.Lock()
		bundleBeforeInsertHooks = append(bundleBeforeInsertHooks, bundleHook)
		bundleBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		bundleAfterInsertMu.Lock()
		bundleAfterInsertHooks = append(bundleAfterInsertHooks, bundleHook)
		bundleAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		bundleBeforeUpdateMu.Lock()
		bundleBeforeUpdateHooks = append(bundleBeforeUpdateHooks, bundleHook)
		bundleBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		bundleAfterUpdateMu.Lock()
		bundleAfterUpdateHooks = append(bundleAfterUpdateHooks, bundleHook)
		bundleAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		bundleBeforeDeleteMu.Lock()
		bundleBeforeDeleteHooks = append(bundleBeforeDeleteHooks, bundleHook)
		bundleBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		bundleAfterDeleteMu.Lock()
		bundleAfterDeleteHooks = append(bundleAfterDeleteHooks, bundleHook)
		bundleAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		bundleBeforeUpsertMu.Lock()
		bundleBeforeUpsertHooks = append(bundleBeforeUpsertHooks, bundleHook)
		bundleBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		bundleAfterUpsertMu.Lock()
		bundleAfterUpsertHooks = append(bundleAfterUpsertHooks, bundleHook)
		bundleAfterUpsertMu.Unlock()
	}
}

// One returns a single bundle record from the query.
func (q bundleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Bundle, error) {
	o := &Bundle{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for bundle")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Bundle records from the query.
func (q bundleQuery) All(ctx context.Context, exec boil.ContextExecutor) (BundleSlice, error) {
	var o []*Bundle

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Bundle slice")
	}

	if len(bundleAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Bundle records in the query.
func (q bundleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count bundle rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q bundleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if bundle exists")
	}

	return count > 0, nil
}

// ApprovalStatusChangedByAppUser pointed to by the foreign key.
func (o *Bundle) ApprovalStatusChangedByAppUser(mods ...qm.QueryMod) appUserQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ApprovalStatusChangedBy),
	}

	queryMods = append(queryMods, mods...)

	return AppUsers(queryMods...)
}

// LoadApprovalStatusChangedByAppUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (bundleL) LoadApprovalStatusChangedByAppUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBundle interface{}, mods queries.Applicator) error {
	var slice []*Bundle
	var object *Bundle

	if singular {
		var ok bool
		object, ok = maybeBundle.(*Bundle)
		if !ok {
			object = new(Bundle)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBundle)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBundle))
			}
		}
	} else {
		s, ok := maybeBundle.(*[]*Bundle)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBundle)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBundle))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &bundleR{}
		}
		if !queries.IsNil(object.ApprovalStatusChangedBy) {
			args[object.ApprovalStatusChangedBy] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &bundleR{}
			}

			if !queries.IsNil(obj.ApprovalStatusChangedBy) {
				args[obj.ApprovalStatusChangedBy] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`app_user`),
		qm.WhereIn(`app_user.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AppUser")
	}

	var resultSlice []*AppUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AppUser")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for app_user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for app_user")
	}

	if len(appUserAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ApprovalStatusChangedByAppUser = foreign
		if foreign.R == nil {
			foreign.R = &appUserR{}
		}
		foreign.R.ApprovalStatusChangedByBundles = append(foreign.R.ApprovalStatusChangedByBundles, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ApprovalStatusChangedBy, foreign.ID) {
				local.R.ApprovalStatusChangedByAppUser = foreign
				if foreign.R == nil {
					foreign.R = &appUserR{}
				}
				foreign.R.ApprovalStatusChangedByBundles = append(foreign.R.ApprovalStatusChangedByBundles, local)
				break
			}
		}
	}

	return nil
}

// SetApprovalStatusChangedByAppUser of the bundle to the related item.
// Sets o.R.ApprovalStatusChangedByAppUser to related.
// Adds o to related.R.ApprovalStatusChangedByBundles.
func (o *Bundle) SetApprovalStatusChangedByAppUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *AppUser) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"bundle\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"approval_status_changed_by"}),
		strmangle.WhereClause("\"", "\"", 2, bundlePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ApprovalStatusChangedBy, related.ID)
	if o.R == nil {
		o.R = &bundleR{
			ApprovalStatusChangedByAppUser: related,
		}
	} else {
		o.R.ApprovalStatusChangedByAppUser = related
	}

	if related.R == nil {
		related.R = &appUserR{
			ApprovalStatusChangedByBundles: BundleSlice{o},
		}
	} else {
		related.R.ApprovalStatusChangedByBundles = append(related.R.ApprovalStatusChangedByBundles, o)
	}

	return nil
}

// RemoveApprovalStatusChangedByAppUser relationship.
// Sets o.R.ApprovalStatusChangedByAppUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Bundle) RemoveApprovalStatusChangedByAppUser(ctx context.Context, exec boil.ContextExecutor, related *AppUser) error {
	var err error

	queries.SetScanner(&o.ApprovalStatusChangedBy, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("approval_status_changed_by")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.ApprovalStatusChangedByAppUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ApprovalStatusChangedByBundles {
		if queries.Equal(o.ApprovalStatusChangedBy, ri.ApprovalStatusChangedBy) {
			continue
		}

		ln := len(related.R.ApprovalStatusChangedByBundles)
		if ln > 1 && i < ln-1 {
			related.R.ApprovalStatusChangedByBundles[i] = related.R.ApprovalStatusChangedByBundles[ln-1]
		}
		related.R.ApprovalStatusChangedByBundles = related.R.ApprovalStatusChangedByBundles[:ln-1]
		break
	}
	return nil
}

// Bundles retrieves all the records using an executor.
func Bundles(mods ...qm.QueryMod) bundleQuery {
	mods = append(mods, qm.From("\"bundle\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"bundle\".*"})
	}

	return bundleQuery{q}
}

// FindBundle retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBundle(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Bundle, error) {
	bundleObj := &Bundle{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"bundle\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, bundleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from bundle")
	}

	if err = bundleObj.doAfterSelectHooks(ctx, exec); err != nil {
		return bundleObj, err
	}

	return bundleObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Bundle) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no bundle provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bundleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	bundleInsertCacheMut.RLock()
	cache, cached := bundleInsertCache[key]
	bundleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			bundleAllColumns,
			bundleColumnsWithDefault,
			bundleColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, bundleGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(bundleType, bundleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(bundleType, bundleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"bundle\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"bundle\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into bundle")
	}

	if !cached {
		bundleInsertCacheMut.Lock()
		bundleInsertCache[key] = cache
		bundleInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Bundle.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Bundle) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	bundleUpdateCacheMut.RLock()
	cache, cached := bundleUpdateCache[key]
	bundleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			bundleAllColumns,
			bundlePrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, bundleGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update bundle, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"bundle\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, bundlePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(bundleType, bundleMapping, append(wl, bundlePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update bundle row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for bundle")
	}

	if !cached {
		bundleUpdateCacheMut.Lock()
		bundleUpdateCache[key] = cache
		bundleUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q bundleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for bundle")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for bundle")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BundleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bundlePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"bundle\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, bundlePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in bundle slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all bundle")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Bundle) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no bundle provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bundleColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	bundleUpsertCacheMut.RLock()
	cache, cached := bundleUpsertCache[key]
	bundleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			bundleAllColumns,
			bundleColumnsWithDefault,
			bundleColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			bundleAllColumns,
			bundlePrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, bundleGeneratedColumns)
		update = strmangle.SetComplement(update, bundleGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert bundle, could not build update column list")
		}

		ret := strmangle.SetComplement(bundleAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(bundlePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert bundle, could not build conflict column list")
			}

			conflict = make([]string, len(bundlePrimaryKeyColumns))
			copy(conflict, bundlePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"bundle\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(bundleType, bundleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(bundleType, bundleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert bundle")
	}

	if !cached {
		bundleUpsertCacheMut.Lock()
		bundleUpsertCache[key] = cache
		bundleUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Bundle record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Bundle) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Bundle provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), bundlePrimaryKeyMapping)
	sql := "DELETE FROM \"bundle\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from bundle")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for bundle")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q bundleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no bundleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from bundle")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bundle")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BundleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(bundleBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bundlePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"bundle\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bundlePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from bundle slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for bundle")
	}

	if len(bundleAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Bundle) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBundle(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BundleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BundleSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bundlePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"bundle\".* FROM \"bundle\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bundlePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BundleSlice")
	}

	*o = slice

	return nil
}

// BundleExists checks if the Bundle row exists.
func BundleExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"bundle\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if bundle exists")
	}

	return exists, nil
}

// Exists checks if the Bundle row exists.
func (o *Bundle) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BundleExists(ctx, exec, o.ID)
}
