// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testProductSyncJobs(t *testing.T) {
	t.Parallel()

	query := ProductSyncJobs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testProductSyncJobsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ProductSyncJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProductSyncJobsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ProductSyncJobs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ProductSyncJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProductSyncJobsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ProductSyncJobSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ProductSyncJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProductSyncJobsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ProductSyncJobExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ProductSyncJob exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ProductSyncJobExists to return true, but got false.")
	}
}

func testProductSyncJobsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	productSyncJobFound, err := FindProductSyncJob(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if productSyncJobFound == nil {
		t.Error("want a record, got nil")
	}
}

func testProductSyncJobsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ProductSyncJobs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testProductSyncJobsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ProductSyncJobs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testProductSyncJobsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	productSyncJobOne := &ProductSyncJob{}
	productSyncJobTwo := &ProductSyncJob{}
	if err = randomize.Struct(seed, productSyncJobOne, productSyncJobDBTypes, false, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}
	if err = randomize.Struct(seed, productSyncJobTwo, productSyncJobDBTypes, false, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = productSyncJobOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = productSyncJobTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ProductSyncJobs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testProductSyncJobsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	productSyncJobOne := &ProductSyncJob{}
	productSyncJobTwo := &ProductSyncJob{}
	if err = randomize.Struct(seed, productSyncJobOne, productSyncJobDBTypes, false, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}
	if err = randomize.Struct(seed, productSyncJobTwo, productSyncJobDBTypes, false, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = productSyncJobOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = productSyncJobTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductSyncJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func productSyncJobBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductSyncJob) error {
	*o = ProductSyncJob{}
	return nil
}

func productSyncJobAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductSyncJob) error {
	*o = ProductSyncJob{}
	return nil
}

func productSyncJobAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ProductSyncJob) error {
	*o = ProductSyncJob{}
	return nil
}

func productSyncJobBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ProductSyncJob) error {
	*o = ProductSyncJob{}
	return nil
}

func productSyncJobAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ProductSyncJob) error {
	*o = ProductSyncJob{}
	return nil
}

func productSyncJobBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ProductSyncJob) error {
	*o = ProductSyncJob{}
	return nil
}

func productSyncJobAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ProductSyncJob) error {
	*o = ProductSyncJob{}
	return nil
}

func productSyncJobBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductSyncJob) error {
	*o = ProductSyncJob{}
	return nil
}

func productSyncJobAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductSyncJob) error {
	*o = ProductSyncJob{}
	return nil
}

func testProductSyncJobsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ProductSyncJob{}
	o := &ProductSyncJob{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob object: %s", err)
	}

	AddProductSyncJobHook(boil.BeforeInsertHook, productSyncJobBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	productSyncJobBeforeInsertHooks = []ProductSyncJobHook{}

	AddProductSyncJobHook(boil.AfterInsertHook, productSyncJobAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	productSyncJobAfterInsertHooks = []ProductSyncJobHook{}

	AddProductSyncJobHook(boil.AfterSelectHook, productSyncJobAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	productSyncJobAfterSelectHooks = []ProductSyncJobHook{}

	AddProductSyncJobHook(boil.BeforeUpdateHook, productSyncJobBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	productSyncJobBeforeUpdateHooks = []ProductSyncJobHook{}

	AddProductSyncJobHook(boil.AfterUpdateHook, productSyncJobAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	productSyncJobAfterUpdateHooks = []ProductSyncJobHook{}

	AddProductSyncJobHook(boil.BeforeDeleteHook, productSyncJobBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	productSyncJobBeforeDeleteHooks = []ProductSyncJobHook{}

	AddProductSyncJobHook(boil.AfterDeleteHook, productSyncJobAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	productSyncJobAfterDeleteHooks = []ProductSyncJobHook{}

	AddProductSyncJobHook(boil.BeforeUpsertHook, productSyncJobBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	productSyncJobBeforeUpsertHooks = []ProductSyncJobHook{}

	AddProductSyncJobHook(boil.AfterUpsertHook, productSyncJobAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	productSyncJobAfterUpsertHooks = []ProductSyncJobHook{}
}

func testProductSyncJobsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductSyncJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testProductSyncJobsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(productSyncJobPrimaryKeyColumns, productSyncJobColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := ProductSyncJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testProductSyncJobsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testProductSyncJobsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ProductSyncJobSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testProductSyncJobsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ProductSyncJobs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	productSyncJobDBTypes = map[string]string{`ID`: `integer`, `JobID`: `uuid`, `SyncOperation`: `enum.sync_operation_enum('full_sync','manual_sync','scheduled_sync')`, `Status`: `enum.sync_status_enum('pending','in_progress','completed','failed')`, `S3Bucket`: `character varying`, `S3Key`: `character varying`, `FileSizeBytes`: `bigint`, `ErrorMessage`: `text`, `ValidationErrors`: `jsonb`, `TotalItems`: `integer`, `SuccessfulItems`: `integer`, `FailedItems`: `integer`, `StartedAt`: `timestamp without time zone`, `CompletedAt`: `timestamp without time zone`, `CreatedAt`: `timestamp without time zone`}
	_                     = bytes.MinRead
)

func testProductSyncJobsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(productSyncJobPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(productSyncJobAllColumns) == len(productSyncJobPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductSyncJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testProductSyncJobsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(productSyncJobAllColumns) == len(productSyncJobPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ProductSyncJob{}
	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductSyncJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, productSyncJobDBTypes, true, productSyncJobPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(productSyncJobAllColumns, productSyncJobPrimaryKeyColumns) {
		fields = productSyncJobAllColumns
	} else {
		fields = strmangle.SetComplement(
			productSyncJobAllColumns,
			productSyncJobPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ProductSyncJobSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testProductSyncJobsUpsert(t *testing.T) {
	t.Parallel()

	if len(productSyncJobAllColumns) == len(productSyncJobPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ProductSyncJob{}
	if err = randomize.Struct(seed, &o, productSyncJobDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ProductSyncJob: %s", err)
	}

	count, err := ProductSyncJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, productSyncJobDBTypes, false, productSyncJobPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ProductSyncJob struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ProductSyncJob: %s", err)
	}

	count, err = ProductSyncJobs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
