// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testProductPrices(t *testing.T) {
	t.Parallel()

	query := ProductPrices()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testProductPricesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ProductPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProductPricesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ProductPrices().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ProductPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProductPricesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ProductPriceSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ProductPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testProductPricesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ProductPriceExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ProductPrice exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ProductPriceExists to return true, but got false.")
	}
}

func testProductPricesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	productPriceFound, err := FindProductPrice(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if productPriceFound == nil {
		t.Error("want a record, got nil")
	}
}

func testProductPricesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ProductPrices().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testProductPricesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ProductPrices().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testProductPricesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	productPriceOne := &ProductPrice{}
	productPriceTwo := &ProductPrice{}
	if err = randomize.Struct(seed, productPriceOne, productPriceDBTypes, false, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}
	if err = randomize.Struct(seed, productPriceTwo, productPriceDBTypes, false, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = productPriceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = productPriceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ProductPrices().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testProductPricesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	productPriceOne := &ProductPrice{}
	productPriceTwo := &ProductPrice{}
	if err = randomize.Struct(seed, productPriceOne, productPriceDBTypes, false, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}
	if err = randomize.Struct(seed, productPriceTwo, productPriceDBTypes, false, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = productPriceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = productPriceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func productPriceBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductPrice) error {
	*o = ProductPrice{}
	return nil
}

func productPriceAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductPrice) error {
	*o = ProductPrice{}
	return nil
}

func productPriceAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ProductPrice) error {
	*o = ProductPrice{}
	return nil
}

func productPriceBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ProductPrice) error {
	*o = ProductPrice{}
	return nil
}

func productPriceAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ProductPrice) error {
	*o = ProductPrice{}
	return nil
}

func productPriceBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ProductPrice) error {
	*o = ProductPrice{}
	return nil
}

func productPriceAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ProductPrice) error {
	*o = ProductPrice{}
	return nil
}

func productPriceBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductPrice) error {
	*o = ProductPrice{}
	return nil
}

func productPriceAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ProductPrice) error {
	*o = ProductPrice{}
	return nil
}

func testProductPricesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ProductPrice{}
	o := &ProductPrice{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, productPriceDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ProductPrice object: %s", err)
	}

	AddProductPriceHook(boil.BeforeInsertHook, productPriceBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	productPriceBeforeInsertHooks = []ProductPriceHook{}

	AddProductPriceHook(boil.AfterInsertHook, productPriceAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	productPriceAfterInsertHooks = []ProductPriceHook{}

	AddProductPriceHook(boil.AfterSelectHook, productPriceAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	productPriceAfterSelectHooks = []ProductPriceHook{}

	AddProductPriceHook(boil.BeforeUpdateHook, productPriceBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	productPriceBeforeUpdateHooks = []ProductPriceHook{}

	AddProductPriceHook(boil.AfterUpdateHook, productPriceAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	productPriceAfterUpdateHooks = []ProductPriceHook{}

	AddProductPriceHook(boil.BeforeDeleteHook, productPriceBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	productPriceBeforeDeleteHooks = []ProductPriceHook{}

	AddProductPriceHook(boil.AfterDeleteHook, productPriceAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	productPriceAfterDeleteHooks = []ProductPriceHook{}

	AddProductPriceHook(boil.BeforeUpsertHook, productPriceBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	productPriceBeforeUpsertHooks = []ProductPriceHook{}

	AddProductPriceHook(boil.AfterUpsertHook, productPriceAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	productPriceAfterUpsertHooks = []ProductPriceHook{}
}

func testProductPricesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testProductPricesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(productPricePrimaryKeyColumns, productPriceColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := ProductPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testProductPricesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testProductPricesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ProductPriceSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testProductPricesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ProductPrices().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	productPriceDBTypes = map[string]string{`ID`: `integer`, `ProductID`: `integer`, `Variant`: `character varying`, `Currency`: `character varying`, `Price`: `numeric`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_                   = bytes.MinRead
)

func testProductPricesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(productPricePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(productPriceAllColumns) == len(productPricePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPricePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testProductPricesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(productPriceAllColumns) == len(productPricePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ProductPrice{}
	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPriceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ProductPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, productPriceDBTypes, true, productPricePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(productPriceAllColumns, productPricePrimaryKeyColumns) {
		fields = productPriceAllColumns
	} else {
		fields = strmangle.SetComplement(
			productPriceAllColumns,
			productPricePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ProductPriceSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testProductPricesUpsert(t *testing.T) {
	t.Parallel()

	if len(productPriceAllColumns) == len(productPricePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ProductPrice{}
	if err = randomize.Struct(seed, &o, productPriceDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ProductPrice: %s", err)
	}

	count, err := ProductPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, productPriceDBTypes, false, productPricePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ProductPrice struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ProductPrice: %s", err)
	}

	count, err = ProductPrices().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
