// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ProjectUser is an object representing the database table.
type ProjectUser struct {
	ID        int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	ProjectID string    `boil:"project_id" json:"project_id" toml:"project_id" yaml:"project_id"`
	UserID    string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	IsStarred bool      `boil:"is_starred" json:"is_starred" toml:"is_starred" yaml:"is_starred"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *projectUserR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L projectUserL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ProjectUserColumns = struct {
	ID        string
	ProjectID string
	UserID    string
	IsStarred string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	ProjectID: "project_id",
	UserID:    "user_id",
	IsStarred: "is_starred",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var ProjectUserTableColumns = struct {
	ID        string
	ProjectID string
	UserID    string
	IsStarred string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "project_user.id",
	ProjectID: "project_user.project_id",
	UserID:    "project_user.user_id",
	IsStarred: "project_user.is_starred",
	CreatedAt: "project_user.created_at",
	UpdatedAt: "project_user.updated_at",
}

// Generated where

var ProjectUserWhere = struct {
	ID        whereHelperint64
	ProjectID whereHelperstring
	UserID    whereHelperstring
	IsStarred whereHelperbool
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint64{field: "\"project_user\".\"id\""},
	ProjectID: whereHelperstring{field: "\"project_user\".\"project_id\""},
	UserID:    whereHelperstring{field: "\"project_user\".\"user_id\""},
	IsStarred: whereHelperbool{field: "\"project_user\".\"is_starred\""},
	CreatedAt: whereHelpertime_Time{field: "\"project_user\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"project_user\".\"updated_at\""},
}

// ProjectUserRels is where relationship names are stored.
var ProjectUserRels = struct {
	Project string
	User    string
}{
	Project: "Project",
	User:    "User",
}

// projectUserR is where relationships are stored.
type projectUserR struct {
	Project *Project `boil:"Project" json:"Project" toml:"Project" yaml:"Project"`
	User    *AppUser `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*projectUserR) NewStruct() *projectUserR {
	return &projectUserR{}
}

func (o *ProjectUser) GetProject() *Project {
	if o == nil {
		return nil
	}

	return o.R.GetProject()
}

func (r *projectUserR) GetProject() *Project {
	if r == nil {
		return nil
	}

	return r.Project
}

func (o *ProjectUser) GetUser() *AppUser {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *projectUserR) GetUser() *AppUser {
	if r == nil {
		return nil
	}

	return r.User
}

// projectUserL is where Load methods for each relationship are stored.
type projectUserL struct{}

var (
	projectUserAllColumns            = []string{"id", "project_id", "user_id", "is_starred", "created_at", "updated_at"}
	projectUserColumnsWithoutDefault = []string{"project_id", "user_id"}
	projectUserColumnsWithDefault    = []string{"id", "is_starred", "created_at", "updated_at"}
	projectUserPrimaryKeyColumns     = []string{"id"}
	projectUserGeneratedColumns      = []string{}
)

type (
	// ProjectUserSlice is an alias for a slice of pointers to ProjectUser.
	// This should almost always be used instead of []ProjectUser.
	ProjectUserSlice []*ProjectUser
	// ProjectUserHook is the signature for custom ProjectUser hook methods
	ProjectUserHook func(context.Context, boil.ContextExecutor, *ProjectUser) error

	projectUserQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	projectUserType                 = reflect.TypeOf(&ProjectUser{})
	projectUserMapping              = queries.MakeStructMapping(projectUserType)
	projectUserPrimaryKeyMapping, _ = queries.BindMapping(projectUserType, projectUserMapping, projectUserPrimaryKeyColumns)
	projectUserInsertCacheMut       sync.RWMutex
	projectUserInsertCache          = make(map[string]insertCache)
	projectUserUpdateCacheMut       sync.RWMutex
	projectUserUpdateCache          = make(map[string]updateCache)
	projectUserUpsertCacheMut       sync.RWMutex
	projectUserUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var projectUserAfterSelectMu sync.Mutex
var projectUserAfterSelectHooks []ProjectUserHook

var projectUserBeforeInsertMu sync.Mutex
var projectUserBeforeInsertHooks []ProjectUserHook
var projectUserAfterInsertMu sync.Mutex
var projectUserAfterInsertHooks []ProjectUserHook

var projectUserBeforeUpdateMu sync.Mutex
var projectUserBeforeUpdateHooks []ProjectUserHook
var projectUserAfterUpdateMu sync.Mutex
var projectUserAfterUpdateHooks []ProjectUserHook

var projectUserBeforeDeleteMu sync.Mutex
var projectUserBeforeDeleteHooks []ProjectUserHook
var projectUserAfterDeleteMu sync.Mutex
var projectUserAfterDeleteHooks []ProjectUserHook

var projectUserBeforeUpsertMu sync.Mutex
var projectUserBeforeUpsertHooks []ProjectUserHook
var projectUserAfterUpsertMu sync.Mutex
var projectUserAfterUpsertHooks []ProjectUserHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ProjectUser) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectUserAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ProjectUser) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectUserBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ProjectUser) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectUserAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ProjectUser) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectUserBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ProjectUser) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectUserAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ProjectUser) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectUserBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ProjectUser) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectUserAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ProjectUser) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectUserBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ProjectUser) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range projectUserAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddProjectUserHook registers your hook function for all future operations.
func AddProjectUserHook(hookPoint boil.HookPoint, projectUserHook ProjectUserHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		projectUserAfterSelectMu.Lock()
		projectUserAfterSelectHooks = append(projectUserAfterSelectHooks, projectUserHook)
		projectUserAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		projectUserBeforeInsertMu.Lock()
		projectUserBeforeInsertHooks = append(projectUserBeforeInsertHooks, projectUserHook)
		projectUserBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		projectUserAfterInsertMu.Lock()
		projectUserAfterInsertHooks = append(projectUserAfterInsertHooks, projectUserHook)
		projectUserAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		projectUserBeforeUpdateMu.Lock()
		projectUserBeforeUpdateHooks = append(projectUserBeforeUpdateHooks, projectUserHook)
		projectUserBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		projectUserAfterUpdateMu.Lock()
		projectUserAfterUpdateHooks = append(projectUserAfterUpdateHooks, projectUserHook)
		projectUserAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		projectUserBeforeDeleteMu.Lock()
		projectUserBeforeDeleteHooks = append(projectUserBeforeDeleteHooks, projectUserHook)
		projectUserBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		projectUserAfterDeleteMu.Lock()
		projectUserAfterDeleteHooks = append(projectUserAfterDeleteHooks, projectUserHook)
		projectUserAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		projectUserBeforeUpsertMu.Lock()
		projectUserBeforeUpsertHooks = append(projectUserBeforeUpsertHooks, projectUserHook)
		projectUserBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		projectUserAfterUpsertMu.Lock()
		projectUserAfterUpsertHooks = append(projectUserAfterUpsertHooks, projectUserHook)
		projectUserAfterUpsertMu.Unlock()
	}
}

// One returns a single projectUser record from the query.
func (q projectUserQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ProjectUser, error) {
	o := &ProjectUser{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for project_user")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ProjectUser records from the query.
func (q projectUserQuery) All(ctx context.Context, exec boil.ContextExecutor) (ProjectUserSlice, error) {
	var o []*ProjectUser

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ProjectUser slice")
	}

	if len(projectUserAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ProjectUser records in the query.
func (q projectUserQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count project_user rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q projectUserQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if project_user exists")
	}

	return count > 0, nil
}

// Project pointed to by the foreign key.
func (o *ProjectUser) Project(mods ...qm.QueryMod) projectQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ProjectID),
	}

	queryMods = append(queryMods, mods...)

	return Projects(queryMods...)
}

// User pointed to by the foreign key.
func (o *ProjectUser) User(mods ...qm.QueryMod) appUserQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return AppUsers(queryMods...)
}

// LoadProject allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (projectUserL) LoadProject(ctx context.Context, e boil.ContextExecutor, singular bool, maybeProjectUser interface{}, mods queries.Applicator) error {
	var slice []*ProjectUser
	var object *ProjectUser

	if singular {
		var ok bool
		object, ok = maybeProjectUser.(*ProjectUser)
		if !ok {
			object = new(ProjectUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeProjectUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeProjectUser))
			}
		}
	} else {
		s, ok := maybeProjectUser.(*[]*ProjectUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeProjectUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeProjectUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &projectUserR{}
		}
		args[object.ProjectID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &projectUserR{}
			}

			args[obj.ProjectID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`project`),
		qm.WhereIn(`project.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Project")
	}

	var resultSlice []*Project
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Project")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for project")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for project")
	}

	if len(projectAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Project = foreign
		if foreign.R == nil {
			foreign.R = &projectR{}
		}
		foreign.R.ProjectUsers = append(foreign.R.ProjectUsers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ProjectID == foreign.ID {
				local.R.Project = foreign
				if foreign.R == nil {
					foreign.R = &projectR{}
				}
				foreign.R.ProjectUsers = append(foreign.R.ProjectUsers, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (projectUserL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeProjectUser interface{}, mods queries.Applicator) error {
	var slice []*ProjectUser
	var object *ProjectUser

	if singular {
		var ok bool
		object, ok = maybeProjectUser.(*ProjectUser)
		if !ok {
			object = new(ProjectUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeProjectUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeProjectUser))
			}
		}
	} else {
		s, ok := maybeProjectUser.(*[]*ProjectUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeProjectUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeProjectUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &projectUserR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &projectUserR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`app_user`),
		qm.WhereIn(`app_user.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load AppUser")
	}

	var resultSlice []*AppUser
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice AppUser")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for app_user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for app_user")
	}

	if len(appUserAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &appUserR{}
		}
		foreign.R.UserProjectUsers = append(foreign.R.UserProjectUsers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &appUserR{}
				}
				foreign.R.UserProjectUsers = append(foreign.R.UserProjectUsers, local)
				break
			}
		}
	}

	return nil
}

// SetProject of the projectUser to the related item.
// Sets o.R.Project to related.
// Adds o to related.R.ProjectUsers.
func (o *ProjectUser) SetProject(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Project) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"project_user\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"project_id"}),
		strmangle.WhereClause("\"", "\"", 2, projectUserPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ProjectID = related.ID
	if o.R == nil {
		o.R = &projectUserR{
			Project: related,
		}
	} else {
		o.R.Project = related
	}

	if related.R == nil {
		related.R = &projectR{
			ProjectUsers: ProjectUserSlice{o},
		}
	} else {
		related.R.ProjectUsers = append(related.R.ProjectUsers, o)
	}

	return nil
}

// SetUser of the projectUser to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserProjectUsers.
func (o *ProjectUser) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *AppUser) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"project_user\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, projectUserPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &projectUserR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &appUserR{
			UserProjectUsers: ProjectUserSlice{o},
		}
	} else {
		related.R.UserProjectUsers = append(related.R.UserProjectUsers, o)
	}

	return nil
}

// ProjectUsers retrieves all the records using an executor.
func ProjectUsers(mods ...qm.QueryMod) projectUserQuery {
	mods = append(mods, qm.From("\"project_user\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"project_user\".*"})
	}

	return projectUserQuery{q}
}

// FindProjectUser retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindProjectUser(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ProjectUser, error) {
	projectUserObj := &ProjectUser{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"project_user\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, projectUserObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from project_user")
	}

	if err = projectUserObj.doAfterSelectHooks(ctx, exec); err != nil {
		return projectUserObj, err
	}

	return projectUserObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ProjectUser) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no project_user provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(projectUserColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	projectUserInsertCacheMut.RLock()
	cache, cached := projectUserInsertCache[key]
	projectUserInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			projectUserAllColumns,
			projectUserColumnsWithDefault,
			projectUserColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(projectUserType, projectUserMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(projectUserType, projectUserMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"project_user\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"project_user\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into project_user")
	}

	if !cached {
		projectUserInsertCacheMut.Lock()
		projectUserInsertCache[key] = cache
		projectUserInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ProjectUser.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ProjectUser) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	projectUserUpdateCacheMut.RLock()
	cache, cached := projectUserUpdateCache[key]
	projectUserUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			projectUserAllColumns,
			projectUserPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update project_user, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"project_user\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, projectUserPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(projectUserType, projectUserMapping, append(wl, projectUserPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update project_user row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for project_user")
	}

	if !cached {
		projectUserUpdateCacheMut.Lock()
		projectUserUpdateCache[key] = cache
		projectUserUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q projectUserQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for project_user")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for project_user")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ProjectUserSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"project_user\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, projectUserPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in projectUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all projectUser")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ProjectUser) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no project_user provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(projectUserColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	projectUserUpsertCacheMut.RLock()
	cache, cached := projectUserUpsertCache[key]
	projectUserUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			projectUserAllColumns,
			projectUserColumnsWithDefault,
			projectUserColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			projectUserAllColumns,
			projectUserPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert project_user, could not build update column list")
		}

		ret := strmangle.SetComplement(projectUserAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(projectUserPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert project_user, could not build conflict column list")
			}

			conflict = make([]string, len(projectUserPrimaryKeyColumns))
			copy(conflict, projectUserPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"project_user\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(projectUserType, projectUserMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(projectUserType, projectUserMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert project_user")
	}

	if !cached {
		projectUserUpsertCacheMut.Lock()
		projectUserUpsertCache[key] = cache
		projectUserUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ProjectUser record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ProjectUser) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ProjectUser provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), projectUserPrimaryKeyMapping)
	sql := "DELETE FROM \"project_user\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from project_user")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for project_user")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q projectUserQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no projectUserQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from project_user")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for project_user")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ProjectUserSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(projectUserBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"project_user\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, projectUserPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from projectUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for project_user")
	}

	if len(projectUserAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ProjectUser) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindProjectUser(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ProjectUserSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ProjectUserSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), projectUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"project_user\".* FROM \"project_user\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, projectUserPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ProjectUserSlice")
	}

	*o = slice

	return nil
}

// ProjectUserExists checks if the ProjectUser row exists.
func ProjectUserExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"project_user\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if project_user exists")
	}

	return exists, nil
}

// Exists checks if the ProjectUser row exists.
func (o *ProjectUser) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ProjectUserExists(ctx, exec, o.ID)
}
