// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserSettings(t *testing.T) {
	t.Parallel()

	query := UserSettings()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserSettingsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserSettingsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserSettings().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserSettingsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserSettingSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserSettingsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserSettingExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UserSetting exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserSettingExists to return true, but got false.")
	}
}

func testUserSettingsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userSettingFound, err := FindUserSetting(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if userSettingFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserSettingsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserSettings().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserSettingsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserSettings().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserSettingsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userSettingOne := &UserSetting{}
	userSettingTwo := &UserSetting{}
	if err = randomize.Struct(seed, userSettingOne, userSettingDBTypes, false, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}
	if err = randomize.Struct(seed, userSettingTwo, userSettingDBTypes, false, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userSettingOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userSettingTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserSettings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserSettingsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userSettingOne := &UserSetting{}
	userSettingTwo := &UserSetting{}
	if err = randomize.Struct(seed, userSettingOne, userSettingDBTypes, false, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}
	if err = randomize.Struct(seed, userSettingTwo, userSettingDBTypes, false, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userSettingOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userSettingTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func userSettingBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserSetting) error {
	*o = UserSetting{}
	return nil
}

func userSettingAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserSetting) error {
	*o = UserSetting{}
	return nil
}

func userSettingAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UserSetting) error {
	*o = UserSetting{}
	return nil
}

func userSettingBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserSetting) error {
	*o = UserSetting{}
	return nil
}

func userSettingAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserSetting) error {
	*o = UserSetting{}
	return nil
}

func userSettingBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserSetting) error {
	*o = UserSetting{}
	return nil
}

func userSettingAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserSetting) error {
	*o = UserSetting{}
	return nil
}

func userSettingBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserSetting) error {
	*o = UserSetting{}
	return nil
}

func userSettingAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserSetting) error {
	*o = UserSetting{}
	return nil
}

func testUserSettingsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UserSetting{}
	o := &UserSetting{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, userSettingDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UserSetting object: %s", err)
	}

	AddUserSettingHook(boil.BeforeInsertHook, userSettingBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	userSettingBeforeInsertHooks = []UserSettingHook{}

	AddUserSettingHook(boil.AfterInsertHook, userSettingAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	userSettingAfterInsertHooks = []UserSettingHook{}

	AddUserSettingHook(boil.AfterSelectHook, userSettingAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	userSettingAfterSelectHooks = []UserSettingHook{}

	AddUserSettingHook(boil.BeforeUpdateHook, userSettingBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	userSettingBeforeUpdateHooks = []UserSettingHook{}

	AddUserSettingHook(boil.AfterUpdateHook, userSettingAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	userSettingAfterUpdateHooks = []UserSettingHook{}

	AddUserSettingHook(boil.BeforeDeleteHook, userSettingBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	userSettingBeforeDeleteHooks = []UserSettingHook{}

	AddUserSettingHook(boil.AfterDeleteHook, userSettingAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	userSettingAfterDeleteHooks = []UserSettingHook{}

	AddUserSettingHook(boil.BeforeUpsertHook, userSettingBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	userSettingBeforeUpsertHooks = []UserSettingHook{}

	AddUserSettingHook(boil.AfterUpsertHook, userSettingAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	userSettingAfterUpsertHooks = []UserSettingHook{}
}

func testUserSettingsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserSettingsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(userSettingPrimaryKeyColumns, userSettingColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserSettingToOneAppUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UserSetting
	var foreign AppUser

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, userSettingDBTypes, false, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, appUserDBTypes, false, appUserColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AppUser struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddAppUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *AppUser) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := UserSettingSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*UserSetting)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testUserSettingToOneSetOpAppUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UserSetting
	var b, c AppUser

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, userSettingDBTypes, false, strmangle.SetComplement(userSettingPrimaryKeyColumns, userSettingColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, appUserDBTypes, false, strmangle.SetComplement(appUserPrimaryKeyColumns, appUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, appUserDBTypes, false, strmangle.SetComplement(appUserPrimaryKeyColumns, appUserColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*AppUser{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserUserSetting != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testUserSettingsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserSettingsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserSettingSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserSettingsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserSettings().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userSettingDBTypes = map[string]string{`ID`: `uuid`, `UserID`: `uuid`, `Language`: `character varying`, `Theme`: `character varying`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_                  = bytes.MinRead
)

func testUserSettingsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userSettingPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userSettingAllColumns) == len(userSettingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserSettingsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userSettingAllColumns) == len(userSettingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserSetting{}
	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userSettingDBTypes, true, userSettingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userSettingAllColumns, userSettingPrimaryKeyColumns) {
		fields = userSettingAllColumns
	} else {
		fields = strmangle.SetComplement(
			userSettingAllColumns,
			userSettingPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserSettingSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserSettingsUpsert(t *testing.T) {
	t.Parallel()

	if len(userSettingAllColumns) == len(userSettingPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserSetting{}
	if err = randomize.Struct(seed, &o, userSettingDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserSetting: %s", err)
	}

	count, err := UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userSettingDBTypes, false, userSettingPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserSetting struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserSetting: %s", err)
	}

	count, err = UserSettings().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
