name: "Build Fusion Server App"
description: "Build Fusion Server App"
inputs:
  flutter_apps_sonar_token:
    description: 'SonarQube server token'
    required: true
  nexus_password:
    description: 'Nexus repository password'
    required: true
  jenkins_user_name:
    description: 'Jenkins username for authentication'
    required: true
  jenkins_user_token:
    description: 'Jenkins token for authentication'
    required: true
  jenkins_url:
    description: 'Nexus repository URL'
    required: true
  nexus_url:
    description: 'Nexus repository URL'
    required: true
        
runs:
  using: "composite"
  steps:
    - name: Build Fusion Server
      shell: bash
      working-directory: apps/firmware-apps/fusion-server
      run: |
        moon run fusion-server:build
        VERSION="$(./Jenkins/SetVersionProperty.sh)-${GITHUB_RUN_NUMBER}+$(git rev-parse --short HEAD)"
        curl -k --ssl-no-revoke -f -u github-actions-uploader:${{ inputs.nexus_password }} -T ./build/fusion-server_*.tar.gz ${{ inputs.nexus_url }}/Fusion-Server/Continuous/${GITHUB_REF_NAME}/fusion-server/$VERSION/fusion-server-$VERSION.tar.gz