const List<Map<String, String>> countries = [
  {'name': 'Afghanistan', 'code': '+93', 'iso': 'AF'},
  {'name': 'Albania', 'code': '+355', 'iso': 'AL'},
  {'name': 'Algeria', 'code': '+213', 'iso': 'DZ'},
  {'name': 'Argentina', 'code': '+54', 'iso': 'AR'},
  {'name': 'Australia', 'code': '+61', 'iso': 'AU'},
  {'name': 'Austria', 'code': '+43', 'iso': 'AT'},
  {'name': 'Bangladesh', 'code': '+880', 'iso': 'BD'},
  {'name': 'Belgium', 'code': '+32', 'iso': 'BE'},
  {'name': 'Brazil', 'code': '+55', 'iso': 'BR'},
  {'name': 'Canada', 'code': '+1', 'iso': 'CA'},
  {'name': 'China', 'code': '+86', 'iso': 'CN'},
  {'name': 'Denmark', 'code': '+45', 'iso': 'DK'},
  {'name': 'Egypt', 'code': '+20', 'iso': 'EG'},
  {'name': 'France', 'code': '+33', 'iso': 'FR'},
  {'name': 'Germany', 'code': '+49', 'iso': 'DE'},
  {'name': 'India', 'code': '+91', 'iso': 'IN'},
  {'name': 'Indonesia', 'code': '+62', 'iso': 'ID'},
  {'name': 'Ireland', 'code': '+353', 'iso': 'IE'},
  {'name': 'Italy', 'code': '+39', 'iso': 'IT'},
  {'name': 'Japan', 'code': '+81', 'iso': 'JP'},
  {'name': 'Malaysia', 'code': '+60', 'iso': 'MY'},
  {'name': 'Mexico', 'code': '+52', 'iso': 'MX'},
  {'name': 'Netherlands', 'code': '+31', 'iso': 'NL'},
  {'name': 'New Zealand', 'code': '+64', 'iso': 'NZ'},
  {'name': 'Nigeria', 'code': '+234', 'iso': 'NG'},
  {'name': 'Norway', 'code': '+47', 'iso': 'NO'},
  {'name': 'Pakistan', 'code': '+92', 'iso': 'PK'},
  {'name': 'Philippines', 'code': '+63', 'iso': 'PH'},
  {'name': 'Poland', 'code': '+48', 'iso': 'PL'},
  {'name': 'Portugal', 'code': '+351', 'iso': 'PT'},
  {'name': 'Russia', 'code': '+7', 'iso': 'RU'},
  {'name': 'Saudi Arabia', 'code': '+966', 'iso': 'SA'},
  {'name': 'Singapore', 'code': '+65', 'iso': 'SG'},
  {'name': 'South Africa', 'code': '+27', 'iso': 'ZA'},
  {'name': 'South Korea', 'code': '+82', 'iso': 'KR'},
  {'name': 'Spain', 'code': '+34', 'iso': 'ES'},
  {'name': 'Sri Lanka', 'code': '+94', 'iso': 'LK'},
  {'name': 'Sweden', 'code': '+46', 'iso': 'SE'},
  {'name': 'Switzerland', 'code': '+41', 'iso': 'CH'},
  {'name': 'Thailand', 'code': '+66', 'iso': 'TH'},
  {'name': 'Turkey', 'code': '+90', 'iso': 'TR'},
  {'name': 'UAE', 'code': '+971', 'iso': 'AE'},
  {'name': 'Ukraine', 'code': '+380', 'iso': 'UA'},
  {'name': 'United Kingdom', 'code': '+44', 'iso': 'GB'},
  {'name': 'United States', 'code': '+1', 'iso': 'US'},
  {'name': 'Vietnam', 'code': '+84', 'iso': 'VN'},
];
