List<Map<String, String>> allTimeZonesJson = <Map<String, String>>[
  <String, String>{"name": "Coordinated Universal Time", "region": "UTC", "offset": "UTC+00:00"},

  <String, String>{"name": "Greenwich Mean Time", "region": "Europe/London", "offset": "UTC+00:00"},
  <String, String>{"name": "Central European Time", "region": "Europe/Paris", "offset": "UTC+01:00"},
  <String, String>{"name": "Eastern European Time", "region": "Europe/Athens", "offset": "UTC+02:00"},
  <String, String>{"name": "Moscow Standard Time", "region": "Europe/Moscow", "offset": "UTC+03:00"},

  <String, String>{"name": "Gulf Standard Time", "region": "Asia/Dubai", "offset": "UTC+04:00"},
  <String, String>{"name": "Pakistan Standard Time", "region": "Asia/Karachi", "offset": "UTC+05:00"},
  <String, String>{"name": "India Standard Time", "region": "Asia/Kolkata", "offset": "UTC+05:30"},
  <String, String>{"name": "Nepal Time", "region": "Asia/Kathmandu", "offset": "UTC+05:45"},
  <String, String>{"name": "Bangladesh Standard Time", "region": "Asia/Dhaka", "offset": "UTC+06:00"},
  <String, String>{"name": "Myanmar Time", "region": "Asia/Yangon", "offset": "UTC+06:30"},
  <String, String>{"name": "Indochina Time", "region": "Asia/Bangkok", "offset": "UTC+07:00"},
  <String, String>{"name": "China Standard Time", "region": "Asia/Shanghai", "offset": "UTC+08:00"},
  <String, String>{"name": "Singapore Standard Time", "region": "Asia/Singapore", "offset": "UTC+08:00"},
  <String, String>{"name": "Japan Standard Time", "region": "Asia/Tokyo", "offset": "UTC+09:00"},
  <String, String>{"name": "Korea Standard Time", "region": "Asia/Seoul", "offset": "UTC+09:00"},
  <String, String>{"name": "Australian Central Standard Time", "region": "Australia/Adelaide", "offset": "UTC+09:30"},
  <String, String>{"name": "Australian Eastern Standard Time", "region": "Australia/Sydney", "offset": "UTC+10:00"},
  <String, String>{"name": "Solomon Islands Time", "region": "Pacific/Guadalcanal", "offset": "UTC+11:00"},
  <String, String>{"name": "New Zealand Standard Time", "region": "Pacific/Auckland", "offset": "UTC+12:00"},
  <String, String>{"name": "Fiji Time", "region": "Pacific/Fiji", "offset": "UTC+12:00"},
  <String, String>{"name": "Tonga Time", "region": "Pacific/Tongatapu", "offset": "UTC+13:00"},
  <String, String>{"name": "Line Islands Time", "region": "Pacific/Kiritimati", "offset": "UTC+14:00"},

  <String, String>{"name": "Azores Time", "region": "Atlantic/Azores", "offset": "UTC-01:00"},
  <String, String>{"name": "South Georgia Time", "region": "Atlantic/South_Georgia", "offset": "UTC-02:00"},
  <String, String>{"name": "Argentina Time", "region": "America/Argentina/Buenos_Aires", "offset": "UTC-03:00"},
  <String, String>{"name": "Brazil Time", "region": "America/Sao_Paulo", "offset": "UTC-03:00"},
  <String, String>{"name": "Atlantic Standard Time", "region": "America/Halifax", "offset": "UTC-04:00"},
  <String, String>{"name": "Eastern Standard Time", "region": "America/New_York", "offset": "UTC-05:00"},
  <String, String>{"name": "Central Standard Time", "region": "America/Chicago", "offset": "UTC-06:00"},
  <String, String>{"name": "Mountain Standard Time", "region": "America/Denver", "offset": "UTC-07:00"},
  <String, String>{"name": "Pacific Standard Time", "region": "America/Los_Angeles", "offset": "UTC-08:00"},
  <String, String>{"name": "Alaska Standard Time", "region": "America/Anchorage", "offset": "UTC-09:00"},
  <String, String>{"name": "Hawaii Standard Time", "region": "Pacific/Honolulu", "offset": "UTC-10:00"},
  <String, String>{"name": "Samoa Standard Time", "region": "Pacific/Pago_Pago", "offset": "UTC-11:00"},
];
