#!/bin/bash
set -euo pipefail

# Build the fusion-server binary and optionally a release package.
#
# Usage:
# $ ./build-fusion-server [-p]
#   Arguments:
#   --package    [optional] Build a release package with required config files, etc.

# Define variables
BINARY_NAME="fusion-server"
ARCH="${ARCH:-arm64}"
OS="linux"
EXPECTED_BINARY="${BINARY_NAME}_${OS}_${ARCH}"

# Clean up old binary if it exists
if [ -f "$BINARY_NAME" ]; then
    echo "Removing old binary..."
    rm "$BINARY_NAME"
fi

# Build the binary
echo "Building ${BINARY_NAME} for ${OS}_${ARCH}..."
make "build-${OS}-${ARCH}"

# Check if the build produced the expected binary
if [ ! -f "build/$EXPECTED_BINARY" ]; then
    echo "Error: Build failed to produce ${EXPECTED_BINARY}"
    exit 1
fi

# Rename the binary
echo "Linking binary to expected name..."
pushd ./build
ln -sf "$EXPECTED_BINARY" "$BINARY_NAME"
popd

flag=${1:-}

if [ "$flag" = '--package' ]; then
    # Make a "release package" with the binary, config files and version info.
    # Get the commit-id
    commit_id=$(git rev-parse HEAD)
    full_version=$VERSION

    cat << EOF_VERSION > build/fusion-server.info
APP="fusion-server"
# Build servers will define VERSION in the environment, but set a default for local builds.
VERSION="${VERSION:-LOCAL}"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
COMMIT_ID="$commit_id"
COMMIT_DATE="$(TZ=UTC0 git --no-pager log -1 --pretty='format:%cd' --date='format-local:%Y-%m-%dT%H:%M:%S+00:00')"
BUILD_DATE="$(date -u -Iseconds)"
EOF_VERSION
    
    tar -czhf "build/fusion-server_${full_version}.tar.gz" scripts/*.service scripts/generate_cloud_config.sh \
              build/$BINARY_NAME build/fusion-server.info
    # Cleanup temp files
    rm build/fusion-server.info
fi

echo "Build process completed successfully."
