#!/bin/bash
set -euo pipefail

# Build the fusion-server binary and optionally a release package.
#
# Usage:
#   ./build-fusion-server [--target <target>] [--package]
#     --target        Specify the target operating system (default: linux)
#     --package   Build a release package with required config files, etc.

# Default values
BINARY_NAME="fusion-server"
ARCH="${ARCH:-arm64}"
TARGET="linux"
PACKAGE=false

# Process command-line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --target)
            TARGET="$2"
            shift 2
            ;;
        --package|-p)
            PACKAGE=true
            shift
            ;;
        *)
            echo "Unknown parameter: $1"
            exit 1
            ;;
    esac
done

EXPECTED_BINARY="${BINARY_NAME}_${TARGET}_${ARCH}"

# Clean up old binary if it exists
if [ -f "$BINARY_NAME" ]; then
    echo "Removing old binary..."
    rm "$BINARY_NAME"
fi

# Build the binary
echo "Building ${BINARY_NAME} for ${TARGET}_${ARCH}..."
make "build-${TARGET}-${ARCH}"

# Check if the build produced the expected binary
if [ ! -f "build/$EXPECTED_BINARY" ]; then
    echo "Error: Build failed to produce ${EXPECTED_BINARY}"
    exit 1
fi

# Rename the binary
echo "Linking binary to expected name..."
pushd ./build > /dev/null
ln -sf "$EXPECTED_BINARY" "$BINARY_NAME"
popd > /dev/null

if [ "$PACKAGE" = true ]; then
    # Make a "release package" with the binary, config files and version info.
    VERSION=${VERSION:-LOCAL}
    commit_id=$(git rev-parse HEAD)
    full_version=$VERSION

    cat << EOF_VERSION > build/fusion-server.info
APP="fusion-server"
VERSION="$VERSION"
BRANCH="$branchName"
COMMIT_ID="$commit_id"
COMMIT_DATE="$(TZ=UTC0 git --no-pager log -1 --pretty='format:%cd' --date='format-local:%Y-%m-%dT%H:%M:%S+00:00')"
BUILD_DATE="$(date -u -Iseconds)"
EOF_VERSION
    
    tar -czhf "build/fusion-server_${full_version}.tar.gz" scripts/*.service scripts/generate_cloud_config.sh \
              build/$BINARY_NAME build/fusion-server.info
    rm build/fusion-server.info
fi

echo "Build process completed successfully."
