services:
  dsp1:
    build:
      context: .
      dockerfile: Dockerfile
    image: fusion-server
    networks:
      fusionnet:
        ipv4_address: ${NETWORK_PREFIX}.${DSP1_SUFFIX}
    ports:
      - "80:80" # HAProxy port
      - "${DSP1_PORT}:${GOSSIP_PORT}"
    environment:
      - KEEPALIVED_CONF=${KEEPALIVED_PRIMARY_CONF}
    command: --name dsp1 --addr 0.0.0.0 --port ${GOSSIP_PORT}
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW

  dsp2:
    build:
      context: .
      dockerfile: Dockerfile
    image: fusion-server
    networks:
      fusionnet:
        ipv4_address: ${NETWORK_PREFIX}.${DSP2_SUFFIX}
    ports:
      - "${DSP2_PORT}:${GOSSIP_PORT}"
    environment:
      - KEEPALIVED_CONF=${KEEPALIVED_BACKUP1_CONF}
    command: --name dsp2 --addr 0.0.0.0 --port ${GOSSIP_PORT} --join ${NETWORK_PREFIX}.${DSP1_SUFFIX}:${GOSSIP_PORT}
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
  # dsp3:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: fusion-server
  #   networks:
  #     fusionnet:
  #       ipv4_address: ${NETWORK_PREFIX}.${DSP3_SUFFIX}
  #   ports:
  #     - "${DSP3_PORT}:${GOSSIP_PORT}"
  #   environment:
  #     - KEEPALIVED_CONF=${KEEPALIVED_BACKUP2_CONF}
  #   command: --name dsp3 --addr 0.0.0.0 --port ${GOSSIP_PORT} --join ${NETWORK_PREFIX}.${DSP1_SUFFIX}:${GOSSIP_PORT},${NETWORK_PREFIX}.${DSP2_SUFFIX}:${GOSSIP_PORT}
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_BROADCAST
  #     - NET_RAW

  # dsp4:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: fusion-server
  #   networks:
  #     fusionnet:
  #       ipv4_address: ${NETWORK_PREFIX}.${DSP4_SUFFIX}
  #   ports:
  #     - "${DSP4_PORT}:${GOSSIP_PORT}"
  #   environment:
  #     - KEEPALIVED_CONF=${KEEPALIVED_BACKUP3_CONF}
  #   command: --name dsp4 --addr 0.0.0.0 --port ${GOSSIP_PORT} --join ${NETWORK_PREFIX}.${DSP1_SUFFIX}:${GOSSIP_PORT},${NETWORK_PREFIX}.${DSP2_SUFFIX}:${GOSSIP_PORT},${NETWORK_PREFIX}.${DSP3_SUFFIX}:${GOSSIP_PORT}
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_BROADCAST
  #     - NET_RAW

networks:
  fusionnet:
    external: true
    driver_opts:
      com.docker.network.driver.mtu: 1450
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_PREFIX}.0/24
