global_defs {
    enable_script_security
    max_auto_priority 99
    vrrp_garp_master_delay 5
    vrrp_garp_master_repeat 5
    vrrp_garp_master_refresh 5
    vrrp_garp_master_refresh_repeat 5
}

vrrp_instance VI_1 {
    state MASTER
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass bosepro
    }
    virtual_ipaddress {
        172.18.0.2
    }
}
