global_defs {
    enable_script_security
    max_auto_priority 99
    vrrp_garp_master_delay 1
    vrrp_garp_master_repeat 3
    vrrp_garp_master_refresh 1
    vrrp_garp_master_refresh_repeat 2
    notification_email {
        root@localhost
    }
    notification_email_from keepalived@localhost
    smtp_server 127.0.0.1
    smtp_connect_timeout 30
    router_id LVS_BACKUP
    vrrp_skip_check_adv_addr
    log_unknown_vrids
}

vrrp_instance VI_1 {
    state BACKUP
    interface eth0
    virtual_router_id 51
    priority 70
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass bosepro
    }
    virtual_ipaddress {
        172.18.0.2/24 dev eth0
    }
    track_interface {
        eth0
    }
    unicast_peer {
        172.18.0.3
    }
}
