global_defs {
    enable_script_security
    max_auto_priority 99
    vrrp_garp_master_delay 1
    vrrp_garp_master_repeat 3
    vrrp_garp_master_refresh 1
    vrrp_garp_master_refresh_repeat 2
    vrrp_skip_check_adv_addr
    log_unknown_vrids
}

vrrp_instance VI_1 {
    state BACKUP
    interface eth0
    virtual_router_id 51
    priority 90
    advert_int 1

    unicast_src_ip 172.18.0.3
    unicast_peer {
        172.18.0.4
    }
    
    authentication {
        auth_type PASS
        auth_pass bosepro
    }
    virtual_ipaddress {
        172.18.0.2/24
    }
}
