name: "Build Flutter Android and iOS App"
description: "Build Flutter Android and iOS App"

runs:
  using: "composite"
  steps:
    - name: Flutter Android build
      shell: bash
      working-directory: apps/frontend/fusion-launcher-prototype
      run: |
        flutter pub get
        moon run fusion-launcher-prototype:build-apk

    - name: Flutter iOS build
      shell: bash
      working-directory: apps/frontend/fusion-launcher-prototype
      run: |
        flutter pub get
        moon run fusion-launcher-prototype:build-iOS
