name: "Build Flutter Android, macOS and iOS App"
description: "Build Flutter Android, macOS and iOS App"
inputs:
  flutter_apps_sonar_token:
    description: 'SonarQube server token'
    required: true
  nexus_password:
    description: 'Nexus repository password'
    required: true
  keychain_password:
    description: 'Keychain password for iOS build'
    required: true
  nexus_url:
    description: 'Nexus repository URL'
    required: true
        
runs:
  using: "composite"
  steps:
    - name: Read package version
      id: get_version
      uses: RCSandberg/dart-flutter-read-package-version-action@v2
      with:
        path: apps/frontend/flutter-apps/fusion-launcher/pubspec.yaml

    # - name: SonarQube Scan
    #   uses: SonarSource/sonarqube-scan-action@v5
    #   env:
    #     SONAR_TOKEN: ${{ inputs.flutter_apps_sonar_token }}
    #   with:
    #     projectBaseDir: 'apps/frontend/flutter-apps'
    #     args: >
    #       -Dsonar.c.file.suffixes=-
    #       -Dsonar.cpp.file.suffixes=-
    #       -Dsonar.objc.file.suffixes=-
    #       -Dsonar.exclusions=build/**
    #       -Dsonar.inclusions=lib/**,android/**,ios/**

    - name: Flutter Android, macOS and iOS Apps build
      shell: bash
      working-directory: apps/frontend/flutter-apps/fusion-launcher
      run: |
        flutter pub get
        moon run flutter-apps:build-all
        VERSION="${{ steps.get_version.outputs.version }}-$(git rev-parse --short HEAD)"
        curl -k --ssl-no-revoke -f -u github-actions-uploader:${{ inputs.nexus_password }} -T ./build/app/outputs/flutter-apk/Fusion\ Launcher.apk ${{ inputs.nexus_url }}/Fusion-Frontend/Continuous/$VERSION/flutter-apk/Fusion-Launcher-$VERSION.apk
        curl -k --ssl-no-revoke -f -u github-actions-uploader:${{ inputs.nexus_password }} -T ./build/ios/ipa/Fusion\ Launcher.ipa ${{ inputs.nexus_url }}/Fusion-Frontend/Continuous/$VERSION/flutter-iOS/Fusion-Launcher-$VERSION.ipa
        curl -k --ssl-no-revoke -f -u github-actions-uploader:${{ inputs.nexus_password }} -T ./build/macos/Build/Products/Release/Fusion\ Launcher.app ${{ inputs.nexus_url }}/Fusion-Frontend/Continuous/$VERSION/flutter-macOS/Fusion-Launcher-$VERSION.app
        echi "Builds uploaded to Nexus successfully!"
        echo "flutter-apk: ${{ inputs.nexus_url }}/Fusion-Frontend/Continuous/$VERSION/flutter-apk/Fusion-Launcher-$VERSION.apk"
        echo "flutter-iOS: ${{ inputs.nexus_url }}/Fusion-Frontend/Continuous/$VERSION/flutter-iOS/Fusion-Launcher-$VERSION.ipa"
        echo "flutter-macOS: ${{ inputs.nexus_url }}/Fusion-Frontend/Continuous/$VERSION/flutter-macOS/Fusion-Launcher-$VERSION.app" 
