name: "Build Flutter Android and iOS App"
description: "Build Flutter Android and iOS App"

runs:
  using: "composite"
  steps:
    - name: Flutter Android build
      shell: bash
      working-directory: apps/frontend/fusion-launcher-prototype
      run: |
        flutter pub get
        moon run fusion-launcher-prototype:build-apk

    - name: Upload apk artifact to Nexus
      shell: bash
      working-directory: apps/frontend/fusion-launcher-prototype/build/app/outputs/flutter-apk
      run: |
        curl --ssl-no-revoke -f -u Jenkins_AT:test123 -T aap-release.apk https://nexus.dev.prod.bosepro.internal:8445/repository/pro-fusion-local/Fusion-Frontend/Continuous/flutter-apk/aap-release.apk

    - name: Flutter iOS build
      shell: bash
      working-directory: apps/frontend/fusion-launcher-prototype
      run: |
        flutter pub get
        moon run fusion-launcher-prototype:build-iOS

    - name: Upload iOS build to Nexus
      shell: bash
      working-directory: apps/frontend/fusion-launcher-prototype/build/ios/ipa
      run: |
        curl --ssl-no-revoke -f -u Jenkins_AT:test123 -T fusion_design_tool_prototype.ipa https://nexus.dev.prod.bosepro.internal:8445/repository/pro-fusion-local/Fusion-Frontend/Continuous/flutter-iOS/fusion_design_tool_prototype.ipa
