name: "Build Fusion DSP App"
description: "Build Fusion DSP App"
inputs:
  flutter_apps_sonar_token:
    description: 'SonarQube server token'
    required: true
  nexus_password:
    description: 'Nexus repository password'
    required: true
  jenkins_user_name:
    description: 'Jenkins username for authentication'
    required: true
  jenkins_user_token:
    description: 'Jenkins token for authentication'
    required: true
  jenkins_url:
    description: 'Nexus repository URL'
    required: true
  nexus_url:
    description: 'Nexus repository URL'
    required: true
        
runs:
  using: "composite"
  steps:
    - name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Trigger jenkins job
          uses: joshlk/jenkins-githubaction@master
          with:
            url: ${{ inputs.jenkins_url }}
            job_name: Fusion/Fusion-DSP/Build-Fusion-DSP
            username: ${{ inputs.jenkins_user_name }}
            api_token: ${{ inputs.jenkins_user_token }}
            timeout: "1000"
       