name: "Build Fusion DSP App"
description: "Build Fusion DSP App"
inputs:
  flutter_apps_sonar_token:
    description: 'SonarQube server token'
    required: true
  nexus_password:
    description: 'Nexus repository password'
    required: true
  jenkins_user_name:
    description: 'Jenkins username for authentication'
    required: true
  jenkins_user_token:
    description: 'Jenkins token for authentication'
    required: true
  jenkins_url:
    description: 'Nexus repository URL'
    required: true
  nexus_url:
    description: 'Nexus repository URL'
    required: true
        
runs:
  using: "composite"
  steps:
    - name: Build with Waf
      shell: bash
      working-directory: apps/firmware-apps/fusion-dsp
      run: |
        moon run fusion-dsp:dsp-CI
        VERSION="$(./Jenkins/SetVersionProperty.sh)-${GITHUB_RUN_NUMBER}+$(git rev-parse --short HEAD)"
        curl -k --ssl-no-revoke -f -u github-actions-uploader:${{ inputs.nexus_password }} -T ./build/fusion-dsp_*.tar.gz ${{ inputs.nexus_url }}/Fusion-DSP/Continuous/${GITHUB_REF_NAME}/fusion-dsp/$VERSION/fusion-dsp_$VERSION.tar.gz