name: Fusion-Monorepo-Dev-CI

# Only run on commits, not when tags added
on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
    branches:
      - develop
      - release/*

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  buildChecks:
    runs-on: mac-agent-actions-runner
    outputs:
      all: ${{ steps.filter.outputs.all }}
      fusionLauncher: ${{ steps.filter.outputs.fusionLauncher }}
      cloudServicesUI: ${{ steps.filter.outputs.cloudServicesUI }}
      cloudServicesBackend: ${{ steps.filter.outputs.cloudServicesBackend }}
      fusionDSP: ${{ steps.filter.outputs.fusionDSP }}
      fusionServer: ${{ steps.filter.outputs.fusionServer }}
      fusionSystemMonitor: ${{ steps.filter.outputs.fusionSystemMonitor }}
      fusionEdgeGateway: ${{ steps.filter.outputs.fusionEdgeGateway }}
      fusionTelemetryCore: ${{ steps.filter.outputs.fusionTelemetryCore }}
    

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          initial-fetch-depth: ''
          filters: |
            all:
              - "./*" # Any file at the root directory
              - "./.github/**"
              - "./apps/**"
            fusionLauncher:
              - "./apps/frontend/flutter-apps/**"
            cloudServicesUI:
              - "./apps/frontend/react-apps/**"
            cloudServicesBackend:
              - "./apps/cloud-backend/fusion-cloud/**"
            fusionDSP:
              - "./apps/firmware-apps/fusion-dsp/**"
            fusionServer:
              - "./apps/firmware-apps/fusion-server/**"
            fusionSystemMonitor:
              - "./apps/firmware-apps/fusion-system-monitor/**"
            fusionEdgeGateway:
              - "./apps/firmware-apps/fusion-edge-gateway/**"
            fusionTelemetryCore:
              - "./apps/firmware-apps/fusion-telemetry-core/**" 

  flutter-android-iOS-macOS-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.fusionLauncher == 'true'
    concurrency:
      group: flutter-android-iOS-macOS-build
    runs-on: mac-agent-actions-runner
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Apps
        uses: ./.github/reusable-actions/build-flutter-Android-iOS
        with:
          flutter_apps_sonar_token: ${{ secrets.FLUTTER_APPS_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}
          notarize_apple_id: ${{ secrets.NOTARIZE_APPLE_ID }}
          notarize_app_password: ${{ secrets.NOTARIZE_APP_PASSWORD }}

  flutter-windows-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.fusionLauncher == 'true'
    concurrency:
      group: flutter-windows-build
    runs-on: windows-actions-build-agent
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Build Apps
        uses: ./.github/reusable-actions/build-flutter-windows
        with:
          flutter_apps_sonar_token: ${{ secrets.FLUTTER_APPS_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}
          cert_thumbprint: ${{ secrets.CERT_THUMBPRINT }}
          SM_API_KEY: ${{ secrets.SM_API_KEY }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}

  flutter-web-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.fusionLauncher == 'true'
    concurrency:
      group: flutter-web-build
    runs-on: ubuntu-agent
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Apps
        uses: ./.github/reusable-actions/build-flutter-web
        with:
          flutter_apps_sonar_token: ${{ secrets.FLUTTER_APPS_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}

  cloud-servicesUI-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.cloudServicesUI == 'true'
    concurrency:
      group: cloud-servicesUI-build
    runs-on: ubuntu-agent
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Apps
        uses: ./.github/reusable-actions/build-cloud-servicesUI

  cloud-web-backend-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.cloudServicesBackend == 'true'
    concurrency:
      group: cloud-web-backend-build
    runs-on: ubuntu-agent
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Apps
        uses: ./.github/reusable-actions/build-cloud-web-backend
        with:
          cloud_backend_sonar_token: ${{ secrets.CLOUD_BACKEND_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}     

  fusion-dsp-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.fusionDSP == 'true'
    concurrency:
      group: fusion-dsp-build
    runs-on: ubuntu-agent
    outputs:
      ran: ${{ steps.set-output.outputs.ran }}
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Apps
        uses: ./.github/reusable-actions/build-fusion-dsp
        with:
          flutter_apps_sonar_token: ${{ secrets.FLUTTER_APPS_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}
          jenkins_user_name: ${{ secrets.JENKINS_USER_NAME }}
          jenkins_user_token: ${{ secrets.JENKINS_TOKEN }}
          jenkins_url: ${{ secrets.JENKINS_URL }}
      
      - name: Set output
        id: set-output
        run: echo "ran=true" >> $GITHUB_OUTPUT

  fusion-server-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.fusionServer == 'true' || needs.buildChecks.outputs.fusionDSP == 'true'
    concurrency:
      group: fusion-server-build
    runs-on: ubuntu-agent
    outputs:
      ran: ${{ steps.set-output.outputs.ran }}
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Fusion Server
        uses: ./.github/reusable-actions/build-fusion-server
        with:
          flutter_apps_sonar_token: ${{ secrets.FLUTTER_APPS_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}
          jenkins_user_name: ${{ secrets.JENKINS_USER_NAME }}
          jenkins_user_token: ${{ secrets.JENKINS_TOKEN }}
          jenkins_url: ${{ secrets.JENKINS_URL }}

      - name: Set output
        id: set-output
        run: echo "ran=true" >> $GITHUB_OUTPUT

  fusion-system-monitor-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.fusionSystemMonitor == 'true'
    concurrency:
      group: fusion-system-monitor-build
    runs-on: ubuntu-agent
    outputs:
      ran: ${{ steps.set-output.outputs.ran }}
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Apps
        uses: ./.github/reusable-actions/build-fusion-system-monitor
        with:
          flutter_apps_sonar_token: ${{ secrets.FLUTTER_APPS_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}
          jenkins_user_name: ${{ secrets.JENKINS_USER_NAME }}
          jenkins_user_token: ${{ secrets.JENKINS_TOKEN }}
          jenkins_url: ${{ secrets.JENKINS_URL }}

      - name: Set output
        id: set-output
        run: echo "ran=true" >> $GITHUB_OUTPUT
  
  fusion-edge-gateway-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.fusionEdgeGateway == 'true'
    concurrency:
      group: fusion-edge-gateway-build
    runs-on: ubuntu-agent
    outputs:
      ran: ${{ steps.set-output.outputs.ran }}
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Apps
        uses: ./.github/reusable-actions/build-fusion-edge-gateway
        with:
          flutter_apps_sonar_token: ${{ secrets.FLUTTER_APPS_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}
          jenkins_user_name: ${{ secrets.JENKINS_USER_NAME }}
          jenkins_user_token: ${{ secrets.JENKINS_TOKEN }}
          jenkins_url: ${{ secrets.JENKINS_URL }}
      
      - name: Set output
        id: set-output
        run: echo "ran=true" >> $GITHUB_OUTPUT

  fusion-telemetry-core-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.fusionTelemetryCore == 'true'
    concurrency:
      group: fusion-telemetry-core-build
    runs-on: ubuntu-agent
    outputs:
      ran: ${{ steps.set-output.outputs.ran }}
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Apps
        uses: ./.github/reusable-actions/build-fusion-telemetry-core
        with:
          flutter_apps_sonar_token: ${{ secrets.FLUTTER_APPS_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}
          jenkins_user_name: ${{ secrets.JENKINS_USER_NAME }}
          jenkins_user_token: ${{ secrets.JENKINS_TOKEN }}
          jenkins_url: ${{ secrets.JENKINS_URL }}
      
      - name: Set output
        id: set-output
        run: echo "ran=true" >> $GITHUB_OUTPUT

  yocto-image-build-trigger:
    needs:
      - buildChecks
      - fusion-dsp-build
      - fusion-server-build
      - fusion-system-monitor-build
      - fusion-edge-gateway-build
      - fusion-telemetry-core-build

    if: |
      always() &&
      github.ref_name == 'devops/trigger-yocto-build' && (
        (needs.fusion-dsp-build.result == 'success' && needs.fusion-dsp-build.outputs.ran == 'true') ||
        (needs.fusion-server-build.result == 'success' && needs.fusion-server-build.outputs.ran == 'true') ||
        (needs.fusion-system-monitor-build.result == 'success' && needs.fusion-system-monitor-build.outputs.ran == 'true') ||
        (needs.fusion-edge-gateway-build.result == 'success' && needs.fusion-edge-gateway-build.outputs.ran == 'true') ||
        (needs.fusion-telemetry-core-build.result == 'success' && needs.fusion-telemetry-core-build.outputs.ran == 'true')
      )
    concurrency:
      group: yocto-image-build-trigger
    runs-on: ubuntu-agent
    timeout-minutes: 30
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: BoseProfessional/meta-fusion
          ref: devops/trigger-yocto-build
          token: ${{ secrets.META_FUSION_REPO_TOKEN }}
          fetch-depth: 0
          
      - name: Make changes in target repo
        run: |
          echo "Build successful on $(date)" >> build-status.txt
          git add build-status.txt
          git commit -m "CI: Build success from Fusion monorepo" || echo "No changes to commit"

      - name: Push commit to target repo
        run: |
          git push origin HEAD
