name: Fusion-Monorepo-Dev-CI

# Only run on commits, not when tags added
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  actions: read
  contents: write

jobs:
  buildChecks:
    runs-on: android-mac-build-agent
    outputs:
      all: ${{ steps.filter.outputs.all }}
      fusionLauncher: ${{ steps.filter.outputs.fusionLauncher }}
      cloudServicesUI: ${{ steps.filter.outputs.cloudServicesUI }}
      cloudServicesBackend: ${{ steps.filter.outputs.cloudServicesBackend }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            all:
              - "./*" # Any file at the root directory
              - "./.github/**"
              - "./apps/**"
            fusionLauncher:
              - "./apps/frontend/flutter-apps/**"
            cloudServicesUI:
              - "./apps/frontend/react-apps/**"
            cloudServicesBackend:
              - "./apps/cloud-backend/fusion-cloud/**"

  flutter-android-iOS-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.fusionLauncher == 'true' && github.ref == 'refs/heads/develop'
    concurrency:
      group: flutter-android-iOS-build
    runs-on: android-mac-build-agent
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Apps
        uses: ./.github/reusable-actions/build-flutter-Android-iOS
        with:
          flutter_apps_sonar_token: ${{ secrets.FLUTTER_APPS_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}

  cloud-servicesUI-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.cloudServicesUI == 'true' && github.ref == 'refs/heads/main'
    concurrency:
      group: cloud-servicesUI-build
    runs-on: android-mac-build-agent
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Apps
        uses: ./.github/reusable-actions/build-cloud-servicesUI

  cloud-web-backend-build:
    needs: buildChecks
    if: needs.buildChecks.outputs.cloudServicesBackend == 'true' && github.ref == 'refs/heads/develop'
    concurrency:
      group: cloud-web-backend-build
    runs-on: ubuntu-agent
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Monorepo Toolchain
        uses: ./.github/reusable-actions/setup-toolchain

      - name: Build Apps
        uses: ./.github/reusable-actions/build-cloud-web-backend
        with:
          cloud_backend_sonar_token: ${{ secrets.CLOUD_BACKEND_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}         
