name: Fusion-App-Windows-Automation-Build

# Only run on commits, not when tags added
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  flutter-windows-build:
    concurrency:
      group: flutter-windows-build
    runs-on: windows-actions-build-agent
    timeout-minutes: 30

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Build Windows desktop automation app
        uses: ./.github/reusable-actions/build-flutter-windows-automation
        with:
          flutter_apps_sonar_token: ${{ secrets.FLUTTER_APPS_SONAR_TOKEN }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          nexus_url: ${{ secrets.NEXUS_BASE_URL }}
          keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}
          cert_thumbprint: ${{ secrets.CERT_THUMBPRINT }}
          SM_API_KEY: ${{ secrets.SM_API_KEY }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.SM_CLIENT_CERT_PASSWORD }}
