syntax = "proto3";

package fusion.websocket.v1;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

option go_package = "fusion/internal/gen/proto/fusion;fusionpb";

message WebSocketRequest {
  string id = 1;
  int32 version = 2;
  string type = 3;
  google.protobuf.Value data = 4;
}

message WebSocketResponse {
  optional string id = 1;
  int32 version = 2;
  string type = 3;
  int32 code = 4;
  string status = 5;
  string message = 6;
  google.protobuf.Value data = 7;
  google.protobuf.Timestamp timestamp = 8;
}

message WebSocketConfigUpdateEvent {
  string mode = 1;
  google.protobuf.Struct updates = 2;
  google.protobuf.Struct state = 3;
  optional bool clear = 4;
}

message WebSocketDeviceLookupRequest {
  string device_id = 1;
}

message WebSocketUpdateDeviceInfoRequest {
  string device_id = 1;
  optional string id = 2;
  optional string location = 3;
  optional string name = 4;
}
